(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.corkgrey = function() {
	this.initialize(img.corkgrey);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txt4b = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00412A").s().p("AgEAFQgCgCAAgDQAAgCACgCQACgCACAAQADAAACACQACACAAACQAAADgCACQgCACgDAAQgCAAgCgCg");
	this.shape.setTransform(204.3,30.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00412A").s().p("AgCAtIAAhWIgeAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBBAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAQAAABAAABQAAABgBAAQAAABgBAAQAAAAgBAAIgeAAIAABWQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAQAAAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBg");
	this.shape_1.setTransform(198.5,26.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#00412A").s().p("AAeAwIAAgBIg6hRIAABPQAAABgBABQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAQgBgBAAAAQgBAAAAgBQAAgBAAgBIAAhYQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQABAAAAAAQABAAAAABQABAAAAABIA7BRIAAhPQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAIAABZQAAABAAABQAAABgBAAQAAAAgBABQgBAAAAAAIgDgBg");
	this.shape_2.setTransform(189.3,26.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00412A").s().p("AgbAlQgMgLAAgRIAAg2QAAAAAAgBQABgBAAAAQABgBAAAAQABAAABAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAAA2QAAAOAKAKQAJAJANAAQAOAAAJgJQAKgKAAgOIAAg2QAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAAA2QAAARgMALQgMAMgQAAQgPAAgMgMg");
	this.shape_3.setTransform(179.1,26.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#00412A").s().p("AggAjQgOgOAAgVQAAgUAOgOQAOgPASAAQATAAAOAPQAOAOAAAUQAAAVgOAOQgOAPgTAAQgSAAgOgPgAgcgdQgMAMAAARQAAASAMAMQANANAPAAQAQAAAMgNQAMgMAAgSQAAgRgMgMQgMgNgQAAQgQAAgMANg");
	this.shape_4.setTransform(168.3,26.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#00412A").s().p("AgaAjQgPgOAAgVQAAgUAPgOQAPgPAUAAQASAAAOALIABADQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAQgCADgDgCQgMgKgPAAQgRAAgNANQgNAMAAARQAAASANAMQANANARAAQAQAAALgKQABAAABAAQAAgBABABQAAAAABAAQAAABABAAQAAABAAAAQABAAAAAAQAAABAAAAQAAAAAAABIgBACQgOALgSAAQgUAAgPgPg");
	this.shape_5.setTransform(157.8,26.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#00412A").s().p("AgaAjQgPgOAAgVQAAgUAPgOQAPgPAUAAQASAAAOALIABADQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAQgCADgDgCQgMgKgPAAQgRAAgNANQgNAMAAARQAAASANAMQANANARAAQAQAAALgKQABAAABAAQAAgBABABQAAAAABAAQAAABABAAQAAABAAAAQABAAAAAAQAAABAAAAQAAAAAAABIgBACQgOALgSAAQgUAAgPgPg");
	this.shape_6.setTransform(147.9,26.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#00412A").s().p("AAiAxQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgJgXIgrAAIgJAXQAAABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAIgBAAQgBgBgBAAQAAgBgBAAQAAgBAAAAQAAgBABgBIAihaQAAAAAAgBQABAAAAAAQABAAAAgBQAAAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQAAABAAAAIAiBaQABABAAABQAAAAAAABQgBAAAAABQgBAAAAABgAAUARIgUg0IgTA0IAnAAg");
	this.shape_7.setTransform(139,26.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#00412A").s().p("AAeAwIAAgBIg6hRIAABPQAAABgBABQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAQgBgBAAAAQgBAAAAgBQAAgBAAgBIAAhYQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQABAAAAAAQABAAAAABQABAAAAABIA7BRIAAhPQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAIAABZQAAABAAABQAAABgBAAQAAAAgBABQgBAAAAAAIgDgBg");
	this.shape_8.setTransform(126.2,26.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#00412A").s().p("AAiAxQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgJgXIgrAAIgJAXQAAABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAIgBAAQgBgBgBAAQAAgBgBAAQAAgBAAAAQAAgBABgBIAihaQAAAAAAgBQABAAAAAAQABAAAAgBQAAAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQAAABAAAAIAiBaQABABAAABQAAAAAAABQgBAAAAABQgBAAAAABgAAUARIgUg0IgTA0IAnAAg");
	this.shape_9.setTransform(117.5,26.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#00412A").s().p("AgfAxIAAAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAhaQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIABAAIARAAQAUAAAOAOQAOAPAAATQAAAUgOAOQgOAPgUAAgAgbAqIAOAAQARAAAMgMQANgNAAgRQAAgRgNgLQgMgNgRAAIgOAAg");
	this.shape_10.setTransform(105.2,26.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#00412A").s().p("AAeAwIAAgBIg6hRIAABPQAAABgBABQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAQgBgBAAAAQgBAAAAgBQAAgBAAgBIAAhYQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQABAAAAAAQABAAAAABQABAAAAABIA7BRIAAhPQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAIAABZQAAABAAABQAAABgBAAQAAAAgBABQgBAAAAAAIgDgBg");
	this.shape_11.setTransform(95.4,26.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#00412A").s().p("AgbAlQgMgLAAgRIAAg2QAAAAAAgBQABgBAAAAQABgBAAAAQABAAABAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAAA2QAAAOAKAKQAJAJANAAQAOAAAJgJQAKgKAAgOIAAg2QAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAAA2QAAARgMALQgMAMgQAAQgPAAgMgMg");
	this.shape_12.setTransform(85.2,26.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#00412A").s().p("AgcAtIAAhaQAAAAAAgBQABgBAAAAQABgBAAAAQABAAABAAIAAAAIAxAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAIguAAIAAAnIAoAAQABAAABAAQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABQgBAAAAABQgBAAAAAAQgBABgBAAIgoAAIAAApQAAABAAABQAAABgBAAQAAABgBAAQAAAAgBAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAgBg");
	this.shape_13.setTransform(76.4,26.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#00412A").s().p("AgfAxIAAAAQgBAAgBAAQAAgBAAAAQgBgBAAAAQAAgBAAgBIAAhaQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIABAAIARAAQAUAAAOAOQAOAPAAATQAAAUgOAOQgOAPgUAAgAgbAqIAOAAQARAAAMgMQANgNAAgRQAAgRgNgLQgMgNgRAAIgOAAg");
	this.shape_14.setTransform(64.4,26.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#00412A").s().p("AAeAwIAAgBIg6hRIAABPQAAABgBABQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAQgBgBAAAAQgBAAAAgBQAAgBAAgBIAAhYQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQABAAAAAAQABAAAAABQABAAAAABIA7BRIAAhPQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAIAABZQAAABAAABQAAABgBAAQAAAAgBABQgBAAAAAAIgDgBg");
	this.shape_15.setTransform(54.6,26.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#00412A").s().p("AAiAxQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgJgXIgrAAIgJAXQAAABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAIgBAAQgBgBgBAAQAAgBgBAAQAAgBAAAAQAAgBABgBIAihaQAAAAAAgBQABAAAAAAQABAAAAgBQAAAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQAAABAAAAIAiBaQABABAAABQAAAAAAABQgBAAAAABQgBAAAAABgAAUARIgUg0IgTA0IAnAAg");
	this.shape_16.setTransform(45.9,26.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#00412A").s().p("AAeAwIAAgBIg6hRIAABPQAAABgBABQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAQgBgBAAAAQgBAAAAgBQAAgBAAgBIAAhYQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQABAAAAAAQABAAAAABQABAAAAABIA7BRIAAhPQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAIAABZQAAABAAABQAAABgBAAQAAAAgBABQgBAAAAAAIgDgBg");
	this.shape_17.setTransform(33,26.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#00412A").s().p("AgXAxIgBAAIAAAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAgBIAAhaQAAAAABgBQAAgBAAAAQABgBAAAAQABAAABAAIAxAAQABAAABAAQAAAAABABQAAAAAAABQABABAAAAQAAABgBABQAAABAAAAQgBABAAAAQgBAAgBAAIguAAIAAAnIApAAQAAAAABAAQABAAAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAAgBABQAAAAgBAAQgBABAAAAIgpAAIAAAmIAuAAQABAAABAAQAAAAABABQAAAAAAABQABABAAAAQAAABgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_18.setTransform(24.8,26.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#00412A").s().p("AgcAtIAAhaQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAAAAIAaAAQAMAAAIAIQAJAIgBAMQABALgJAIQgIAIgMAAIgXAAIAAAmQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBgAgWAAIAXAAQAJAAAHgFQAGgGAAgJQAAgIgGgHQgHgGgJAAIgXAAg");
	this.shape_19.setTransform(17.5,26.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#00412A").s().p("AggAjQgOgOAAgVQAAgUAOgOQAOgPASAAQAUAAANAPQAOAOAAAUQAAAVgOAOQgNAPgUAAQgSAAgOgPgAgcgdQgLAMgBARQABASALAMQAMANAQAAQAQAAAMgNQAMgMAAgSQAAgRgMgMQgMgNgQAAQgQAAgMANg");
	this.shape_20.setTransform(7.8,26.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#00412A").s().p("AgbAlQgMgLAAgRIAAg2QAAAAAAgBQABgBAAAAQABgBAAAAQABAAABAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAAA2QAAAOAKAKQAJAJANAAQAOAAAJgJQAKgKAAgOIAAg2QAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAAA2QAAARgMALQgMAMgQAAQgPAAgMgMg");
	this.shape_21.setTransform(189.4,10.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#00412A").s().p("AggAjQgOgOAAgVQAAgUAOgOQAOgPASAAQATAAAOAPQAOAOAAAUQAAAVgOAOQgOAPgTAAQgSAAgOgPgAgcgdQgMAMAAARQAAASAMAMQANANAPAAQAQAAAMgNQAMgMAAgSQAAgRgMgMQgMgNgQAAQgQAAgMANg");
	this.shape_22.setTransform(178.7,10.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#00412A").s().p("AgCAtIAAgrIghgsQgBgBAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBIADgBQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAeAqIAfgqQAAgBAAAAQAAAAABAAQAAgBAAAAQAAAAABAAIACABQABABAAAAQABABAAAAQAAABAAAAQAAABgBABIghArIAAAsQAAABAAABQAAAAAAABQgBAAAAABQgBAAgBAAQAAAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBg");
	this.shape_23.setTransform(169.7,10.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#00412A").s().p("AAeAwIAAgBIg6hRIAABPQAAABgBABQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAQgBgBAAAAQgBAAAAgBQAAgBAAgBIAAhYQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQABAAAAAAQABAAAAABQABAAAAABIA7BRIAAhPQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAIAABZQAAABAAABQAAABgBAAQAAAAgBABQgBAAAAAAIgDgBg");
	this.shape_24.setTransform(157,10.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#00412A").s().p("AgXAxIgBAAIAAAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAhaQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAyAAQAAAAABAAQAAAAABABQAAAAAAABQABABAAAAQAAABgBABQAAABAAAAQgBABAAAAQgBAAAAAAIgvAAIAAAnIApAAQAAAAABAAQABAAAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAAgBABQAAAAgBAAQgBAAAAAAIgpAAIAAAnIAvAAQAAAAABAAQAAAAABABQAAAAAAABQABABAAAAQAAABgBABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_25.setTransform(148.7,10.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#00412A").s().p("AAZAtIAAgqIgxAAIAAAqQAAABAAABQAAABgBAAQAAABgBAAQgBAAgBAAQAAAAgBAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAhaQAAAAAAgBQAAgBABAAQAAgBABAAQABAAAAAAQABAAABAAQABAAAAABQABAAAAABQAAABAAAAIAAArIAxAAIAAgrQAAAAABgBQAAgBAAAAQABgBAAAAQABAAABAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAIAABaQAAABAAABQAAABgBAAQAAABgBAAQgBAAAAAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAgBg");
	this.shape_26.setTransform(140,10.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#00412A").s().p("AAcAxIAAAAIgCgBIAAAAIgBgBIAAgBIgZg6IgYA6IAAABIgBABIgCABIgCgBIgBAAIgBgCIgmhZQAAgBAAAAQAAgBAAgBQAAAAABgBQABAAAAAAQABgBABAAQABAAAAAAQABABAAAAQABABAAAAIAjBTIAZg6QAAgBABAAQAAAAAAgBQABAAAAAAQAAAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAAAABIAZA6IAjhTQABAAAAgBQABAAAAgBQABAAABAAQAAAAABABQABAAAAAAQABABAAAAQAAABAAABQAAAAgBABIgmBZIgCADg");
	this.shape_27.setTransform(128.6,10.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#00412A").s().p("AgZAiQgJgOgBgUQABgTAJgOQALgPAOAAQAQAAAKAPQAJAOAAATQAAAUgJAOQgKAPgQAAQgOAAgLgPgAgMgYQgHAKAAAOQAAAPAHAKQAGAJAGAAQAHAAAGgJQAHgKAAgPQAAgOgHgKQgGgJgHAAQgGAAgGAJg");
	this.shape_28.setTransform(112.7,10.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#00412A").s().p("AgZAiQgJgOgBgUQABgTAJgOQAKgPAPAAQAQAAAKAPQAJAOAAATQAAAUgJAOQgKAPgQAAQgPAAgKgPgAgMgYQgHAKAAAOQAAAPAHAKQAGAJAGAAQAIAAAFgJQAHgKAAgPQAAgOgHgKQgGgJgHAAQgGAAgGAJg");
	this.shape_29.setTransform(103.6,10.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#00412A").s().p("AgZAiQgJgOAAgUQAAgTAJgOQAKgPAPAAQAQAAAKAPQAKAOAAATQAAAUgKAOQgKAPgQAAQgPAAgKgPgAgMgYQgHAKAAAOQAAAPAHAKQAGAJAGAAQAHAAAGgJQAHgKAAgPQAAgOgHgKQgGgJgHAAQgGAAgGAJg");
	this.shape_30.setTransform(94.5,10.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#00412A").s().p("AgLAQQAAgDADgBQAJgDAAgJQgHgBAAgIIAAgBQAAgEACgDQADgCADAAQAFAAADADQACADAAAGIAAACQAAAMgHAHQgFAGgHAAQgEAAAAgEg");
	this.shape_31.setTransform(89.6,15.3);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#00412A").s().p("AADAuQgCgBAAgDIAAhEIgFACIgEABQgEAAgCgDQgCgDABgDQABgDACgBIARgLIAAAAIABAAIABAAIAAgBIABAAIABAAIABAAIAAAAIABABIABAAIABAAIAAABIABAAIAAABIABAAIAAAAIAAABIABAAIAAABIAAAAIAAABIAAABIAABTQAAADgCABQgCADgDAAQgEAAgCgDg");
	this.shape_32.setTransform(85.9,10.4);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#00412A").s().p("AgCA7QAAgBgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAgJQgPgCgNgJQgEgCAAgFQAAgDACgCQACgCAEAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQAKAIALACIAAgcQgQgEgHgGQgHgGAAgMQAAgLAIgHQAIgIANgBIAAgDQAAAAAAgBQAAAAABgBQAAgBAAAAQABAAAAgBQABAAAAgBQABAAAAAAQAAgBAAAAQABAAAAAAQABAAAAAAQABAAABABQAAAAABAAQAAABABAAQAAABAAAAQABAAAAABQAAABAAAAQAAABAAAAIAAAEQAMABAKAGQAEADAAAEQAAADgCACQgCADgEAAIgEgCQgHgEgHgCIAAAbQAQAEAHAGQAHAHAAALQAAALgIAIQgIAHgOABIAAAJQAAAAAAABQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAABQgBAAAAAAQgBAAgBABQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAAAgBAAQAAgBgBAAgAAHAgQAOgBAAgLQAAgFgDgDQgDgDgIgCgAgRgZQAAAFADADQADADAIACIAAgZQgOACAAAKg");
	this.shape_33.setTransform(80.3,10.7);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#00412A").s().p("AghAjQgOgOAAgVQAAgTAOgQQAOgPATABQAUgBAOAPQAOAQAAATQAAAUgOAPQgOAPgUABQgTgBgOgPgAgWgXQgJAJAAAOQAAAOAJAKQAKALAMgBQANABAJgLQAKgKAAgOQAAgNgKgKQgJgKgNAAQgMAAgKAKg");
	this.shape_34.setTransform(67.1,10.3);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#00412A").s().p("AgFAuQgCgBABgDIAAhLIgXAAQgDAAgCgCQgCgCAAgEQAAgCACgDQACgCADAAIA7AAQADAAADACQACADAAACQAAAEgCACQgDACgDAAIgWAAIAABLQAAADgDABQgBADgEAAQgCAAgDgDg");
	this.shape_35.setTransform(57.5,10.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#00412A").s().p("AgcAuQgCgBAAgDIAAhTQAAgCACgDQACgCADAAIAYAAQANAAAJAJQAIAJABAMQgBAMgIAIQgJAJgNAAIgQAAIAAAfQAAADgCABQgDADgDAAQgDAAgCgDgAgPgDIAQAAQAHAAADgFQAFgEAAgGQAAgGgFgEQgDgFgHAAIgQAAg");
	this.shape_36.setTransform(46.9,10.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#00412A").s().p("AgbAlQgNgMAAgRIAAgxQAAgCADgDQACgCADAAQADAAADACQACADAAACIAAAxQAAALAIAHQAHAIAJAAQALAAAHgIQAHgHAAgLIAAgxQAAgCADgDQACgCADAAQADAAACACQACADAAACIAAAxQAAARgLAMQgMAMgRAAQgPAAgMgMg");
	this.shape_37.setTransform(37.2,10.4);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#00412A").s().p("AgFAuQgBgBAAgDIAAhLIgXAAQgDAAgCgCQgCgCAAgEQAAgCACgDQACgCADAAIA7AAQADAAADACQACADAAACQAAAEgCACQgDACgDAAIgWAAIAABLQgBADgCABQgCADgDAAQgCAAgDgDg");
	this.shape_38.setTransform(24.5,10.4);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#00412A").s().p("AgWAxQgDAAgCgDQgCgBAAgDIAAhTQAAgCACgDQACgCADAAIAtAAQADAAACACQACADAAACQAAAEgCACQgCACgDAAIglAAIAAAaIAgAAQADAAACACQACADABACQgBADgCADQgCACgDAAIggAAIAAAaIAlAAQADAAACABQACADAAAEQAAADgCABQgCADgDAAg");
	this.shape_39.setTransform(17.1,10.4);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#00412A").s().p("AgbAkQgPgPAAgVQAAgUAPgPQAPgPAUABQASgBAOALQADADAAADQABADgCADQgCACgEABQgDABgDgDQgKgHgMAAQgOgBgKALQgLAKAAANQAAAOALAKQAKALAOgBQAKABAJgGIAAgTIgUAAQgDAAgCgDQgCgCAAgDQAAgCACgDQACgCADAAIAcAAIAAAAQAEAAACACQACADAAACIAAAfIAAACIAAABIgDAEQgOALgSAAQgUAAgPgPg");
	this.shape_40.setTransform(7.4,10.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt4b, new cjs.Rectangle(0,0,207,36.6), null);


(lib.txt4a2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgKALQgFgEAAgHQAAgFAFgFQAFgFAFAAQAGAAAFAFQAFAFAAAFQAAAHgFAEQgEAFgHAAQgFAAgFgFg");
	this.shape.setTransform(268.3,69.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AghBJIAAAAQgFABgEgEQgDgEAAgEIAAh7QAAgFADgDQAEgDAFgBIAAAAIBDAAQAFABADADQAEADAAAFQAAAFgEADQgDAEgFAAIg4AAIAAAnIAwAAQAFAAADADQAEADAAAEQAAAEgEAEQgDADgFAAIgwAAIAAAnIA4AAQAFAAADADQAEAEAAAFQAAAEgEAEQgDAEgFgBg");
	this.shape_1.setTransform(260.3,63.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAjBFIgBgCIhChcIAABWQAAAFgDADQgEAEgEAAQgFAAgDgEQgEgDAAgFIAAh5IAAAAQAAgGAFgEQAEgCAFAAQAEABADAEIBDBdIAAhWQAAgEADgEQADgDAFAAQAFAAADADQAEAEAAAEIAAB5QAAAFgEADQgDAEgFAAQgFAAgEgEg");
	this.shape_2.setTransform(246.2,63.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgIBGQgDgDAAgFIAAh7QAAgFADgDQAEgDAEgBQAEABAEADQAEADAAAFIAAB7QAAAEgEAEQgEAEgEgBQgEABgEgEg");
	this.shape_3.setTransform(236.5,63.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AghBJIAAAAQgFABgEgEQgDgEAAgEIAAh7QAAgFADgDQAEgDAFgBQAEABAEADQADADAAAFIAABvIA4AAQAFAAADADQAEAEAAAFQAAAEgEAEQgDAEgFgBg");
	this.shape_4.setTransform(229,63.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgqBJQgFABgEgEQgDgEAAgEIAAh7QAAgFADgDQAEgDAFgBIAYAAQAeAAAVAWQAWAVAAAeQAAAfgWAVQgVAVgeAAgAgfAyIANAAQAUAAAPgPQAOgPAAgUQAAgUgOgPQgPgOgUAAIgNAAg");
	this.shape_5.setTransform(215.8,63.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAkBCIgKgbIgzAAIgKAbQgDAIgIgBIgEAAQgEgCgCgEQgCgFABgEIAvh7QADgHAHgBQAIABADAHIAuB7QACAEgCAFQgCAEgEACIgEAAQgIABgDgIgAARAQIgRgsIgQAsIAhAAg");
	this.shape_6.setTransform(202.7,63.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AghBJIAAAAQgFABgEgEQgDgEAAgEIAAh7QAAgFADgDQAEgDAFgBIAAAAIBDAAQAFABADADQAEADAAAFQAAAFgEADQgDAEgFAAIg4AAIAAAnIAwAAQAFAAADADQAEADAAAEQAAAEgEAEQgDADgFAAIgwAAIAAAnIA4AAQAFAAADADQAEAEAAAFQAAAEgEAEQgDAEgFgBg");
	this.shape_7.setTransform(190.9,63.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgqBJQgFABgEgEQgDgEAAgEIAAh7QAAgFADgDQAEgDAFgBIAYAAQAeAAAVAWQAWAVAAAeQAAAfgWAVQgVAVgeAAgAgfAyIANAAQAUAAAPgPQAOgPAAgUQAAgUgOgPQgPgOgUAAIgNAAg");
	this.shape_8.setTransform(177.8,63.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAjBEIgjgxIgiAxQgEAFgFAAQgFAAgCgDQgFgCAAgFQgBgFADgEIAog2Igog1QgDgEABgFQAAgFAFgCQAEgDAEAAQAFABADAEIAiAxIAjgxQADgEAFgBQAEAAAEADQAFACAAAFQABAFgDAEIgoA1IAoA2QADAEgBAFQAAAFgFACQgDADgDAAQgGAAgEgFg");
	this.shape_9.setTransform(158,63.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAkBCIgKgbIgzAAIgKAbQgDAIgIgBIgEAAQgEgCgCgEQgCgFABgEIAvh7QADgHAHgBQAIABADAHIAuB7QACAEgCAFQgCAEgEACIgEAAQgIABgDgIgAARAQIgRgsIgQAsIAhAAg");
	this.shape_10.setTransform(145.2,63.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgIBGQgDgDAAgFIAAhvIghAAQgFAAgDgEQgDgDgBgFQABgFADgDQADgDAFgBIBZAAQAFABADADQAEADAAAFQAAAFgEADQgDAEgFAAIghAAIAABvQAAAFgEADQgDAEgFgBQgEABgEgEg");
	this.shape_11.setTransform(132.2,63.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AghBJIAAAAQgFABgEgEQgDgEAAgEIAAh7QAAgFADgDQAEgDAFgBIAAAAIBDAAQAFABADADQAEADAAAFQAAAFgEADQgDAEgFAAIg4AAIAAAnIAwAAQAFAAADADQAEADAAAEQAAAEgEAEQgDADgFAAIgwAAIAAAnIA4AAQAFAAADADQAEAEAAAFQAAAEgEAEQgDAEgFgBg");
	this.shape_12.setTransform(115.5,63.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAfBGQgEgDAAgFIAAgzIg2AAIAAAzQAAAFgDADQgEAEgEgBQgFABgEgEQgCgDAAgFIAAh7QAAgFACgDQAEgDAFgBQAEABAEADQADADAAAFIAAAzIA2AAIAAgzQAAgFAEgDQACgDAGgBQAEABAEADQADADAAAFIAAB7QAAAFgDADQgEAEgEgBQgGABgCgEg");
	this.shape_13.setTransform(102.2,63.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgIBGQgDgDAAgFIAAhvIghAAQgFAAgDgEQgDgDgBgFQABgFADgDQADgDAFgBIBZAAQAFABADADQAEADAAAFQAAAFgEADQgDAEgFAAIghAAIAABvQAAAFgEADQgDAEgFgBQgEABgEgEg");
	this.shape_14.setTransform(89,63.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AghBJIAAAAQgFABgEgEQgDgEAAgEIAAh7QAAgFADgDQAEgDAFgBIAAAAIBDAAQAFABADADQAEADAAAFQAAAFgEADQgDAEgFAAIg4AAIAAAnIAwAAQAFAAADADQAEADAAAEQAAAEgEAEQgDADgFAAIgwAAIAAAnIA4AAQAFAAADADQAEAEAAAFQAAAEgEAEQgDAEgFgBg");
	this.shape_15.setTransform(72.3,63.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AguBGQgDgEAAgEIAAh7QAAgFADgDQADgDAFgBIAmAAQARAAAOANQANAOAAASQAAAWgRAMQAFAEADAEQAHAKAAAMQgBAIACAFQAFABACAGQABAFgCAEQgCAEgEACIgFAAQgFABgEgDQgDgDgDgFQgFgJAAgQQAAgFgCgEQgCgCgEgDQgGgEgFgCIgZAAIAAAuQAAAEgDAEQgEAEgFgBQgFABgDgEgAgagGIAaAAQAIAAAGgGQAGgGAAgKQAAgJgGgGQgGgGgIAAIgaAAg");
	this.shape_16.setTransform(60.4,63.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgyA1QgVgWAAgfQAAgeAVgWQAVgWAdAAQAeAAAUAWQAWAWAAAeQAAAfgWAWQgUAWgeAAQgdAAgVgWgAghgkQgOAPAAAVQAAAWAOAOQAOAQATAAQATAAAPgQQAOgOAAgWQAAgVgOgPQgOgPgUAAQgTAAgOAPg");
	this.shape_17.setTransform(45.3,63.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgqBGQgDgEAAgEIAAh7QAAgFADgDQAEgDAFgBIAAAAIBDAAQAFABADADQAEADAAAFQAAAFgEADQgDAEgFAAIg4AAIAAAnIAwAAQAFAAADADQAEADAAAEQAAAEgEAEQgDADgFAAIgwAAIAAAzQAAAEgDAEQgEAEgEgBQgFABgEgEg");
	this.shape_18.setTransform(31.7,63.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AghBJIAAAAQgFABgEgEQgDgEAAgEIAAh7QAAgFADgDQAEgDAFgBIAAAAIBDAAQAFABADADQAEADAAAFQAAAFgEADQgDAEgFAAIg4AAIAAAnIAwAAQAFAAADADQAEADAAAEQAAAEgEAEQgDADgFAAIgwAAIAAAnIA4AAQAFAAADADQAEAEAAAFQAAAEgEAEQgDAEgFgBg");
	this.shape_19.setTransform(20.2,63.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgiBJIgBAAQgFABgDgEQgDgEAAgEIAAh7QAAgFADgDQADgDAFgBIABAAIAdAAQAQAAALAMQAMAMAAAQQAAANgIALQAVANAAAYQAAATgNAOQgNAMgTAAgAgXAyIAZAAQAJAAAGgGQAHgHAAgJQAAgIgHgHQgGgGgJAAIgZAAgAgXgQIASAAQAGAAAFgEQAFgGAAgHQAAgHgFgFQgFgEgGAAIgSAAg");
	this.shape_20.setTransform(8.9,63.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAkBCIgKgbIgzAAIgKAbQgDAHgIAAIgEAAQgEgCgCgFQgCgDABgGIAvh6QADgHAHAAQAIAAADAHIAuB6QACAGgCADQgCAFgEACIgEAAQgIAAgDgHgAARAQIgRgsIgQAsIAhAAg");
	this.shape_21.setTransform(228.9,39.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AguBGQgDgDAAgFIAAh7QAAgFADgDQADgEAFABIAmAAQARgBAOANQANAOAAATQAAAUgRANQAFADADAFQAHAKAAAMQgBAHACAGQAFABACAGQABAEgCAFQgCAEgEACIgFABQgFgBgEgCQgDgDgDgEQgFgKAAgQQAAgFgCgEQgCgCgEgEQgGgDgFgBIgZAAIAAAtQAAAFgDADQgEADgFAAQgFAAgDgDgAgagGIAaAAQAIAAAGgGQAGgHAAgIQAAgKgGgGQgGgGgIAAIgaAAg");
	this.shape_22.setTransform(216.6,39.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgHBGQgDgDAAgFIAAh7QAAgFADgDQADgEAEABQAFgBADAEQADADAAAFIAAB7QAAAFgDADQgDADgFAAQgEAAgDgDg");
	this.shape_23.setTransform(207.8,39.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAjBFIgBgCIhChcIAABWQAAAFgDADQgEAEgEAAQgFAAgDgEQgEgDAAgFIAAh5IAAAAQAAgGAFgEQAEgCAFAAQAEABADAEIBDBdIAAhWQAAgEADgEQADgDAFAAQAFAAADADQAEAEAAAEIAAB5QAAAFgEADQgDAEgFAAQgFAAgEgEg");
	this.shape_24.setTransform(191.6,39.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAkBCIgKgbIgzAAIgKAbQgDAHgIAAIgEAAQgEgCgCgFQgCgDABgGIAvh6QADgHAHAAQAIAAADAHIAuB6QACAGgCADQgCAFgEACIgEAAQgIAAgDgHgAARAQIgRgsIgQAsIAhAAg");
	this.shape_25.setTransform(178.4,39.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgqBJQgFAAgEgDQgDgDAAgFIAAh7QAAgFADgDQAEgEAFABIAYAAQAegBAVAWQAWAVAAAeQAAAfgWAVQgVAWgegBgAgfAyIANAAQAUAAAPgOQAOgPAAgVQAAgUgOgPQgPgOgUAAIgNAAg");
	this.shape_26.setTransform(159.6,39.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAjBFIgBgCIhChcIAABWQAAAFgDADQgEAEgEAAQgFAAgDgEQgEgDAAgFIAAh5IAAAAQAAgGAFgEQAEgCAFAAQAEABADAEIBDBdIAAhWQAAgEADgEQADgDAFAAQAFAAADADQAEAEAAAEIAAB5QAAAFgEADQgDAEgFAAQgFAAgEgEg");
	this.shape_27.setTransform(144.5,39.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgqA3QgSgRAAgZIAAhKQAAgFAEgDQADgEAFABQAFgBADAEQAEADAAAFIAABKQAAAQALAKQALALAOAAQAQAAAKgLQALgKAAgQIAAhKQAAgFAEgDQADgEAFABQAFgBADAEQAEADAAAFIAABKQAAAZgSARQgSASgZAAQgYAAgSgSg");
	this.shape_28.setTransform(129,39.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgqBGQgDgDAAgFIAAh7QAAgFADgDQAEgEAFABIAAAAIBDAAQAFgBADAEQAEADAAAFQAAAFgEADQgDAEgFAAIg4AAIAAAnIAwAAQAFgBADAEQAEADAAAEQAAAFgEADQgDAEgFgBIgwAAIAAAzQAAAFgDADQgEADgEAAQgFAAgEgDg");
	this.shape_29.setTransform(115.8,39.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgqBJQgFAAgEgDQgDgDAAgFIAAh7QAAgFADgDQAEgEAFABIAYAAQAegBAVAWQAWAVAAAeQAAAfgWAVQgVAWgegBgAgfAyIANAAQAUAAAPgOQAOgPAAgVQAAgUgOgPQgPgOgUAAIgNAAg");
	this.shape_30.setTransform(97.3,39.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AAjBFIgBgCIhChcIAABWQAAAFgDADQgEAEgEAAQgFAAgDgEQgEgDAAgFIAAh5IAAAAQAAgGAFgEQAEgCAFAAQAEABADAEIBDBdIAAhWQAAgEADgEQADgDAFAAQAFAAADADQAEAEAAAEIAAB5QAAAFgEADQgDAEgFAAQgFAAgEgEg");
	this.shape_31.setTransform(82.3,39.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAkBCIgKgbIgzAAIgKAbQgDAHgIAAIgEAAQgEgCgCgFQgCgDABgGIAvh6QADgHAHAAQAIAAADAHIAuB6QACAGgCADQgCAFgEACIgEAAQgIAAgDgHgAARAQIgRgsIgQAsIAhAAg");
	this.shape_32.setTransform(69.1,39.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AAjBFIgBgCIhChcIAABWQAAAFgDADQgEAEgEAAQgFAAgDgEQgEgDAAgFIAAh5IAAAAQAAgGAFgEQAEgCAFAAQAEABADAEIBDBdIAAhWQAAgEADgEQADgDAFAAQAFAAADADQAEAEAAAEIAAB5QAAAFgEADQgDAEgFAAQgFAAgEgEg");
	this.shape_33.setTransform(49.3,39.2);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AghBJIAAAAQgFAAgEgDQgDgDAAgFIAAh7QAAgFADgDQAEgEAFABIAAAAIBDAAQAFgBADAEQAEADAAAFQAAAFgEADQgDAEgFAAIg4AAIAAAnIAwAAQAFgBADAEQAEADAAAEQAAAFgEADQgDAEgFgBIgwAAIAAAnIA4AAQAFAAADAEQAEADAAAFQAAAFgEADQgDADgFAAg");
	this.shape_34.setTransform(36.8,39.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgrBGQgDgDAAgFIAAh7QAAgFADgDQADgEAGABIAkAAQATgBANANQANAOAAATQAAASgNAMQgNANgTABIgZAAIAAAtQAAAFgDADQgEADgEAAQgGAAgDgDgAgXgGIAZAAQAJAAAHgGQAGgHAAgIQAAgKgGgGQgHgGgJAAIgZAAg");
	this.shape_35.setTransform(25.8,39.1);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgyA1QgVgWAAgfQAAgeAVgWQAVgWAdgBQAeABAUAWQAWAXAAAdQAAAfgWAWQgUAXgegBQgdABgVgXgAghgkQgOAPAAAVQAAAWAOAPQAOAOATAAQATAAAPgOQAOgPAAgWQAAgUgOgQQgOgPgUAAQgTAAgOAPg");
	this.shape_36.setTransform(10.7,38.9);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgyA1QgVgWAAgfQAAgeAVgWQAVgXAdAAQAeAAAUAXQAWAXAAAdQAAAfgWAWQgUAXgeAAQgdAAgVgXgAghgkQgOAPAAAVQAAAWAOAPQAOAPATgBQATABAPgPQAOgQAAgVQAAgVgOgPQgOgPgUAAQgTAAgOAPg");
	this.shape_37.setTransform(256.9,14.4);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgHBGQgDgDgBgFIAAhvIghAAQgFAAgDgEQgEgDAAgFQAAgFAEgDQADgDAFAAIBZAAQAFAAADADQADADAAAFQAAAFgDADQgDAEgFAAIgiAAIAABvQAAAFgDADQgDADgFABQgEgBgDgDg");
	this.shape_38.setTransform(242.3,14.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgHBFQgEgDAAgFIAAg5Igqg6QgDgDAAgFQABgFAEgCQAEgDAFAAQAEABADAEIAjAxIAkgxQADgEAEgBQAFAAAEADQAEACAAAFQABAFgDADIgrA6IAAA5QAAAFgDADQgDAEgFAAQgEAAgDgEg");
	this.shape_39.setTransform(225.6,14.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AAkBCIgKgbIgzAAIgKAbQgDAHgIABIgEgBQgEgCgCgFQgCgEABgFIAvh6QADgIAHABQAIgBADAIIAuB6QACAFgCAEQgCAFgEACIgEABQgIgBgDgHgAARAQIgRgtIgQAtIAhAAg");
	this.shape_40.setTransform(213.2,14.6);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgqBKQgFgBgEgDQgDgEAAgEIAAh7QAAgFADgDQAEgDAFAAIAYAAQAeAAAVAVQAWAWAAAdQAAAegWAWQgVAWgeAAgAgfAyIANAAQAUAAAPgOQAOgPAAgVQAAgUgOgOQgPgPgUAAIgNAAg");
	this.shape_41.setTransform(199.7,14.6);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgHBGQgDgDAAgFIAAhvIgiAAQgFAAgDgEQgEgDABgFQgBgFAEgDQADgDAFAAIBZAAQAFAAADADQAEADgBAFQABAFgEADQgDAEgFAAIgiAAIAABvQABAFgEADQgDADgFABQgEgBgDgDg");
	this.shape_42.setTransform(180.9,14.6);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("Ag0A3QgEgDAAgFQgBgEADgEQADgDAEgBQAFgBADAEQAUAQATgBQAQABALgIQAJgGAAgJQAAgEgCgDQgCgEgEgCQgKgGgSgEIgBAAQgQgDgLgFQgNgGgGgJQgFgJAAgJQAAgSARgNQAPgKAUgBQAUAAAaARQADADABAEQABAFgCADQgDAEgEABQgEABgEgDQgUgOgOAAQgNAAgKAIQgIAGAAAHQAAADACADIAGAFQAIAGARAEIAAAAQASADALAFQAPAHAGAKQAFAIAAAKQAAAUgSANQgQALgXABQgagBgagUg");
	this.shape_43.setTransform(168.4,14.4);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AAkBCIgKgbIgzAAIgKAbQgDAHgIABIgEgBQgEgCgCgFQgCgEABgFIAvh6QADgIAHABQAIgBADAIIAuB6QACAFgCAEQgCAFgEACIgEABQgIgBgDgHgAARAQIgRgtIgQAtIAhAAg");
	this.shape_44.setTransform(155.7,14.6);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AghBKIAAAAQgFgBgEgDQgDgEAAgEIAAh7QAAgEADgEQAEgDAFAAQAEAAAEADQADAEAAAEIAABvIA4AAQAFAAADAEQAEADAAAFQAAAEgEAEQgDADgFABg");
	this.shape_45.setTransform(144.6,14.6);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AguBGQgDgEAAgEIAAh7QAAgFADgDQADgDAFAAIAmAAQARAAAOANQANANAAATQAAAUgRANQAFADADAFQAHAKAAANQgBAGACAGQAFACACAFQABAFgCAEQgCAEgEACIgFABQgFAAgEgDQgDgCgDgFQgFgKAAgPQAAgGgCgDQgCgDgEgEQgGgDgFgBIgZAAIAAAtQAAAEgDAEQgEADgFABQgFgBgDgDgAgagGIAaAAQAIAAAGgGQAGgHAAgIQAAgJgGgHQgGgGgIAAIgaAAg");
	this.shape_46.setTransform(127.3,14.6);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgqA4QgSgSAAgZIAAhKQAAgFAEgDQADgDAFAAQAFAAADADQAEADAAAFIAABKQAAAPALALQALALAOAAQAQAAAKgLQALgLAAgPIAAhKQAAgFAEgDQADgDAFAAQAFAAADADQAEADAAAFIAABKQAAAZgSASQgSARgZABQgYgBgSgRg");
	this.shape_47.setTransform(112.6,14.6);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgyA1QgVgWAAgfQAAgeAVgWQAVgXAdAAQAeAAAUAXQAWAXAAAdQAAAfgWAWQgUAXgeAAQgdAAgVgXgAghgkQgOAPAAAVQAAAWAOAPQAOAPATgBQATABAPgPQAOgQAAgVQAAgVgOgPQgOgPgUAAQgTAAgOAPg");
	this.shape_48.setTransform(96.2,14.4);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgHBFQgEgDAAgFIAAg5Igqg6QgDgDAAgFQABgFAEgCQAEgDAFAAQAEABADAEIAjAxIAkgxQADgEAEgBQAFAAAEADQAEACAAAFQABAFgDADIgrA6IAAA5QAAAFgDADQgDAEgFAAQgEAAgDgEg");
	this.shape_49.setTransform(82.8,14.7);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("Ag0A3QgEgDAAgFQgBgEADgEQADgDAEgBQAFgBADAEQAUAQATgBQAQABALgIQAJgGAAgJQAAgEgCgDQgCgEgEgCQgKgGgSgEIgBAAQgQgDgLgFQgNgGgGgJQgFgJAAgJQAAgSARgNQAPgKAUgBQAUAAAaARQADADABAEQABAFgCADQgDAEgEABQgEABgEgDQgUgOgOAAQgNAAgKAIQgIAGAAAHQAAADACADIAGAFQAIAGARAEIAAAAQASADALAFQAPAHAGAKQAFAIAAAKQAAAUgSANQgQALgXABQgagBgagUg");
	this.shape_50.setTransform(64.8,14.4);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgHBGQgDgDAAgFIAAh7QAAgFADgDQADgDAEAAQAFAAADADQADADAAAFIAAB7QAAAEgDAEQgDADgFABQgEgBgDgDg");
	this.shape_51.setTransform(55.7,14.6);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("Ag0A3QgEgDAAgFQgBgEADgEQADgDAEgBQAFgBADAEQAUAQATgBQAQABALgIQAJgGAAgJQAAgEgCgDQgCgEgEgCQgKgGgSgEIgBAAQgQgDgLgFQgNgGgGgJQgFgJAAgJQAAgSARgNQAPgKAUgBQAUAAAaARQADADABAEQABAFgCADQgDAEgEABQgEABgEgDQgUgOgOAAQgNAAgKAIQgIAGAAAHQAAADACADIAGAFQAIAGARAEIAAAAQASADALAFQAPAHAGAKQAFAIAAAKQAAAUgSANQgQALgXABQgagBgagUg");
	this.shape_52.setTransform(41.1,14.4);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgHBGQgEgDAAgFIAAh7QAAgFAEgDQADgDAEAAQAEAAAEADQADADABAFIAAB7QgBAEgDAEQgEADgEABQgEgBgDgDg");
	this.shape_53.setTransform(32,14.6);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AAfBGQgEgDAAgFIAAgyIg2AAIAAAyQABAFgEADQgDADgFABQgFgBgDgDQgDgDAAgFIAAh7QAAgFADgDQADgDAFAAQAFAAADADQAEADgBAFIAAAyIA2AAIAAgyQAAgFAEgDQACgDAGAAQAFAAADADQADADABAFIAAB7QgBAFgDADQgDADgFABQgGgBgCgDg");
	this.shape_54.setTransform(21.9,14.6);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgIBGQgCgDAAgFIAAhvIgiAAQgFAAgDgEQgDgDAAgFQAAgFADgDQADgDAFAAIBZAAQAEAAAEADQADADAAAFQAAAFgDADQgEAEgEAAIgiAAIAABvQAAAFgDADQgEADgEABQgEgBgEgDg");
	this.shape_55.setTransform(8.7,14.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt4a2, new cjs.Rectangle(0,0,281,77.5), null);


(lib.txt_taxday = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAaAxIgBgBIgvhBIAAA9QAAADgDADQgCACgDAAQgEAAgCgCQgDgDAAgDIAAhWQAAgFAEgCQADgCADAAQADABACADIAwBCIAAg9QAAgDACgDQACgCAEAAQADAAADACQACADAAADIAABWQAAADgCADQgDACgDAAQgEAAgCgDg");
	this.shape.setTransform(161.1,11);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAdA0IgCAAIgBAAIgBAAIgBgBIgBgBIgBgBIgBAAIAAgBIgBAAIAAgBIgUgvIgTAvIAAABIgBABIgBABIgBAAIgBABIAAAAIgBABIgBAAIgBAAIgCAAIAAAAIgBgBIgCgBIgBgBIAAAAIgBgBIgBgBIglhXQgBgDABgDQACgDADgBQADgCADABQADACACADIAdBEIATgtQACgFAFAAQAGAAACAFIATAtIAdhEQACgDADgCQADgBADACQADABACADQABADgBADIglBXIgBABIAAAAIgBABIgBABIAAAAIgBABIgBAAIgBABg");
	this.shape_1.setTransform(148.1,11.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgjAmQgPgQAAgWQAAgVAPgQQAOgQAVAAQAWAAAOAQQAPAQAAAVQAAAWgPAQQgOAQgWAAQgUAAgPgQgAgXgaQgKALAAAPQAAAQAKAKQAKALANAAQAOAAAKgLQAKgKAAgQQAAgPgKgLQgKgKgOAAQgNAAgKAKg");
	this.shape_2.setTransform(134.1,10.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgeA1QgDAAgDgDQgCgCAAgEIAAhXQAAgEACgCQADgDADABIASAAQAUAAAQAPQAPAPAAAVQAAAWgPAPQgPAPgVABgAgWAkIAKAAQAOgBAKgJQALgLAAgPQAAgOgLgKQgKgLgOAAIgKAAg");
	this.shape_3.setTransform(123.4,11);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgFAyQgCgCAAgEIAAhPIgYAAQgDAAgDgDQgCgCAAgDQAAgEACgCQACgDAEABIA/AAQADgBADADQACADAAADQAAADgCACQgDADgDAAIgYAAIAABPQAAAEgCACQgDADgDAAQgCAAgDgDg");
	this.shape_4.setTransform(113.8,11);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAaAxIgBgBIgvhBIAAA9QAAADgDADQgCACgDAAQgEAAgCgCQgDgDAAgDIAAhWQAAgFAEgCQADgCADAAQADABACADIAwBCIAAg9QAAgDACgDQACgCAEAAQADAAADACQACADAAADIAABWQAAADgCADQgDACgDAAQgEAAgCgDg");
	this.shape_5.setTransform(103.8,11);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgeAoQgNgNABgSIAAg0QgBgEADgCQADgDADABQADgBADADQADADAAADIAAA0QgBALAIAIQAIAIAKAAQALAAAIgIQAIgIAAgLIAAg0QAAgDADgDQACgDADABQADgBADADQACACAAAEIAAA0QAAASgMANQgNANgSAAQgRAAgNgNg");
	this.shape_6.setTransform(92.8,11);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgjAmQgPgQAAgWQAAgVAPgQQAOgQAVAAQAWAAAOAQQAPAQAAAVQAAAWgPAQQgOAQgWAAQgUAAgPgQgAgXgaQgKALAAAPQAAAQAKAKQAKALANAAQAOAAAKgLQAKgKAAgQQAAgPgKgLQgKgKgOAAQgNAAgKAKg");
	this.shape_7.setTransform(81.2,10.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgeAmQgPgQAAgWQAAgVAPgQQARgQAWAAQATAAAPALQADADABADQAAAEgCADQgCADgEAAQgDABgEgCQgJgJgOAAQgPAAgLALQgMALAAAOQAAAQAMAKQALALAPAAQAOAAAJgJQAEgBADAAQAEABACACQACADAAADQgBAEgDADQgPALgTAAQgWAAgRgQg");
	this.shape_8.setTransform(70,10.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgFAyQgCgDAAgDIAAgpIgfgpQgCgCABgEQAAgDADgCQADgCADAAQADABACADIAZAjIAagjQACgDADgBQADAAADACQADACAAADQABAEgCACIgfApIAAApQAAADgCADQgDACgDAAQgCAAgDgCg");
	this.shape_9.setTransform(57.2,11);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAaAvIgIgTIgjAAIgHATQgDAGgFAAIgDgBQgDgBgCgDQgBgDABgEIAhhXQACgFAFAAQAGAAACAFIAhBXQABAEgBADQgCADgDABIgDABQgFAAgCgGgAAMALIgMgfIgLAfIAXAAg");
	this.shape_10.setTransform(48.5,11);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgeA1QgDAAgDgDQgCgCAAgEIAAhXQAAgEACgCQADgDADABIASAAQAUAAAQAPQAPAPAAAVQAAAWgPAPQgPAPgVABgAgWAkIAKAAQAOgBAKgJQALgLAAgPQAAgOgLgKQgKgLgOAAIgKAAg");
	this.shape_11.setTransform(38.9,11);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAaAxIgagjIgYAjQgDADgEAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgEgCAAgEQAAgDABgDIAdgnIgdglQgBgDAAgEQAAgDAEgCQACgCADAAQAEABACADIAYAiIAagiQABgDAEgBQADAAADACQADACAAADQABAEgDADIgbAlIAbAnQADADgBADQAAAEgDACIgFABQgEAAgCgDg");
	this.shape_12.setTransform(25,11);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAaAvIgIgTIgjAAIgHATQgDAGgFAAIgDgBQgDgBgCgDQgBgDABgEIAhhXQACgFAFAAQAGAAACAFIAhBXQABAEgBADQgCADgDABIgDABQgFAAgCgGgAAMALIgMgfIgLAfIAXAAg");
	this.shape_13.setTransform(16,11);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgFAyQgCgCAAgEIAAhPIgYAAQgDAAgDgDQgCgCAAgDQAAgEACgCQACgDAEABIA/AAQADgBADADQACADAAADQAAADgCACQgDADgDAAIgYAAIAABPQAAAEgCACQgDADgDAAQgCAAgDgDg");
	this.shape_14.setTransform(6.8,11);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt_taxday, new cjs.Rectangle(0,0,168.5,21.5), null);


(lib.TD_chars = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43B02A").s().p("AgSBCIAAhpIAdAAIAABWIAcAAQAPAAAGgLQAHgLAAgZQAAgagHgLQgHgJgPAAIhAAAIAABwIgdAAIAAhwIgrAAIAAgTICRAAQAbAAAMAPQANAPAAAiQAAApgRAPQgMALgeAAg");
	this.shape.setTransform(9.9,6.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.TD_chars, new cjs.Rectangle(0,0,19.8,13.2), null);


(lib.logotext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#073F2C").s().p("AFLAzQgJgMAAgWQAAgTAJgMQAKgOATAAQASAAAKAOIAAAAIAAgzIArAAIAACBIgoAAIAAgRIgBAAQgHATgWAAQgTAAgLgPgAFvARQAAAUALAAQAKAAAAgTQABgSgLAAQgLAAAAARgADbA8QgKgIAAgNQAAghAuAAIARACQAAgNgWAAQgPAAgPAHIAAgYQATgFASAAQAYAAANAGQASAJAAAVIAAA2IgpAAIAAgMQgJAPgTAAQgOAAgKgGgAD5AiQgBAJALAAQAHAAADgFQAEgFgBgGIAAgDIgDAAQgVAAABAKgAA3AfIAAgfIgPAAIAAgZIAPAAIAAgVIArgNIAAAiIAUAAIAAAZIgUAAIAAAZQAAAMAKAAIAKgCIAAAaQgQAFgNAAQgiAAAAgjgAjKA1QgOgNAAgXQgBgsA4AAQAwAAgBAzIAAAFIg7AAQAAAOAXAAQATAAAKgGIAAAXQgPAGgZAAQgbAAgOgNgAisAAQgCAEAAAGIAWAAQAAgRgKAAQgHAAgDAHgAHIA0QgOgMgBgXQABgtA3AAQAvAAAAAzIAAAGIg8AAQABAOAXAAQASAAALgGIAAAXQgPAFgZAAQgbAAgOgNgAHmAAQgDADABAHIAWAAQABgRgMAAQgHAAgCAHgACCA/IAAhYIApAAIAAAUIAAAAQAKgWASAAIAHABIAAAjQgDgCgHAAQgJAAgHAHQgGAHAAAKIAAAggAgOA/IAAhYIAqAAIAABYgAhmA/IAAhYIAoAAIAAAUIABAAQAJgWASAAIAIABIAAAjQgEgCgGAAQgKAAgGAHQgHAHAAAKIAAAggAkOA/IAAgzQAAgMgIAAQgHAAgBAMIAAAzIgrAAIAAgzQAAgMgIAAQgHAAAAAMIAAAzIgrAAIAAhYIAoAAIAAAPIABAAQAHgRAYAAQAKAAAHAEQAIAEADAHQACgHAJgEQAIgEAJAAQAWAAAGAMQAEAHAAASIAAA1gAm6A/IgIgaIgoAAIgHAaIguAAIAqh3IBAAAIAqB3gAnjAJIAaAAIgMgnIgBAAgAgOgjIAAgeIAqAAIAAAeg");
	this.shape.setTransform(54.4,7.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.logotext, new cjs.Rectangle(0,0.5,112.4,13.4), null);


(lib.greenTDcopy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AijCSIAAkjIFGAAIAAEjgAgZBTIBMAAQAnAAAQgPQAWgTgBg1QAAgsgQgTQgQgUgjAAIi8AAIAAAZIA3AAIAACRIAmAAIAAiRIBTAAQAVAAAIAMQAJANAAAiQAAAggIAPQgIAOgUAAIgkAAIAAhvIgnAAg");
	this.shape.setTransform(16.4,14.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greenTDcopy, new cjs.Rectangle(0,0,32.7,29.3), null);


(lib.greenTD = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#50B948").s().p("AijCSIAAkjIFGAAIAAEjgAgZBTIBMAAQAnAAAQgPQAWgTgBg1QAAgsgQgTQgQgUgjAAIi8AAIAAAZIA3AAIAACRIAmAAIAAiRIBTAAQAVAAAIAMQAJANAAAiQAAAggIAPQgIAOgUAAIgkAAIAAhvIgnAAg");
	this.shape.setTransform(16.4,14.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greenTD, new cjs.Rectangle(0,0,32.7,29.3), null);


(lib.greenrectlight = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43B02A").s().p("EgMfAu4MAAAhdvIY/AAMAAABdvg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greenrectlight, new cjs.Rectangle(0,0,160,600), null);


(lib.ctaarrow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{"dark-green":6,white:26});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_18 = function() {
		this.stop();
	}
	this.frame_34 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(18).call(this.frame_18).wait(16).call(this.frame_34).wait(1));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003333").s().p("AgYAsQgCgCgBgEQABgDACgDIAfggIgfgfQgCgDgBgDQABgEACgCQADgDADAAQADAAADADIAlAmIABABIAAABIABAAIAAACIAAABIAAAAIAAACIAAABIgBABIAAABIgmAnQgCADgEAAQgDAAgDgDg");
	this.shape.setTransform(3.8,6.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAsQgCgCgBgEQABgDACgDIAfggIgfgfQgCgDgBgDQABgEACgCQADgDADAAQADAAADADIAlAmIABABIAAABIABAAIAAACIAAABIAAAAIAAACIAAABIgBABIAAABIgmAnQgCADgEAAQgDAAgDgDg");
	this.shape_1.setTransform(3.8,6.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},26).wait(9));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1,2,5.5,9.4);


(lib.ctabtntxt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{"dark-green":0,"white":18});

	// timeline functions:
	this.frame_13 = function() {
		this.stop();
	}
	this.frame_29 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(13).call(this.frame_13).wait(16).call(this.frame_29).wait(1));

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003333").s().p("AAeAwIAAgBIg6hRIAABPQAAABgBABQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAQgBgBAAAAQgBAAAAgBQAAgBAAgBIAAhYQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQABAAAAAAQABAAAAABQABAAAAABIA7BRIAAhPQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAIAABZQAAABAAABQAAABgBAAQAAAAgBABQgBAAAAAAIgDgBg");
	this.shape.setTransform(32.1,10.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#003333").s().p("AgYAxIAAAAIAAAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAhaQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAyAAQAAAAABAAQAAAAABABQAAAAAAABQAAABABAAQgBABAAABQAAABAAAAQgBABAAAAQgBAAAAAAIgvAAIAAAnIApAAQAAAAABAAQABAAAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAAgBABQAAAAgBAAQgBAAAAAAIgpAAIAAAnIAvAAQAAAAABAAQAAAAABABQAAAAAAABQAAABABAAQgBABAAABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_1.setTransform(24.2,10.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#003333").s().p("AgdAtIAAhaQAAAAABgBQAAgBAAAAQABgBAAAAQABAAABAAIABAAIAaAAQALAAAJAIQAIAJAAALQAAALgIAJQgJAHgLAAIgYAAIAAAmQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAgBgAgWAAIAYAAQAIAAAGgFQAHgHAAgIQAAgIgHgHQgGgGgIAAIgYAAg");
	this.shape_2.setTransform(17.2,10.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#003333").s().p("AggAjQgOgOAAgVQAAgUAOgOQAOgPASAAQAUAAANAPQAOAOAAAUQAAAVgOAOQgNAPgUAAQgSAAgOgPgAgcgdQgLAMgBARQABASALAMQAMANAQAAQAQAAAMgNQAMgMAAgSQAAgRgMgMQgMgNgQAAQgQAAgMANg");
	this.shape_3.setTransform(7.8,10.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAeAwIAAgBIg6hRIAABPQAAABgBABQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAQgBgBAAAAQgBAAAAgBQAAgBAAgBIAAhYQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQABAAAAAAQABAAAAABQABAAAAABIA7BRIAAhPQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAIAABZQAAABAAABQAAABgBAAQAAAAgBABQgBAAAAAAIgDgBg");
	this.shape_4.setTransform(32.1,10.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYAxIAAAAIAAAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAhaQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAyAAQAAAAABAAQAAAAABABQAAAAAAABQAAABABAAQgBABAAABQAAABAAAAQgBABAAAAQgBAAAAAAIgvAAIAAAnIApAAQAAAAABAAQABAAAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAAgBABQAAAAgBAAQgBAAAAAAIgpAAIAAAnIAvAAQAAAAABAAQAAAAABABQAAAAAAABQAAABABAAQgBABAAABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_5.setTransform(24.2,10.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgdAtIAAhaQAAAAABgBQAAgBAAAAQABgBAAAAQABAAABAAIABAAIAaAAQALAAAJAIQAIAJAAALQAAALgIAJQgJAHgLAAIgYAAIAAAmQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAgBgAgWAAIAYAAQAIAAAGgFQAHgHAAgIQAAgIgHgHQgGgGgIAAIgYAAg");
	this.shape_6.setTransform(17.2,10.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AggAjQgOgOAAgVQAAgUAOgOQAOgPASAAQAUAAANAPQAOAOAAAUQAAAVgOAOQgNAPgUAAQgSAAgOgPgAgcgdQgLAMgBARQABASALAMQAMANAQAAQAQAAAMgNQAMgMAAgSQAAgRgMgMQgMgNgQAAQgQAAgMANg");
	this.shape_7.setTransform(7.8,10.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4}]},18).wait(12));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,38.9,20.3);


(lib.ctabg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{"regular-green":4,"white":28});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_18 = function() {
		this.stop();
	}
	this.frame_36 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(18).call(this.frame_18).wait(18).call(this.frame_36).wait(1));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#43B02A").s().p("ApmCDQg2AAgngnQgmgmAAg2QAAg1AmgnQAngmA2AAITNAAQA2AAAmAmQAnAnAAA1QAAA2gnAmQgmAng2AAg");
	this.shape.setTransform(102.6,18.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ApmCDQg2AAgngnQgmgmAAg2QAAg1AmgnQAngmA2AAITNAAQA2AAAmAmQAnAnAAA1QAAA2gnAmQgmAng2AAg");
	this.shape_1.setTransform(102.6,18.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},28).wait(9));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(28,5,149.2,26.2);


(lib.whiteAmeritrade = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.instance = new lib.logotext();
	this.instance.parent = this;
	this.instance.setTransform(1.9,-0.5,1,1,0,0,0,56.3,7);
	this.instance.filters = [new cjs.ColorFilter(0, 0, 0, 1, 255, 255, 255, 0)];
	this.instance.cache(-2,-1,116,17);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-54.4,-6.8,108.8,13.2);


(lib.txt4a = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{showCountdownTxt:1});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_7 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(7).call(this.frame_7).wait(1));

	// Layer_2
	this.instance = new lib.txt_taxday();
	this.instance.parent = this;
	this.instance.setTransform(84.2,40.8,1,1,0,0,0,84.2,10.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},7).wait(1));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgKALQgFgEAAgHQAAgFAFgFQAFgFAFAAQAGAAAFAFQAFAFAAAFQAAAHgFAEQgEAFgHAAQgFAAgFgFg");
	this.shape.setTransform(272.8,20.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag0A3QgEgDAAgFQgBgEADgEQADgDAEgBQAFgBADAEQAUAQATgBQAQABALgIQAJgGAAgJQAAgEgCgDQgCgEgEgCQgKgGgSgEIgBAAQgQgDgLgFQgNgGgGgJQgFgJAAgJQAAgSARgNQAPgKAUgBQAUAAAaARQADADABAEQABAFgCADQgDAEgEABQgEABgEgDQgUgOgOAAQgNAAgKAIQgIAGAAAHQAAADACADIAGAFQAIAGARAEIAAAAQASADALAFQAPAHAGAKQAFAIAAAKQAAAUgSANQgQALgXABQgagBgagUg");
	this.shape_1.setTransform(263.7,14.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AghBKIAAAAQgFgBgEgDQgDgEAAgEIAAh7QAAgFADgDQAEgDAFAAIAAAAIBDAAQAFAAADADQAEADAAAFQAAAFgEAEQgDADgFAAIg4AAIAAAmIAwAAQAFAAADAEQAEADAAAEQAAAFgEADQgDADgFABIgwAAIAAAmIA4AAQAFAAADAEQAEADAAAFQAAAEgEAEQgDADgFABg");
	this.shape_2.setTransform(251.8,14.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgHBGQgDgDgBgFIAAhvIghAAQgFAAgDgEQgEgDAAgFQAAgFAEgDQADgDAFAAIBZAAQAFAAADADQADADABAFQgBAFgDADQgDAEgFAAIghAAIAABvQgBAFgDADQgDADgFABQgEgBgDgDg");
	this.shape_3.setTransform(239.2,14.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgqA4QgSgSAAgZIAAhKQAAgFAEgDQADgDAFAAQAFAAADADQAEADAAAFIAABKQAAAPALALQALALAOAAQAQAAAKgLQALgLAAgPIAAhKQAAgFAEgDQADgDAFAAQAFAAADADQAEADAAAFIAABKQAAAZgSASQgSARgZABQgYgBgSgRg");
	this.shape_4.setTransform(224.7,14.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAjBFIgBgCIhChcIAABWQAAAFgDADQgEAEgEAAQgFAAgDgEQgEgDAAgFIAAh5IAAAAQAAgGAFgEQAEgCAFAAQAEABADAEIBDBdIAAhWQAAgEADgEQADgDAFAAQAFAAADADQAEAEAAAEIAAB5QAAAFgEADQgDAEgFAAQgFAAgEgEg");
	this.shape_5.setTransform(209,14.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgHBGQgEgDAAgFIAAh7QAAgFAEgDQADgDAEAAQAEAAAEADQADADABAFIAAB7QgBAEgDAEQgEADgEABQgEgBgDgDg");
	this.shape_6.setTransform(199.4,14.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AArBGQgDgEAAgEIAAhXIgfAoQgDAGgGgBQgFABgEgGIgegoIAABXQAAAEgEAEQgDADgFABQgFgBgDgDQgDgEAAgEIAAh7QAAgEADgEQADgDAFAAIABAAQAGAAADAEIApA7IAqg7QADgEAGAAQAFAAAEADQADAEAAAEIAAB7QAAAEgDAEQgEADgFABQgFgBgDgDg");
	this.shape_7.setTransform(187.7,14.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgFBKQgWAAgPgQQgDgDAAgFQAAgFADgEQADgDAFAAQAGAAADADQAIAJAMAAQALAAAIgJQAIgIAAgMQAAgMgIgIQgIgHgLAAQgMAAgIAHQgDAEgFgBQgFABgEgEIgCgBIAAgBIgBgBIAAgCIAAAAIAAgDIAGg3QABgFAEgDIABgBIABAAQACgBADAAIA9AAQAFAAAEADQADAEAAAFQAAAEgDAEQgEADgFAAIgyAAIgDAVQAHgCAHAAQAVAAAPAQQAPAOAAAVQAAAWgPAPQgPAQgVAAg");
	this.shape_8.setTransform(168.2,14.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAFBGQgEgDAAgFIAAhnIgHAGQgDABgDAAQgHAAgDgGQgDgDACgGQABgEAEgDIAZgPIABAAIABgBIABAAIABAAIABAAIABAAIACAAIAAAAIACAAIAAABIACAAIABABIAAAAIABABIABABIABABIAAABIABABIAAABIAAABIABACIAAAAIAAB7QAAAEgEAEQgDADgFABQgFgBgDgDg");
	this.shape_9.setTransform(159.4,14.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAjBFIgBgCIhChcIAABWQAAAFgDADQgEAEgEAAQgFAAgDgEQgEgDAAgFIAAh5IAAAAQAAgGAFgEQAEgCAFAAQAEABADAEIBDBdIAAhWQAAgEADgEQADgDAFAAQAFAAADADQAEAEAAAEIAAB5QAAAFgEADQgDAEgFAAQgFAAgEgEg");
	this.shape_10.setTransform(143.5,14.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgIBGQgCgDAAgFIAAh7QAAgFACgDQAEgDAEAAQAEAAAEADQADADAAAFIAAB7QAAAEgDAEQgEADgEABQgEgBgEgDg");
	this.shape_11.setTransform(133.8,14.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAkBCIgKgbIgzAAIgKAbQgDAHgIABIgEgBQgEgCgCgFQgCgEABgFIAvh6QADgIAHABQAIgBADAIIAuB6QACAFgCAEQgCAFgEACIgEABQgIgBgDgHgAARAQIgRgtIgQAtIAhAAg");
	this.shape_12.setTransform(119.6,14.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AguBGQgDgEAAgEIAAh7QAAgFADgDQADgDAFAAIAmAAQARAAAOANQANANAAATQAAAUgRANQAFADADAFQAHAKAAANQgBAGACAGQAFACACAFQABAFgCAEQgCAEgEACIgFABQgFAAgEgDQgDgCgDgFQgFgKAAgPQAAgGgCgDQgCgDgEgEQgGgDgFgBIgZAAIAAAtQAAAEgDAEQgEADgFABQgFgBgDgDgAgagGIAaAAQAIAAAGgGQAGgHAAgIQAAgJgGgHQgGgGgIAAIgaAAg");
	this.shape_13.setTransform(107.3,14.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgIBGQgDgDAAgFIAAh7QAAgFADgDQAEgDAEAAQAFAAADADQAEADAAAFIAAB7QAAAEgEAEQgDADgFABQgEgBgEgDg");
	this.shape_14.setTransform(98.5,14.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAjBFIgBgCIhChcIAABWQAAAFgDADQgEAEgEAAQgFAAgDgEQgEgDAAgFIAAh5IAAAAQAAgGAFgEQAEgCAFAAQAEABADAEIBDBdIAAhWQAAgEADgEQADgDAFAAQAFAAADADQAEAEAAAEIAAB5QAAAFgEADQgDAEgFAAQgFAAgEgEg");
	this.shape_15.setTransform(82.3,14.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAkBCIgKgbIgzAAIgKAbQgDAHgIABIgEgBQgEgCgCgFQgCgEABgFIAvh6QADgIAHABQAIgBADAIIAuB6QACAFgCAEQgCAFgEACIgEABQgIgBgDgHgAARAQIgRgtIgQAtIAhAAg");
	this.shape_16.setTransform(69.1,14.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAjBFIgBgCIhChcIAABWQAAAFgDADQgEAEgEAAQgFAAgDgEQgEgDAAgFIAAh5IAAAAQAAgGAFgEQAEgCAFAAQAEABADAEIBDBdIAAhWQAAgEADgEQADgDAFAAQAFAAADADQAEAEAAAEIAAB5QAAAFgEADQgDAEgFAAQgFAAgEgEg");
	this.shape_17.setTransform(49.3,14.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AghBKIAAAAQgFgBgEgDQgDgEAAgEIAAh7QAAgFADgDQAEgDAFAAIAAAAIBDAAQAFAAADADQAEADAAAFQAAAFgEAEQgDADgFAAIg4AAIAAAmIAwAAQAFAAADAEQAEADAAAEQAAAFgEADQgDADgFABIgwAAIAAAmIA4AAQAFAAADAEQAEADAAAFQAAAEgEAEQgDADgFABg");
	this.shape_18.setTransform(36.8,14.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgrBGQgDgEAAgEIAAh7QAAgFADgDQADgDAGAAIAkAAQATAAANANQANANAAATQAAASgNAMQgNAOgTAAIgZAAIAAAtQAAAEgDAEQgEADgEABQgGgBgDgDgAgXgGIAZAAQAJAAAHgGQAGgHAAgIQAAgJgGgHQgHgGgJAAIgZAAg");
	this.shape_19.setTransform(25.8,14.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgyA1QgVgWAAgfQAAgeAVgWQAVgXAdAAQAeAAAUAXQAWAXAAAdQAAAfgWAWQgUAXgeAAQgdAAgVgXgAghgkQgOAPAAAVQAAAWAOAPQAOAPATgBQATABAPgPQAOgQAAgVQAAgVgOgPQgOgPgUAAQgTAAgOAPg");
	this.shape_20.setTransform(10.7,14.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,281,51.5);


(lib.txt4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{alt:1,"alt":16});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_16 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(16).call(this.frame_16).wait(1));

	// Layer 1
	this.t1 = new lib.txt4a();
	this.t1.name = "t1";
	this.t1.parent = this;
	this.t1.setTransform(140.5,23.7,1,1,0,0,0,140.5,23.7);

	this.t1_alt = new lib.txt4a2();
	this.t1_alt.name = "t1_alt";
	this.t1_alt.parent = this;
	this.t1_alt.setTransform(140.5,37.7,1,1,0,0,0,140.5,23.7);
	this.t1_alt.alpha = 0;
	this.t1_alt._off = true;

	this.timeline.addTween(cjs.Tween.get(this.t1).to({alpha:0},8).to({_off:true},1).wait(8));
	this.timeline.addTween(cjs.Tween.get(this.t1_alt).wait(9).to({_off:false},0).to({alpha:1},7).wait(1));

	// Layer 2
	this.t2 = new lib.txt4b();
	this.t2.name = "t2";
	this.t2.parent = this;
	this.t2.setTransform(95.2,133.7,1,1,0,0,0,92.2,20.7);

	this.t2_alt = new lib.txt4b();
	this.t2_alt.name = "t2_alt";
	this.t2_alt.parent = this;
	this.t2_alt.setTransform(95.2,125.7,1,1,0,0,0,92.2,20.7);
	this.t2_alt.alpha = 0;
	this.t2_alt._off = true;

	this.timeline.addTween(cjs.Tween.get(this.t2).to({alpha:0},8).to({_off:true},1).wait(8));
	this.timeline.addTween(cjs.Tween.get(this.t2_alt).wait(9).to({_off:false},0).to({alpha:1},7).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,281,149.6);


(lib.greenAmeritrade = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.instance = new lib.logotext();
	this.instance.parent = this;
	this.instance.setTransform(1.9,-0.5,1,1,0,0,0,56.3,7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-54.4,-6.8,108.8,13.2);


(lib.ctainside = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// arrow
	this.arrow = new lib.ctaarrow();
	this.arrow.name = "arrow";
	this.arrow.parent = this;
	this.arrow.setTransform(60.6,17,1,1,0,0,0,3.6,6);

	this.timeline.addTween(cjs.Tween.get(this.arrow).wait(1));

	// MASK (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AnBBuIAAjbIODAAIAADbg");
	mask.setTransform(45,18);

	// text down
	this.textDown = new lib.ctabtntxt();
	this.textDown.name = "textDown";
	this.textDown.parent = this;
	this.textDown.setTransform(40.6,18.5,1,1,0,0,0,26.9,9.5);

	var maskedShapeInstanceList = [this.textDown];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.textDown).wait(1));

	// text up
	this.textUp = new lib.ctabtntxt();
	this.textUp.name = "textUp";
	this.textUp.parent = this;
	this.textUp.setTransform(40.6,-1.5,1,1,0,0,0,26.9,9.5);

	var maskedShapeInstanceList = [this.textUp];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.textUp).wait(1));

	// BG
	this.bg = new lib.ctabg();
	this.bg.name = "bg";
	this.bg.parent = this;
	this.bg.setTransform(80.3,18.5,1,1,0,0,0,105.5,18.5);

	this.timeline.addTween(cjs.Tween.get(this.bg).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctainside, new cjs.Rectangle(2.8,5,149.1,26.2), null);


(lib.ctamain = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{over:6,out:25});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_17 = function() {
		this.stop();
	}
	this.frame_32 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(17).call(this.frame_17).wait(15).call(this.frame_32).wait(1));

	// Layer 1
	this.cta = new lib.ctainside();
	this.cta.name = "cta";
	this.cta.parent = this;
	this.cta.setTransform(105.5,18.5,1,1,0,0,0,105.5,18.5);

	this.timeline.addTween(cjs.Tween.get(this.cta).wait(6).to({x:98.7},4,cjs.Ease.get(1)).wait(1).to({regX:77.4,regY:18.1,x:70.7,y:18.1},0).wait(1).to({x:71},0).wait(1).to({x:71.5},0).wait(1).to({x:71.8},0).wait(1).to({regX:105.5,regY:18.5,x:100,y:18.5},0).wait(11).to({regX:77.4,regY:18.1,x:72.5,y:18.1},0).wait(1).to({x:73.3},0).wait(1).to({x:74.3},0).wait(1).to({x:75.3},0).wait(1).to({x:76.2},0).wait(1).to({x:76.9},0).wait(1).to({regX:105.5,regY:18.5,x:105.5,y:18.5},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-11,152,42.2);


// stage content:
(lib.tda_retirement_ira_tackletodayfy18_retargeting90d100_1000cash_300x250_urgency_sthtm = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var self = this;
		this.isLastDay = false;
		
		this.btnColor;
		this.downText = this.cta.cta.textDown;
		this.upText = this.cta.cta.textUp;
		this.textRestingYPos = 17;
		this.ctaTextOffset = 30;
		
		
		
		self.upText.y = this.textRestingYPos + this.ctaTextOffset;
		self.downText.y = this.textRestingYPos;
		
		this.setBtnColor = function(p_color) {
			switch (p_color) {
				case "white":
					self.cta.cta.arrow.gotoAndPlay("dark-green");
					self.cta.cta.textDown.gotoAndPlay("dark-green");
					self.cta.cta.bg.gotoAndPlay("white");
					self.btnColor = "white";
					break;
				case "regular-green":
					self.cta.cta.arrow.gotoAndPlay("white");
					self.cta.cta.textDown.gotoAndPlay("white");
					self.cta.cta.bg.gotoAndPlay("regular-green");
					self.btnColor = "regular-green";
					break;	
			}
		}
		this.setRolloverBtnColor = function() {
			if (self.btnColor == "regular-green") {
				setTimeout(function() {
					self.cta.cta.arrow.gotoAndPlay("dark-green");
				}, 150);
			}	
		}
		this.setRolloutBtnColor = function() {
			if (self.btnColor == "regular-green") {
				setTimeout(function() {
					self.cta.cta.arrow.gotoAndPlay("white");
				}, 150);
			}
		}
		
		// Set initial button color
		setTimeout(function() {
			self.setBtnColor("white");
		}, 50);
		
		this.revealEndFrame = function(){
			//console.log('REVEAL ENDFRAME this.isLastDay', this.isLastDay);
			//if(!this.isLastDay){
			//
			window.revealEndFrame();
			//} else {
			//	//console.log('GO TO ALT LAST FRAME');
			//}
			
			
		}
		
		this.mouseOver = function() {
			var landingY = self.textRestingYPos;
			self.cta.gotoAndPlay("over"); 
			self.cta.cta.gotoAndPlay("over");
			self.setRolloverBtnColor();
			self.downText.y = landingY;
			self.upText.y = landingY-self.ctaTextOffset;
			createjs.Tween.get(self.downText, {override:true}).to({y:landingY+self.ctaTextOffset}, 200, createjs.Ease.quintIn);
			createjs.Tween.get(self.upText, {override:true}).wait(200).to({y:landingY}, 300, createjs.Ease.quintOut);
		}
		this.mouseOut = function () {
			var landingY = self.textRestingYPos;
			self.cta.gotoAndPlay("out");
			self.cta.cta.gotoAndPlay("out");
			self.setRolloutBtnColor();
			self.downText.y = landingY+self.ctaTextOffset;
			self.upText.y = landingY;
			createjs.Tween.get(self.downText, {override:true}).wait(200).to({y:landingY}, 300, createjs.Ease.quintOut);
			createjs.Tween.get(self.upText, {override:true}).to({y:landingY-self.ctaTextOffset}, 200, createjs.Ease.quintIn);
		}
		
		this.lastDay = function(){
			console.log("LAST DAY!!!");
			this.isLastDay = true;
			this.endframe.gotoAndPlay(2);
		}
		
		// Clicktag =======================
		/// moved over to html file
		
		//this.clicktag.addEventListener('click', handleClick);
		//this.clicktag.addEventListener('mouseover', handleMouseOver);
		//this.clicktag.addEventListener('mouseout', handleMouseOut);
		
		//this.infoBtn.addEventListener('click', handleInfoClick);
		//this.balloon.addEventListener('click', handleBalloonClick);
		
		
		/*
		function handleClick() {
			console.log('HANDLE CTA');
		    window.ctaClick();
		}
		function handleBalloonClick(){
			window.ctaClick2();
		}
		
		function handleInfoClick(){
			self.balloon.x = 13;
			createjs.Tween.get(self.balloon, {override:true}).to({alpha:1}, 200, createjs.Ease.quintIn);
			setTimeout(function(){
				//createjs.Tween.get(self.balloon, {override:true}).to({alpha:.5}, 200, createjs.Ease.quintOut);
				self.balloon.x = -300;
				self.balloon.alpha = 0;
			}, 3000);	
		}
		*/
	}
	this.frame_76 = function() {
		this.setBtnColor("regular-green");
	}
	this.frame_149 = function() {
		this.setBtnColor("white");
	}
	this.frame_160 = function() {
		this.revealEndFrame();
		this.endframe.t1.gotoAndPlay('showCountdownTxt');
	}
	this.frame_172 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(76).call(this.frame_76).wait(73).call(this.frame_149).wait(11).call(this.frame_160).wait(12).call(this.frame_172).wait(1));

	// stroke
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,0,3).p("A3bzhMAu3AAAMAAAAnDMgu3AAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(173));

	// cta
	this.cta = new lib.ctamain();
	this.cta.name = "cta";
	this.cta.parent = this;
	this.cta.setTransform(433.2,214.7,1.268,1.268,0,0,0,105.5,18.7);

	this.timeline.addTween(cjs.Tween.get(this.cta).wait(8).to({x:435.2,y:223.7},0).wait(1).to({regX:73.9,regY:18.1,x:364,y:223},0).wait(1).to({x:341.9},0).wait(1).to({x:327.3},0).wait(1).to({x:317.9},0).wait(1).to({x:311.9},0).wait(1).to({x:307.9},0).wait(1).to({x:305.3},0).wait(1).to({x:303.7},0).wait(1).to({x:302.8},0).wait(1).to({x:302.3},0).wait(1).to({regX:105.5,regY:18.7,x:342.3,y:223.7},0).wait(154));

	// MASK (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AqHCWIAAkrIUOAAIAAErg");
	mask.setTransform(103.3,27.6);

	// ameritrade-ko
	this.instance = new lib.whiteAmeritrade("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(87.1,23.1,0.774,0.774,0,0,0,0.1,0.1);

	this.instance_1 = new lib.greenAmeritrade("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(87.1,23.1,0.774,0.774,0,0,0,0.1,0.1);
	this.instance_1.alpha = 0;

	var maskedShapeInstanceList = [this.instance,this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance}]},76).to({state:[{t:this.instance_1}]},4).to({state:[]},1).to({state:[{t:this.instance}]},77).to({state:[{t:this.instance}]},5).to({state:[{t:this.instance}]},1).to({state:[{t:this.instance}]},1).to({state:[{t:this.instance}]},1).to({state:[{t:this.instance}]},1).to({state:[{t:this.instance}]},1).to({state:[{t:this.instance}]},1).to({state:[{t:this.instance}]},1).to({state:[{t:this.instance}]},1).wait(2));
	this.timeline.addTween(cjs.Tween.get(this.instance).wait(76).to({startPosition:0},0).to({_off:true,alpha:0},4).wait(78).to({_off:false,x:-3.1,alpha:1},0).to({x:89.6},5,cjs.Ease.get(1)).wait(1).to({regX:0,regY:-0.2,x:89.4,y:22.9},0).wait(1).to({x:89.2},0).wait(1).to({x:88.9},0).wait(1).to({x:88.4},0).wait(1).to({x:87.8},0).wait(1).to({x:87.4},0).wait(1).to({x:87.1},0).wait(1).to({regX:0.1,regY:0.1,y:23.1},0).wait(2));

	// ameritrade-gr
	this.instance_2 = new lib.greenAmeritrade("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(-3.1,24.1,0.774,0.774,0,0,0,0.1,0.1);
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(86).to({_off:false},0).to({x:89.6},5,cjs.Ease.get(1)).wait(1).to({regX:0,regY:-0.2,x:89.4,y:23.9},0).wait(1).to({x:89.2},0).wait(1).to({x:88.9},0).wait(1).to({x:88.4},0).wait(1).to({x:87.8},0).wait(1).to({x:87.4},0).wait(1).to({x:87.1},0).wait(1).to({regX:0.1,regY:0.1,y:24.1},0).wait(50).to({startPosition:0},0).to({alpha:0},4).to({_off:true},8).wait(12));

	// MASK (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	var mask_1_graphics_73 = new cjs.Graphics().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	var mask_1_graphics_74 = new cjs.Graphics().p("A3eTQMAAUgm3MAupAAYMgAUAm3g");
	var mask_1_graphics_75 = new cjs.Graphics().p("A3mSWMABUgmQMAt5ABlMgBUAmQg");
	var mask_1_graphics_76 = new cjs.Graphics().p("A3vQtMADEglFMAsbADsMgDEAlFg");
	var mask_1_graphics_77 = new cjs.Graphics().p("A3xOLMAFmgjDMAp9AGuMgFmAjDg");
	var mask_1_graphics_78 = new cjs.Graphics().p("A3aKvIIw/5MAmFAKcIowf5g");
	var mask_1_graphics_79 = new cjs.Graphics().p("A2NGfIMB7PMAgaAOSIsBbPg");
	var mask_1_graphics_80 = new cjs.Graphics().p("AztB/IOf1GIY8RJIufVGg");
	var mask_1_graphics_81 = new cjs.Graphics().p("Av6hvIPKuQIQrRvIvKOQg");
	var mask_1_graphics_82 = new cjs.Graphics().p("ArljyINuoOIJdPzItuIOg");
	var mask_1_graphics_83 = new cjs.Graphics().p("An1kLILFkFIEmMcIrFEFg");
	var mask_1_graphics_84 = new cjs.Graphics().p("AlLjpIIbhzIB8JGIobBzg");
	var mask_1_graphics_85 = new cjs.Graphics().p("Ajgi5IGUgsIAtGfImUAsg");
	var mask_1_graphics_86 = new cjs.Graphics().p("AikiQIE7gPIAOEwIk7APg");
	var mask_1_graphics_87 = new cjs.Graphics().p("AiGh4IEKgDIADD0IkKADg");
	var mask_1_graphics_88 = new cjs.Graphics().p("Ah9BxIAAjhID7AAIAADhg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:149.9,y:124.9}).wait(73).to({graphics:mask_1_graphics_73,x:149.9,y:125}).wait(1).to({graphics:mask_1_graphics_74,x:149.3,y:124.5}).wait(1).to({graphics:mask_1_graphics_75,x:147.2,y:122.8}).wait(1).to({graphics:mask_1_graphics_76,x:143.4,y:119.7}).wait(1).to({graphics:mask_1_graphics_77,x:137.4,y:114.8}).wait(1).to({graphics:mask_1_graphics_78,x:128.8,y:107.9}).wait(1).to({graphics:mask_1_graphics_79,x:117.1,y:98.4}).wait(1).to({graphics:mask_1_graphics_80,x:102.3,y:86.4}).wait(1).to({graphics:mask_1_graphics_81,x:85.4,y:72.7}).wait(1).to({graphics:mask_1_graphics_82,x:68.3,y:58.9}).wait(1).to({graphics:mask_1_graphics_83,x:53.6,y:47}).wait(1).to({graphics:mask_1_graphics_84,x:42.2,y:37.8}).wait(1).to({graphics:mask_1_graphics_85,x:34.3,y:31.4}).wait(1).to({graphics:mask_1_graphics_86,x:29.2,y:27.3}).wait(1).to({graphics:mask_1_graphics_87,x:26.5,y:25.1}).wait(1).to({graphics:mask_1_graphics_88,x:25.6,y:24.4}).wait(1).to({graphics:null,x:0,y:0}).wait(84));

	// TD-ko
	this.instance_3 = new lib.greenTDcopy();
	this.instance_3.parent = this;
	this.instance_3.setTransform(70.5,24.4,0.771,0.771,0,0,0,74.5,14.7);

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(76).to({alpha:0},4,cjs.Ease.get(1)).to({_off:true},9).wait(84));

	// Layer 1
	this.instance_4 = new lib.TD_chars();
	this.instance_4.parent = this;
	this.instance_4.setTransform(25.6,24,1,1,0,0,0,9.9,6.5);
	this.instance_4._off = true;
	this.instance_4.filters = [new cjs.ColorFilter(0, 0, 0, 1, 255, 255, 255, 0)];
	this.instance_4.cache(-2,-2,24,17);

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(76).to({_off:false},0).to({_off:true},13).wait(84));

	// text2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgaAcQgMgMAAgQQAAgPAMgLQALgMAPAAQAQAAALAMQAMALAAAPQAAAQgMAMQgLALgQAAQgPAAgLgLg");
	this.shape_1.setTransform(240.1,168.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgTCsQgJgJAAgLIAAiNIhpiRQgIgJACgMQACgLAJgHQAKgHAMABQALACAHAKIBYB6IBZh6QAHgKAMgCQALgBAKAHQAJAHACALQACAMgHAJIhqCRIAACNQAAAMgJAIQgIAIgMAAQgLAAgIgIg");
	this.shape_2.setTransform(219.8,153.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ABZCjIgahDIh9AAIgZBDQgIATgTAAIgKgCQgMgEgEgLQgFgLAEgLIBzkyQAHgTATABQAUgBAIATIByEyQAEALgEALQgFALgMAEIgKACQgTAAgHgTgAAqAnIgqhvIgpBvIBTAAg");
	this.shape_3.setTransform(188.7,153.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhqC2QgMAAgIgIQgJgJAAgLIAAkzQAAgLAJgJQAIgIAMAAIA9AAQBKAAA2A1QA1A2AABKQAABLg1A2Qg1A1hLAAgAhNB8IAgAAQAzAAAkglQAkgkAAgzQAAgygkglQgkgkgzAAIggAAg");
	this.shape_4.setTransform(154.7,153.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ah9CEQg0g2AAhOQAAhMA0g2QAzg4BLAAQBLAAAxA4QA1A3AABLQAABNg1A3QgyA3hKAAQhKAAg0g3gAhShaQgkAlAAA1QAAA2AkAlQAjAlAwAAQAvAAAjglQAkgmAAg1QAAg0gkgmQgiglgwAAQgxAAgiAlg");
	this.shape_5.setTransform(115.1,152.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgUCuQgHgJgBgLIAAkVIhSAAQgMAAgIgJQgJgIAAgNQAAgLAJgJQAIgIAMAAIDdAAQAMAAAIAIQAJAJgBALQABANgJAIQgIAJgMAAIhSAAIAAEVQAAALgJAJQgIAIgMAAQgLAAgJgIg");
	this.shape_6.setTransform(78.4,153.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhSC2IgBgBIgBABQgMAAgIgJQgJgIAAgLIAAkyQAAgNAJgHQAIgJAMAAIABAAIABAAICnAAQAMAAAIAJQAJAHAAANQAAAMgJAIQgJAJgLAAIiMAAIAABfIB4AAQAMAAAIAJQAJAIAAALQAAAMgJAIQgIAIgMAAIh4AAIAABhICMAAQALgBAJAJQAJAIAAANQAAALgJAIQgJAJgLAAg");
	this.shape_7.setTransform(229.3,95.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhSC2IgBAAIgBAAQgMAAgIgJQgJgIAAgLIAAkyQAAgMAJgIQAIgJAMAAQAMAAAJAJQAIAIAAAMIAAEVICMAAQALgBAJAJQAJAIAAANQAAALgJAIQgJAJgLAAg");
	this.shape_8.setTransform(202,95.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABXCqIhwiTIg2A3IAABKQAAAMgIAIQgJAJgLAAQgNAAgIgJQgIgIAAgMIAAkvQAAgMAIgIQAJgJAMAAQALAAAJAJQAIAIAAAMIAACVICoipQAIgIAMAAQAMAAAIAIQAIAIAAAMQAAAMgIAJIhyByIBzCWQAIAJgBAMQgCAMgJAHQgHAHgLAAQgNAAgIgLg");
	this.shape_9.setTransform(169.2,95.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhoCEQg4g2AAhOQAAhMA4g3QA4g3BOAAQBEAAA0AoQAJAIACAMQABAMgHAKQgIAKgMABQgNACgJgHQgjgdgwAAQg1AAgoAlQgmAnAAAzQAAA1AmAmQAoAlA1AAQAwAAAjgdQAJgGANABQAMACAIAJQAHAKgBAMQgCAMgJAIQg0AohEAAQhOAAg4g3g");
	this.shape_10.setTransform(132,95.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("ABZCjIgahDIh9AAIgZBDQgIATgTAAIgKgCQgMgEgEgLQgFgLAEgLIBzkyQAHgTATABQAUgBAIATIByEyQAEALgEALQgFALgMAEIgKACQgTAAgHgTgAAqAnIgqhvIgpBvIBTAAg");
	this.shape_11.setTransform(98.1,95.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgTCtQgJgHAAgMIAAkVIhSAAQgMAAgIgJQgJgIABgMQgBgNAJgHQAIgJAMAAIDeAAQALAAAJAJQAHAHABANQgBAMgHAIQgKAJgKAAIhUAAIAAEVQABAMgJAHQgIAJgMAAQgLAAgIgJg");
	this.shape_12.setTransform(65.4,95.8);

	var maskedShapeInstanceList = [this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8,this.shape_9,this.shape_10,this.shape_11,this.shape_12];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).to({state:[]},89).wait(84));

	// green bg
	this.instance_5 = new lib.greenrectlight();
	this.instance_5.parent = this;
	this.instance_5.setTransform(150,125,1.875,0.417,0,0,0,80,300);

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({_off:true},89).wait(84));

	// MASK (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_73 = new cjs.Graphics().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	var mask_2_graphics_145 = new cjs.Graphics().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	var mask_2_graphics_146 = new cjs.Graphics().p("A3eTQMAAUgm3MAupAAYMgAUAm3g");
	var mask_2_graphics_147 = new cjs.Graphics().p("A3mSWMABUgmQMAt5ABlMgBUAmQg");
	var mask_2_graphics_148 = new cjs.Graphics().p("A3vQtMADEglFMAsbADsMgDEAlFg");
	var mask_2_graphics_149 = new cjs.Graphics().p("A3xOLMAFmgjDMAp9AGuMgFmAjDg");
	var mask_2_graphics_150 = new cjs.Graphics().p("A3aKvIIw/5MAmFAKcIowf5g");
	var mask_2_graphics_151 = new cjs.Graphics().p("A2NGfIMB7PMAgaAOSIsBbPg");
	var mask_2_graphics_152 = new cjs.Graphics().p("AztB/IOf1GIY8RJIufVGg");
	var mask_2_graphics_153 = new cjs.Graphics().p("Av6hvIPKuQIQrRvIvKOQg");
	var mask_2_graphics_154 = new cjs.Graphics().p("ArljyINuoOIJdPzItuIOg");
	var mask_2_graphics_155 = new cjs.Graphics().p("An1kLILFkFIEmMcIrFEFg");
	var mask_2_graphics_156 = new cjs.Graphics().p("AlLjpIIbhzIB8JGIobBzg");
	var mask_2_graphics_157 = new cjs.Graphics().p("Ajgi5IGUgsIAtGfImUAsg");
	var mask_2_graphics_158 = new cjs.Graphics().p("AikiQIE7gPIAOEwIk7APg");
	var mask_2_graphics_159 = new cjs.Graphics().p("AiGh4IEKgDIADD0IkKADg");
	var mask_2_graphics_160 = new cjs.Graphics().p("Ah9BxIAAjhID7AAIAADhg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:null,x:0,y:0}).wait(73).to({graphics:mask_2_graphics_73,x:149.9,y:124.9}).wait(72).to({graphics:mask_2_graphics_145,x:149.9,y:125}).wait(1).to({graphics:mask_2_graphics_146,x:149.3,y:124.5}).wait(1).to({graphics:mask_2_graphics_147,x:147.2,y:122.8}).wait(1).to({graphics:mask_2_graphics_148,x:143.4,y:119.7}).wait(1).to({graphics:mask_2_graphics_149,x:137.4,y:114.8}).wait(1).to({graphics:mask_2_graphics_150,x:128.8,y:107.9}).wait(1).to({graphics:mask_2_graphics_151,x:117.1,y:98.4}).wait(1).to({graphics:mask_2_graphics_152,x:102.3,y:86.4}).wait(1).to({graphics:mask_2_graphics_153,x:85.4,y:72.7}).wait(1).to({graphics:mask_2_graphics_154,x:68.3,y:58.9}).wait(1).to({graphics:mask_2_graphics_155,x:53.6,y:47}).wait(1).to({graphics:mask_2_graphics_156,x:42.2,y:37.8}).wait(1).to({graphics:mask_2_graphics_157,x:34.3,y:31.4}).wait(1).to({graphics:mask_2_graphics_158,x:29.2,y:27.3}).wait(1).to({graphics:mask_2_graphics_159,x:26.5,y:25.1}).wait(1).to({graphics:mask_2_graphics_160,x:25.6,y:24.4}).wait(1).to({graphics:null,x:0,y:0}).wait(12));

	// TD-gr
	this.instance_6 = new lib.greenTD();
	this.instance_6.parent = this;
	this.instance_6.setTransform(70.5,24.4,0.771,0.771,0,0,0,74.5,14.7);
	this.instance_6._off = true;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(88).to({_off:false},0).wait(60).to({alpha:0},4,cjs.Ease.get(1)).to({_off:true},9).wait(12));

	// Layer 2
	this.instance_7 = new lib.TD_chars();
	this.instance_7.parent = this;
	this.instance_7.setTransform(25.6,24,1,1,0,0,0,9.9,6.5);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(148).to({_off:false},0).to({alpha:1},4).to({_off:true},9).wait(12));

	// text3
	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#3FB41C").s().p("AgOAPQgGgGAAgJQAAgIAGgGQAGgGAIAAQAIAAAHAGQAGAGAAAIQAAAJgGAGQgGAGgJAAQgIAAgGgGg");
	this.shape_13.setTransform(257.8,165.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#3FB41C").s().p("AgKBcQgFgEAAgHIAAhLIg4hOQgEgFABgGQABgGAFgEQAFgEAGABQAHABADAFIAvBCIAwhCQAEgFAGgBQAGgBAFAEQAFAEABAGQABAGgDAFIg6BOIAABLQAAAHgEAEQgFAFgGAAQgFAAgFgFg");
	this.shape_14.setTransform(247.5,157.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#3FB41C").s().p("AAwBYIgOgkIhDAAIgNAkQgEAKgLAAIgFgBQgGgCgDgGQgDgGACgGIA+ikQAEgKAKAAQALAAAEAKIA+CkQACAGgDAGQgCAGgGACIgGABQgKAAgEgKgAAXAVIgXg7IgWA7IAtAAg");
	this.shape_15.setTransform(231.3,157.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#3FB41C").s().p("Ag5BiQgGAAgFgEQgEgFAAgHIAAikQAAgGAEgEQAFgFAGAAIAhAAQAoAAAcAdQAdAcAAAoQAAAogdAdQgcAdgoAAgAgpBDIARAAQAbgBATgTQAUgTAAgcQAAgbgUgUQgTgTgbAAIgRAAg");
	this.shape_16.setTransform(213.7,157.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#3FB41C").s().p("AgKBeQgFgFAAgHIAAiUIgsAAQgGAAgFgFQgEgEAAgHQAAgGAEgEQAFgFAGAAIB3AAQAGAAAFAFQAEAEAAAGQAAAHgEAEQgFAFgGAAIgtAAIAACUQAAAHgEAFQgFAEgGAAQgGAAgEgEg");
	this.shape_17.setTransform(189.3,157.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#3FB41C").s().p("AAvBaIgvhAIguBAQgFAHgIAAQgEAAgEgDQgGgEgBgGQgBgHAEgFIA1hIIg1hIQgEgFABgGQABgGAGgEQAFgEAGABQAGABAEAFIAuBBIAvhBQAEgFAGgBQAHgBAFAEQAFAEABAGQABAGgEAFIg1BIIA1BIQAEAFgBAHQgBAGgFAEQgFADgEAAQgIAAgFgHg");
	this.shape_18.setTransform(171.6,157.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#3FB41C").s().p("AgsBiIAAgBIgBABQgGAAgFgEQgEgFAAgHIAAikQAAgGAEgEQAFgFAGAAIABAAIAAAAIBaAAQAGAAAFAFQAEAEAAAGQAAAHgEAEQgFAFgGAAIhLAAIAAA0IBAAAQAGgBAFAFQAFAFAAAFQAAAHgFAEQgEAEgHABIhAAAIAAAzIBLAAQAGAAAFAEQAEAFAAAGQAAAHgEAFQgFAEgGAAg");
	this.shape_19.setTransform(156,157.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#3FB41C").s().p("AAwBcIgCgCIhYh7IAABzQAAAGgFAFQgEAEgGAAQgHAAgEgEQgFgFAAgGIAAiiIAAAAQAAgIAGgFQAGgEAGABQAGABAEAFIBZB8IAAhyQAAgGAEgEQAFgFAGAAQAGAAAFAFQAEAEAAAGIAACiQAAAGgEAFQgFAEgGAAQgHAAgEgFg");
	this.shape_20.setTransform(137.4,157.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#3FB41C").s().p("AgsBiIAAgBIgBABQgGAAgFgEQgEgFAAgHIAAikQAAgGAEgEQAFgFAGAAIABAAIAAAAIBaAAQAGAAAFAFQAEAEAAAGQAAAHgEAEQgFAFgGAAIhLAAIAAA0IBAAAQAGgBAFAFQAFAFAAAFQAAAHgFAEQgEAEgHABIhAAAIAAAzIBLAAQAGAAAFAEQAEAFAAAGQAAAHgEAFQgFAEgGAAg");
	this.shape_21.setTransform(114.5,157.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#3FB41C").s().p("AApBeQgFgFAAgHIAAhCIhIAAIAABCQABAHgFAFQgFAEgGAAQgGAAgFgEQgFgFABgHIAAikQgBgGAFgEQAFgFAGAAQAGAAAFAFQAFAEgBAGIAABEIBIAAIAAhEQAAgGAFgEQAEgFAHAAQAGAAAFAFQAEAEABAGIAACkQgBAHgEAFQgFAEgGAAQgHAAgEgEg");
	this.shape_22.setTransform(97,157.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#3FB41C").s().p("AgKBeQgFgFAAgHIAAiUIgsAAQgGAAgFgFQgEgEAAgHQAAgGAEgEQAFgFAGAAIB3AAQAGAAAFAFQAEAEAAAGQAAAHgEAEQgFAFgGAAIgtAAIAACUQAAAHgEAFQgFAEgGAAQgGAAgEgEg");
	this.shape_23.setTransform(79.9,157.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#3FB41C").s().p("Ag5BiQgGAAgFgEQgEgFAAgHIAAikQAAgGAEgEQAFgFAGAAIAhAAQAoAAAcAdQAdAcAAAoQAAAogdAdQgcAdgoAAgAgpBDIARAAQAbgBATgTQAUgTAAgcQAAgbgUgUQgTgTgbAAIgRAAg");
	this.shape_24.setTransform(56.1,157.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#3FB41C").s().p("AAwBcIgCgCIhYh7IAABzQAAAGgFAFQgEAEgGAAQgHAAgEgEQgFgFAAgGIAAiiIAAAAQAAgIAGgFQAGgEAGABQAGABAEAFIBZB8IAAhyQAAgGAEgEQAFgFAGAAQAGAAAFAFQAEAEAAAGIAACiQAAAGgEAFQgFAEgGAAQgHAAgEgFg");
	this.shape_25.setTransform(36.3,157.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#3FB41C").s().p("AAwBYIgOgkIhDAAIgNAkQgEAKgLAAIgFgBQgGgCgDgGQgDgGACgGIA+ikQAEgKAKAAQALAAAEAKIA+CkQACAGgDAGQgCAGgGACIgGABQgKAAgEgKgAAXAVIgXg7IgWA7IAtAAg");
	this.shape_26.setTransform(19.1,157.8);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#3FB41C").s().p("AgOAPQgGgGAAgJQAAgHAGgGQAGgHAIAAQAIAAAHAHQAGAGAAAHQAAAJgGAGQgGAGgJAAQgIAAgGgGg");
	this.shape_27.setTransform(196.5,134);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#3FB41C").s().p("AgKBcQgFgEAAgHIAAhLIg4hOQgEgFABgGQABgGAFgEQAFgEAGABQAHABADAFIAvBCIAwhCQAEgFAGgBQAGgBAFAEQAFAEABAGQABAGgDAFIg6BOIAABLQAAAHgEAEQgFAFgGAAQgFAAgFgFg");
	this.shape_28.setTransform(186.2,126.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#3FB41C").s().p("AAwBYIgOgkIhDAAIgNAkQgEAKgLAAIgFgBQgGgCgDgGQgDgGACgGIA+ikQAEgKAKAAQALAAAEAKIA+CkQACAGgDAGQgCAGgGACIgGABQgKAAgEgKgAAXAVIgXg8IgWA8IAtAAg");
	this.shape_29.setTransform(170,126.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#3FB41C").s().p("Ag5BiQgGAAgFgFQgEgEAAgGIAAilQAAgGAEgFQAFgEAGAAIAhAAQAoAAAcAdQAdAdAAAnQAAApgdAcQgcAdgoAAgAgpBDIARAAQAbAAATgUQAUgTAAgcQAAgbgUgUQgTgTgbAAIgRAAg");
	this.shape_30.setTransform(152.4,126.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#3FB41C").s().p("AgKBdQgFgEAAgGIAAiVIgsAAQgGAAgFgEQgEgFAAgHQAAgGAEgFQAFgEAGAAIB3AAQAGAAAFAEQAEAFAAAGQAAAGgEAGQgFAEgGAAIgtAAIAACVQAAAGgEAEQgFAFgGAAQgGAAgEgFg");
	this.shape_31.setTransform(128,126.1);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#3FB41C").s().p("AAvBaIgvhAIguBAQgFAHgIAAQgEAAgEgDQgGgEgBgGQgBgHAEgFIA1hIIg1hIQgEgFABgGQABgGAGgEQAFgEAGABQAGABAEAFIAuBBIAvhBQAEgFAGgBQAHgBAFAEQAFAEABAGQABAGgEAFIg1BIIA1BIQAEAFgBAHQgBAGgFAEQgFADgEAAQgIAAgFgHg");
	this.shape_32.setTransform(110.3,126.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#3FB41C").s().p("AgsBiIAAgBIgBABQgGAAgFgFQgEgEAAgGIAAilQAAgGAEgFQAFgEAGAAIABAAIAAAAIBaAAQAGAAAFAEQAEAFAAAGQAAAHgEAFQgFAEgGAAIhLAAIAAA0IBAAAQAGAAAFAEQAFAEAAAGQAAAGgFAFQgEAFgHgBIhAAAIAAA0IBLAAQAGAAAFAFQAEAEAAAHQAAAGgEAEQgFAFgGAAg");
	this.shape_33.setTransform(94.7,126.1);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#3FB41C").s().p("AAwBcIgCgCIhYh7IAABzQAAAGgFAFQgEAEgGAAQgHAAgEgEQgFgFAAgGIAAiiIAAAAQAAgIAGgFQAGgEAGABQAGABAEAFIBZB8IAAhyQAAgGAEgEQAFgFAGAAQAGAAAFAFQAEAEAAAGIAACiQAAAGgEAFQgFAEgGAAQgHAAgEgFg");
	this.shape_34.setTransform(76.1,126.2);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#3FB41C").s().p("AgsBiIAAgBIgBABQgGAAgFgFQgEgEAAgGIAAilQAAgGAEgFQAFgEAGAAIABAAIAAAAIBaAAQAGAAAFAEQAEAFAAAGQAAAHgEAFQgFAEgGAAIhLAAIAAA0IBAAAQAGAAAFAEQAFAEAAAGQAAAGgFAFQgEAFgHgBIhAAAIAAA0IBLAAQAGAAAFAFQAEAEAAAHQAAAGgEAEQgFAFgGAAg");
	this.shape_35.setTransform(53.2,126.1);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#3FB41C").s().p("AApBdQgFgEAAgGIAAhEIhIAAIAABEQAAAGgEAEQgFAFgGAAQgHAAgEgFQgFgEABgGIAAilQgBgGAFgFQAEgEAHAAQAGAAAFAEQAEAFAAAGIAABEIBIAAIAAhEQAAgGAFgFQAEgEAHAAQAGAAAFAEQAFAFAAAGIAAClQAAAGgFAEQgFAFgGAAQgHAAgEgFg");
	this.shape_36.setTransform(35.7,126.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#3FB41C").s().p("AgKBdQgFgEAAgGIAAiVIgsAAQgGAAgFgEQgEgFAAgHQAAgGAEgFQAFgEAGAAIB3AAQAGAAAFAEQAEAFAAAGQAAAGgEAGQgFAEgGAAIgtAAIAACVQAAAGgEAEQgFAFgGAAQgGAAgEgFg");
	this.shape_37.setTransform(18.6,126.1);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#3FB41C").s().p("AgsBiIAAAAIgBAAQgGAAgFgFQgEgEAAgHIAAijQAAgHAEgEQAFgFAGAAIABAAIAAAAIBaAAQAGAAAFAFQAEAEAAAHQAAAGgEAEQgFAFgGAAIhLAAIAAAzIBAAAQAGABAFAEQAFAFAAAFQAAAGgFAFQgEAFgHAAIhAAAIAAAzIBLAAQAGAAAFAFQAEAEAAAGQAAAHgEAEQgFAFgGAAg");
	this.shape_38.setTransform(277.2,94.5);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#3FB41C").s().p("AgsBiIAAAAIgBAAQgGAAgFgFQgEgEAAgHIAAijQAAgHAEgEQAFgFAGAAQAHAAAEAFQAFAEAAAHIAACUIBLAAQAGAAAFAFQAEAEAAAGQAAAHgEAEQgFAFgGAAg");
	this.shape_39.setTransform(263.1,94.5);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#3FB41C").s().p("AAuBcIg7hQIgdAeIAAAoQAAAGgEAFQgFAEgHAAQgGAAgFgEQgEgFAAgGIAAijQAAgGAEgFQAFgEAGAAQAHAAAFAEQAEAFAAAGIAABQIBZhbQAGgEAFAAQAHAAAFAEQAEAFAAAGQAAAHgEAEIg+A+IA+BQQAEAFgBAGQAAAHgFAEQgEADgGAAQgHAAgFgFg");
	this.shape_40.setTransform(246.1,94.5);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#3FB41C").s().p("Ag3BHQgfgdAAgqQAAgpAfgdQAegeApAAQAlAAAcAWQAFAEAAAHQABAGgEAFQgEAGgGAAQgHABgFgDQgTgQgaAAQgcAAgWAUQgUAVAAAbQAAAdAUAUQAWAUAcAAQAaAAATgQQAFgDAHABQAGABAEAEQAEAGgBAGQAAAHgFAEQgcAWglAAQgpAAgegeg");
	this.shape_41.setTransform(226.7,94.2);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#3FB41C").s().p("AAwBYIgOgkIhDAAIgNAkQgEAKgLAAIgFgBQgGgCgDgGQgDgGACgGIA+ikQAEgKAKAAQALAAAEAKIA+CkQACAGgDAGQgCAGgGACIgGABQgKAAgEgKgAAXAVIgXg7IgWA7IAtAAg");
	this.shape_42.setTransform(209.1,94.5);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#3FB41C").s().p("AgKBdQgFgEAAgHIAAiUIgsAAQgGAAgFgFQgEgEAAgGQAAgHAEgEQAFgFAGAAIB3AAQAGAAAFAFQAEAEAAAHQAAAGgEAEQgFAFgGAAIgtAAIAACUQAAAHgEAEQgFAFgGAAQgGAAgEgFg");
	this.shape_43.setTransform(192.1,94.5);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#3FB41C").s().p("AAwBcIgCgCIhYh7IAABzQAAAGgFAFQgEAEgGAAQgHAAgEgEQgFgFAAgGIAAiiIAAAAQAAgIAGgFQAGgEAGABQAGABAEAFIBZB8IAAhyQAAgGAEgEQAFgFAGAAQAGAAAFAFQAEAEAAAGIAACiQAAAGgEAFQgFAEgGAAQgHAAgEgFg");
	this.shape_44.setTransform(167,94.5);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#3FB41C").s().p("AAwBYIgOgkIhDAAIgNAkQgEAKgLAAIgFgBQgGgCgDgGQgDgGACgGIA+ikQAEgKAKAAQALAAAEAKIA+CkQACAGgDAGQgCAGgGACIgGABQgKAAgEgKgAAXAVIgXg7IgWA7IAtAAg");
	this.shape_45.setTransform(149.8,94.5);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#3FB41C").s().p("Ag3BHQgfgdAAgqQAAgpAfgdQAegeApAAQAlAAAcAWQAFAEAAAHQABAGgEAFQgEAGgGAAQgHABgFgDQgTgQgaAAQgcAAgWAUQgUAVAAAbQAAAdAUAUQAWAUAcAAQAaAAATgQQAFgDAHABQAGABAEAEQAEAGgBAGQAAAHgFAEQgcAWglAAQgpAAgegeg");
	this.shape_46.setTransform(131.2,94.2);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#3FB41C").s().p("Ag4BKQgYgXAAgiIAAhiQAAgHAFgEQAEgFAGAAQAGAAAFAFQAFAEAAAHIAABiQAAAVAOAPQAPAOAUAAQAUAAAPgOQAPgPAAgVIAAhiQgBgHAFgEQAFgFAHAAQAGAAAFAFQAEAEAAAHIAABiQAAAigYAXQgYAYghAAQghAAgXgYg");
	this.shape_47.setTransform(103.8,94.5);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#3FB41C").s().p("AhDBHQgcgdAAgqQAAgoAcgeQAcgeAoAAQAoAAAaAeQAdAeAAAoQAAApgdAeQgbAegnAAQgoAAgcgegAgsgwQgTAUAAAcQAAAdATAUQATAUAaAAQAZAAATgUQATgUAAgdQAAgcgTgUQgTgUgZAAQgaAAgTAUg");
	this.shape_48.setTransform(82.2,94.2);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#3FB41C").s().p("AgKBcQgFgEAAgHIAAhLIg4hOQgEgFABgGQABgGAFgEQAFgEAGABQAHABADAFIAvBCIAwhCQAEgFAGgBQAGgBAFAEQAFAEABAGQABAGgDAFIg6BOIAABLQAAAHgEAEQgFAFgGAAQgFAAgFgFg");
	this.shape_49.setTransform(64.7,94.6);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#3FB41C").s().p("AhDBHQgcgdAAgqQAAgoAcgeQAcgeAoAAQAoAAAaAeQAdAeAAAoQAAApgdAeQgbAegnAAQgoAAgcgegAgsgwQgTAUAAAcQAAAdATAUQATAUAaAAQAZAAATgUQATgUAAgdQAAgcgTgUQgTgUgZAAQgaAAgTAUg");
	this.shape_50.setTransform(38.2,94.2);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#3FB41C").s().p("AhGBJQgFgEAAgGQgBgGAEgFQAEgFAGAAQAGgBAEAEQAbAXAagBQAUAAAPgLQAMgIAAgMQAAgEgDgFQgDgEgFgEQgNgIgZgFIAAAAQgWgEgOgHQgSgIgIgNQgHgKAAgNQAAgYAXgRQAUgPAbAAQAbABAiAWQAFADABAGQABAGgDAEQgDAGgGABQgGABgFgDQgbgSgSAAQgRAAgNAKQgLAHAAAKQAAAFACADQACADAGAEQALAIAXAFIAAAAQAYAEAPAHQATAJAJAOQAHAKAAANQAAAbgZAQQgVAQgeABQgkAAgjgcg");
	this.shape_51.setTransform(19.3,94.2);

	var maskedShapeInstanceList = [this.shape_13,this.shape_14,this.shape_15,this.shape_16,this.shape_17,this.shape_18,this.shape_19,this.shape_20,this.shape_21,this.shape_22,this.shape_23,this.shape_24,this.shape_25,this.shape_26,this.shape_27,this.shape_28,this.shape_29,this.shape_30,this.shape_31,this.shape_32,this.shape_33,this.shape_34,this.shape_35,this.shape_36,this.shape_37,this.shape_38,this.shape_39,this.shape_40,this.shape_41,this.shape_42,this.shape_43,this.shape_44,this.shape_45,this.shape_46,this.shape_47,this.shape_48,this.shape_49,this.shape_50,this.shape_51];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13}]},73).to({state:[]},88).wait(12));

	// white bg
	this.instance_8 = new lib.corkgrey();
	this.instance_8.parent = this;
	this.instance_8._off = true;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(73).to({_off:false},0).to({_off:true},88).wait(12));

	// MASK (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	var mask_3_graphics_145 = new cjs.Graphics().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(mask_3).to({graphics:null,x:0,y:0}).wait(145).to({graphics:mask_3_graphics_145,x:149.9,y:124.9}).wait(28));

	// TD-ko
	this.instance_9 = new lib.greenTDcopy();
	this.instance_9.parent = this;
	this.instance_9.setTransform(70.5,24.4,0.771,0.771,0,0,0,74.5,14.7);
	this.instance_9._off = true;

	var maskedShapeInstanceList = [this.instance_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(161).to({_off:false},0).wait(12));

	// text4
	this.endframe = new lib.txt4();
	this.endframe.name = "endframe";
	this.endframe.parent = this;
	this.endframe.setTransform(9,47);
	this.endframe.alpha = 0;

	var maskedShapeInstanceList = [this.endframe];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.endframe).wait(146).to({regX:138.6,regY:75.7,x:147.6,y:122.7,alpha:0.004},0).wait(1).to({alpha:0.017},0).wait(1).to({alpha:0.04},0).wait(1).to({alpha:0.076},0).wait(1).to({alpha:0.127},0).wait(1).to({alpha:0.195},0).wait(1).to({alpha:0.283},0).wait(1).to({alpha:0.391},0).wait(1).to({alpha:0.511},0).wait(1).to({alpha:0.633},0).wait(1).to({alpha:0.743},0).wait(1).to({alpha:0.833},0).wait(1).to({alpha:0.9},0).wait(1).to({alpha:0.948},0).wait(1).to({alpha:0.978},0).wait(1).to({alpha:0.995},0).wait(1).to({regX:0,regY:0,x:9,y:47,alpha:1},0).wait(11));

	// green bg
	this.instance_10 = new lib.greenrectlight();
	this.instance_10.parent = this;
	this.instance_10.setTransform(150,125,1.875,0.417,0,0,0,80,300);
	this.instance_10._off = true;

	var maskedShapeInstanceList = [this.instance_10];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(145).to({_off:false},0).wait(28));

	// white bg
	this.instance_11 = new lib.corkgrey();
	this.instance_11.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(173));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,124,792.1,252);
// library properties:
lib.properties = {
	id: 'CAFC813688A947EE953882ED377C3153',
	width: 300,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/corkgrey.jpg?1519750197689", id:"corkgrey"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['CAFC813688A947EE953882ED377C3153'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;