(function(z){
'use strict';var q7=function(a){z.L.call(this);this.aa(a)},K2a=function(a,b){this.user=a;this.quotes=b},L2a=function(a,b){b=b.g();if(b===Number||b.$isProtoEnum)return a=Number(a),Number.isNaN(a)?void 0:a;if(b===Boolean)return!!a;if(b===String)return String(a)},r7=function(a){return a.xB.best||null},s7=function(a,b){b=b.filter(function(a){return"anon"!=a.mb()});b=z.jb(b,function(a){return a.mb()},a);return z.ob(b).map(function(a){return new K2a(a[0].$b(),a)},a)},M2a=function(a,b,c,d){return(0,z.Od)(a.Rt[b.name]||
[],function(a){return a.Bd()==c&&a.ye()==d})},t7=function(){this.jH=1},u7=function(a){z.jj.call(this);this.aa(a)},N2a=function(a,b){return z.K(a,"slots",b)},O2a=function(a,b){return z.K(a,"requestContext",b)},v7=function(a){z.L.call(this);this.aa(a)},w7=function(a){return z.J(a,"inResponseToMediaResource")},x7=function(a){return z.J(a,"mediumQuote")},P2a=function(a,b){a.fQ=b;return a},y7=function(a,b){return r7(a)?z.UD(r7(a)).filter(function(a){return this.O4(a)==b},a):[]},Q2a=function(a,b,c){c=c.gy;
b=b.getAttribute("name").split(" ");var d=z.Cb(b);a=(a.Rt[c.name]||[]).filter(function(a){return d[a.Zi()]});return a.length?z.Ata(a):null},R2a=function(a,b,c,d){b=M2a(a,b,c,d);return s7(a,b)},S2a=function(a,b){var c=0;(a.Rt[b]||[]).forEach(function(a){"anon"==a.mb()&&(c+=a.Ke())});return c},T2a=function(a){var b=z.MN(a.dk.st,a.dk.Jr(),a.im.st,a.im.Jr()).Ha().trim();0<a.dk.Jr()&&(b="…"+b);var c=z.FE(a.xc,a.im.st);a.im.Jr()<c.Ha().length&&(b+="…");return b},U2a=function(a){var b=z.yC(a.Uxa),c=a.dk.st,
d=c?b.indexOf(c):-1,e=(c=a.im.st)?b.indexOf(c):-1;if(-1==d||-1==e)return"";for(c=[];d<=e;d++)c.push(z.FE(a.xc,b[d]));b=z.Ra(c);a=z.xv(c.indexOf(c[0]),a.dk.Jr(),c.indexOf(b),a.im.Jr(),!1);return z.Dia(new z.Pu(z.ho,z.MBa),c,a,!0)},V2a=function(a,b,c){var d=a.ma.la(z.tBa,{postId:b},{filter:c});return z.rE(a,d,function(){return this.Ib.Im(d)})},W2a=function(a,b){z.xu(a,7);var c=new z.ou("",1,a.Ha());b.forEach(function(a){z.vu(c,z.fu(a.startOffset,a.endOffset,[a.quoteId],[a.userId]))},a);b=z.qia(c);for(var d=
z.ria(c,b),e=0;e<b.length;e++){var g=d[e];if(g.length){for(var k={},l=[],p=0;p<g.length;p++){var r=g[p];k[z.J(r,"creatorIds")]=!0;l.push(r.getName())}g=b[e];p=e<b.length-1?b[e+1]:a.Ha().length;z.vu(a,z.fu(g,p,l,Object.keys(k)))}}},X2a=function(a,b,c){b="";a.DFa?a=z.n("Top highlight"):(c=""+z.A(z.JQ(z.D({V5:!0,Nka:!c.useragent.isMobile},a),c)),1==a.Fi&&a.isActive&&(a=z.n("highlighted"),c+=" "+a),a=(0,z.y)(c));b+=a;return(0,z.y)(b)},z7=function(a,b){this.li=a;this.Bra=b;this.Ne=(this.Mk=b=z.tC(a.node,
b))&&b.getAttribute("name");this.UP=b?z.Mx(a,b):-1},A7=function(a){var b=a.length;a=a.match(Y2a);if(!a)return b;for(var c=0;c<a.length;c++)b+=23-a[c].length;return b},Z2a=function(a,b,c){return(0,z.y)(z.uQ(z.D({user:c.currentUser,type:"quoteResponses"},a),c))},$2a=function(a,b,c){b="\x3cdiv class\x3d'u-marginLeft10'\x3e\x3cdiv class\x3d\"buttonSet u-inlineBlock\"\x3e"+z.A(z.Wl({action:"quote",source:"quote_popover",icon:(0,z.N)(""+z.A(z.yca())),l:(0,z.N)("button--highlightMenu u-sm-height42 u-sm-lineHeight44 u-accentColor--highlightStrong js-quoteAttributions-pileOn"),
ac:!0,Nj:!0,RR:"quote",wa:!0,isActive:a.isActive},c))+(c.supportsEdit?z.A(z.Wl({action:"quote-respond",source:"quote_popover",icon:(0,z.N)(""+z.A(z.Dca())),l:"button--highlightMenu u-sm-height42 u-sm-lineHeight44",ac:!0,wa:!0},c)):"")+(a.zV?z.A(z.Wl({action:"twitter",source:"quote_popover",icon:(0,z.N)(""+z.A(z.Jl(null))),l:"button--highlightMenu u-sm-height42 u-sm-lineHeight44",ac:!0,wa:!0},c)):"")+'\x3cdiv class\x3d"buttonSet-separator"\x3e\x3c/div\x3e\x3c/div\x3e';b+='\x3cdiv class\x3d"'+z.F(z.E("js-quoteAttributions-info u-inlineBlock u-verticalAlignTop u-noWrapWithEllipsis u-maxWidth414 u-paddingTop11 u-paddingRight18 u-paddingBottom0 u-paddingLeft10 u-xs-paddingTop13 u-xs-paddingLeft4 u-xs-maxWidth160"))+
'"\x3e'+X2a(a,0,c)+"\x3c/div\x3e\x3c/div\x3e";return(0,z.y)(b)},B7=function(a){z.jo.call(this);var b=z.tp();this.dk=b&&new z7(z.Vp(b,!0),a);this.im=b&&new z7(z.Vp(b,!1),a)},C7=function(a){z.L.call(this);this.aa(a)},D7=function(a,b){var c=new z.Vj(z.eo(b)),c=new z.Je(c.la(z.uAa)),d=new z.Je("https://www.facebook.com/v2.7/dialog/share");z.Qe(d,z.kf({app_id:b.facebook.key,href:a.toString(),display:"popup",redirect_uri:c.toString()}));return d},a3a=function(a,b,c){function d(a){return a.replace(/“/g,
"‘").replace(/”/g,"’").replace(/„/g,"‚").replace(/'/g,"’")}b.content=d(b.content);b.name&&(b.name=d(b.name));var e=String(a(b,null,c)),g=A7(e)-280;0<g&&(b.content=z.Pi(b.content,b.content.length-g),e=String(a(b,null,c)));return e},b3a=function(a,b){b=new z.Vj(b.authBaseUrl);return new z.Je(b.vl(a))},c3a=function(){var a=z.n("Highlights");return(0,z.y)(""+a)},d3a=function(a,b,c){b=a.post.virtuals.responsesCreatedCount>=c.j.m7&&(a.post.creator.userId==c.currentUser.userId||(null==a.post.homeCollection?
null:null==a.post.homeCollection.virtuals?null:null==a.post.homeCollection.virtuals.permissions?null:a.post.homeCollection.virtuals.permissions.canManageAll));var d=z.D({g8:b},a),d=d||{},d=d.g8;a=""+('\x3cdiv class\x3d"container u-maxWidth740"\x3e\x3cdiv class\x3d"responsesStreamWrapper u-maxWidth640 u-hide js-responsesStreamWrapper"\x3e'+(0,z.y)('\x3cdiv class\x3d"container responsesStream-title u-paddingTop15"\x3e\x3cdiv class\x3d"row"\x3e'+z.A(z.$P({title:(0,z.N)(""+z.A(z.Tm())),hD:!0,Lg:(0,z.N)(""+
(c.supportsEdit&&d?z.GNa(null,c):""))},c))+"\x3c/div\x3e\x3c/div\x3e")+z.ENa(z.D({qe:b},a),c)+(b?z.FNa(a,c):"")+z.DNa(c)+"\x3c/div\x3e\x3c/div\x3e");return(0,z.y)(a)},E7=function(a,b,c){z.Q.call(this);this.ue=a.get("quotes-data");var d=this.ue.kp;d.subscribe("add",this.Xda,this);d.subscribe("remove",this.Xda,this);this.fb=b;this.Ud=b.em;this.nm=c;this.Baa=[];this.Ja=a.get("app");this.Ga=a.get("popover");this.ma=a.get("route-builder");this.LZ=a.get("global-event-bus");this.gya=a.get("progressive-media-loader")},
f3a=function(a,b,c,d){var e=e3a(a,b);if(e){var g=a.fb.isPublished(),k=z.Zta(a.fb);e.zV=g&&k;if(c=z.PH(z.sD(z.rD(z.tD(z.$F(z.uD(a.Ga).jb($2a,e),z.GG),c),{G5:!0,py:!0,Ba:!0}),"popover--quoteAttributions"),d).ua())c.Um("deactivate",function(){this.wp===b&&F7(this,null)},a),c.$n().ba("quote",a.xsa.bind(a,c)).ba("quote-respond",a.ysa.bind(a,c)).ba("twitter",a.zsa.bind(a))}},e3a=function(a,b){if("anon"==b.mb())return{isActive:!1,DFa:!0};var c=G7(a,b),d=b.Bd();b=b.ye();a=R2a(a.ue,c,d,b);if(!a||!a.length)return null;
a=(0,z.Eb)(a,function(a){return a.user});c=(0,z.Od)(a,function(a){return a.userId!=z.Xr().userId});return{isActive:(0,z.td)(a,function(a){return a.userId==z.Xr().userId}),social:c,Fi:a.length}},g3a=function(a,b){a=a.Ud.querySelectorAll('.markup--quote[name~\x3d"'+b.Zi()+'"]');return z.$a(a)},G7=function(a,b){b=b.gc()[0].name;return(b=z.Rt(a.Ud,b))?a.fb.Yi(b):null},h3a=function(a,b){var c=z.up(b);return(c=z.CF(a.nm,c))?Q2a(a.ue,b,c):null},F7=function(a,b){a.wp!==b&&(a.wp&&i3a(a,a.wp,!1),b&&i3a(a,b,
!0),a.wp=b)},i3a=function(a,b,c){g3a(a,b).map(function(a){z.Xd(a,"is-targeted",c)})},H7=function(a,b){(b=j3a(a,b))&&z.AF(a.rk(),b)},j3a=function(a,b){var c=b.gc(),d=z.Rt(a.Ud,c[0].getName());a=z.Rt(a.Ud,z.Ra(c).getName());return z.MN(d,b.Bd(),a,b.ye())},I7=function(a,b,c,d){a={postId:a.fb.Oa(),quoteId:b,source:d};z.Jy(c?z.Hta:z.WCa,a)},k3a=function(a,b){z.xC(a,z.wC,z.Yb(b,z.Vb(!0)),void 0)},l3a=function(a,b,c){z.qa(a)||(a=a.toString());var d=window,e={scrollbars:!0,oIa:!0,toolbar:!1,location:!0,width:670,
height:690};z.Ab(e,c||{});e.left||e.top||(e.width=(0,window.parseInt)(e.width,10),e.height=(0,window.parseInt)(e.height,10),e.left=Math.max(d.screenX+Math.round(d.outerWidth/2-e.width/2),0),e.top=Math.max(d.screenY+Math.round(d.outerHeight/2-e.height/2),0));var g={scrollbars:"scrollbars",oIa:"resizable",toolbar:"toolbar",location:"location",width:"width",height:"height",left:"left",top:"top"};c=z.Ega(e,function(a,b,c){g[c]&&("boolean"==typeof b&&(b=b?"yes":"no"),a.push(g[c]+"\x3d"+b));return a},[]).join();
return d.open(a,b,c)},m3a=function(a){var b=z.mx(z.Eva,{xGa:!0});b&&(b=b.split(/\s+/),b=b.filter(function(a){return!z.Fa(a)}),b.length&&z.Md(a,b))},n3a=function(a){return(0,z.y)(z.A(z.Sm(String(a.content)))+" — "+z.A(z.Ft(a))+" "+z.A(a.url))},o3a=function(a,b,c){return(0,z.Sj)("https://"+z.yi(c.textshotHost)+"/image")},p3a=function(a,b,c){return(0,z.Sj)("https://twitter.com/"+z.yi(c.currentUser.twitterScreenName)+"/status/"+z.yi(a.id))},q3a=function(){var a=z.y,b;b=z.n("Failed to load image");b=(0,z.y)(""+
b);return a('\x3cspan class\x3d"tweetEditor-imageStatusIcon"\x3e\x26times;\x3c/span\x3e'+z.A(b))},r3a=function(a,b,c){b=z.y;a='\x3cdiv class\x3d"tweetEditor u-sizeFullWidth"\x3e\x3cdiv class\x3d"js-tweetEditor-error tweetEditor-error u-paddingBottom10 u-textAlignCenter u-textColorRed"\x3e\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-avatar"\x3e'+z.A(z.hn({user:a.user,wf:!0},c))+'\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-tweetContainer"\x3e\x3cdiv class\x3d"tweetEditor-textContainer"\x3e\x3cdiv class\x3d"js-tweetEditor-text textInput textInput--chromeless u-textAlignLeft"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-textshot"\x3e\x3cdiv class\x3d"js-tweetEditor-imageStatus tweetEditor-imageStatus"\x3e';
var d;d=z.n("Loading image attachment…");d=(0,z.y)(""+d);a=a+z.A(d)+"\x3c/div\x3e";d={};d=(0,z.y)(z.dl(z.D({name:"addCircled",size:"21px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"21" height\x3d"21" viewBox\x3d"0 0 21 21" \x3e\x3cpath d\x3d"M2.286 12.691a8.358 8.358 0 0 0 2.192 3.831A8.298 8.298 0 0 0 8.3 18.715c.73.19 1.462.288 2.192.29a8.363 8.363 0 0 0 2.2-.29 8.286 8.286 0 0 0 3.822-2.193 8.264 8.264 0 0 0 2.201-3.82c.19-.732.285-1.462.285-2.193a8.248 8.248 0 0 0-.285-2.2 8.265 8.265 0 0 0-2.2-3.823 8.258 8.258 0 0 0-3.822-2.2A8.66 8.66 0 0 0 10.5 2a8.188 8.188 0 0 0-2.192.286 8.33 8.33 0 0 0-3.831 2.2 8.298 8.298 0 0 0-2.193 3.822A8.66 8.66 0 0 0 2 10.5c0 .731.095 1.461.286 2.191zm1.557-.413a6.74 6.74 0 0 1-.239-1.773c0-.592.08-1.184.24-1.773a6.77 6.77 0 0 1 1.786-3.09 6.73 6.73 0 0 1 3.085-1.79c.59-.16 1.181-.24 1.777-.24.596 0 1.188.08 1.777.24a6.736 6.736 0 0 1 3.094 1.786 6.801 6.801 0 0 1 1.787 3.094c.16.59.239 1.178.239 1.768 0 .59-.08 1.182-.24 1.778a6.75 6.75 0 0 1-1.786 3.093 6.801 6.801 0 0 1-3.094 1.787 6.707 6.707 0 0 1-3.545 0A6.74 6.74 0 0 1 5.63 15.37a6.746 6.746 0 0 1-1.787-3.093zm2.937-2.055c0-.134.049-.25.148-.345a.494.494 0 0 1 .359-.143H9.23a.478.478 0 0 0 .35-.148.475.475 0 0 0 .147-.35V7.303c0-.141.048-.262.144-.363a.458.458 0 0 1 .345-.152h.562c.134 0 .25.05.35.152a.502.502 0 0 1 .147.363v1.934c0 .135.048.252.143.35a.46.46 0 0 0 .345.148h1.945c.14 0 .26.048.358.143.099.096.148.21.148.345v.562a.476.476 0 0 1-.148.35.486.486 0 0 1-.358.147h-1.945a.472.472 0 0 0-.345.143.47.47 0 0 0-.143.345v1.944c0 .14-.05.262-.148.36a.478.478 0 0 1-.35.147h-.56a.498.498 0 0 1-.489-.507V11.77a.461.461 0 0 0-.148-.345.487.487 0 0 0-.35-.143H7.287a.488.488 0 0 1-.36-.147.476.476 0 0 1-.147-.35v-.562z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
d)));d=(0,z.N)(""+z.A(d));var e;e=z.n("Include quote image");e=(0,z.y)(""+e);a=a+z.A(z.Wl({icon:d,isPrimary:!0,wa:!0,l:"js-tweetEditor-addTextshot u-hide",action:"add-textshot",text:(0,z.N)(""+z.A(e))},c))+'\x3cdiv class\x3d"js-tweetEditor-imageContainer tweetEditor-imageContainer"\x3e';d=(0,z.N)("\x26times;");e=z.n("Remove quote image from tweet");e=(0,z.y)(""+e);return b(a+z.A(z.Ul({s:d,Ic:!0,l:"js-tweetEditor-removeTextshot tweetEditor-removeTextshot",title:(0,z.N)(""+z.A(e)),action:"remove-textshot"},
c))+'\x3cimg class\x3d"js-tweetEditor-image tweetEditor-image" data-action\x3d"toggle-expand-image"\x3e\x3c/img\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e'+(c.variants.textshots_userid?'\x3cdiv class\x3d"u-textColorRed"\x3eTweet to test account @fuzzyoctopusfee\x3c/div\x3e':""))},s3a=function(){var a=z.n("An error occurred, and the tweet wasn’t posted to Twitter.");return(0,z.y)(""+a)},t3a=function(a,b,c){var d="";b=z.n("Tweet posted.");a=a.yJa;var e;e=z.n("View the tweet");e=(0,z.y)(""+
e);d+=b+" "+z.A(z.O({vb:!0,href:a,s:(0,z.N)(""+e)},c));return(0,z.y)(d)},u3a=function(a,b,c){a=z.n("Tweet must be {$twitterMaxTweetLength} characters or less.",{twitterMaxTweetLength:z.A(c.j.zJa)});return(0,z.y)(""+a)},v3a=function(a){if(!a)return"";var b=[],c=z.wb(["grafId","noteId","command","startIndex","endIndex"]),d;for(d in a)b[c[d]]=a[d];return b.join("-")},J7=function(a){z.ky.call(this);this.xc=a.get("dom-model-converter");this.Uca={};this.Mba={};this.L0={};this.ra=a;this.jl=a.get("request");
this.ma=a.get("route-builder");this.Aa=a.get("model-store");this.nb="";this.uda=z.Tn;this.yaa=!1;this.Eh=null},K7=function(a,b){var c=a.Uca[b];c||(c=a.Uca[b]=new z.PD,a.za("new_note_list",c,a));return c},w3a=function(a,b){if(!b)return!1;var c=b.Ha();if(a.content==c.substring(a.startIndex,a.endIndex))return!0;var d=new RegExp(z.Ja(a.content),"gi"),c=(b=d.exec(c))&&d.exec(c);return b&&!c?(c=a.endIndex-a.startIndex,a.startIndex=b.index,a.endIndex=b.index+c,a.content=b[0],!0):!1},L7=function(a,b,c){var d=
b.Oa(),e=b.sg(),g=K7(a,b.oe()),k=g?g.indexOf(b):-1,l=b.$x();b.Ds(c);"HIDDEN"==c?a.Aa.remove(b):b=z.pD(a.Aa,b);var p=g?g.indexOf(b):-1;return{Al:a.jl.put(a.ma.la(z.DAa,{postId:d,noteId:e}),{state:c}),dL:function(){b.Ds(l);-1==p&&(-1==k?g.add(b):z.RD(g,b,k))}}},M7=function(a,b,c,d,e,g){var k=z.J(a.Kp(c,e),"replies"),l=z.Sa(k,function(a){return a.Yx()==b}),p=k[l];"HIDDEN"==g&&z.Xa(k,l);c=a.ma.la(z.GAa,{postId:d,noteId:c,replyId:b});a=a.jl.put(c,{state:g});var r=z.Sa(k,function(a){return a.Yx()==b});
return{Al:a,dL:function(){-1==r&&z.eb(k,l,0,p)}}},x3a=function(a,b,c){this.range=a;this.anchor=b;this.UB=b.getAttribute("name");this.highlight=c},N7=function(a,b,c){z.Q.call(this);this.Vya=b;this.Rxa=c;this.Pa=a.get("screen");this.kb=a.get("screen-request")},O7=function(a,b,c,d){z.Q.call(this);this.Pa=a.get("screen");this.gp=c;this.gh=d;this.nP=!1;this.Sv=this.ah=null;this.Wa(b)},P7=function(){},y3a=function(a){this.TP=a},Q7=function(a,b){return b?z.Rt(a.TP,b):null},z3a=function(a,b,c){k3a(a.TP,function(a){var e=
a.getAttribute("name");e&&b.call(c,a,e)})},A3a=function(a,b){return z.Kh(a.TP,b)?a.TP:null},R7=function(a,b,c,d,e){z.tW.call(this,a,b);this.$a(new z.MV(c));this.$a(new z.HW(!1));this.$a(new z.KW(a));this.$a(new z.uW);this.$a(new z.NW(a,!1,!1));this.$a(new z.PW(d,!0));this.fl=!0;this.mm=d;this.jl=a.get("request");this.Da=a.get("dialog");this.q0=e;this.ua()},B3a=function(){var a=z.n("Saving failed. You may be having connectivity issues or notes might be disabled on this post. Please try again.");return(0,z.y)(""+
a)},C3a=function(){var a=z.n("Yikes! Something happened and we couldn’t dismiss this note.");return(0,z.y)(""+a)},D3a=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this note.");return(0,z.y)(""+a)},E3a=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this reply.");return(0,z.y)(""+a)},F3a=function(){var a=z.n("The note has been dismissed.");return(0,z.y)(""+a)},G3a=function(){var a=z.n("The note has been deleted.");return(0,z.y)(""+a)},H3a=function(){var a=
z.n("The reply has been deleted.");return(0,z.y)(""+a)},I3a=function(){var a=z.n("Write a note…");return(0,z.y)(""+a)},J3a=function(){var a=z.n("Cancel");return(0,z.y)(""+a)},S7=function(a,b,c,d,e){R7.call(this,a,b,e||"Leave a note",400,d||null);this.nb=c;this.ma=a.get("route-builder");this.uf=a.get("notes-data")},T7=function(a,b,c,d,e,g){R7.call(this,a,b,"Leave a reply…",200,d);this.ma=a.get("route-builder");this.uf=a.get("notes-data");this.nb=c;this.Tda=g||null;this.Ne=e},L3a=function(a,b,c){var d=
'\x3cdiv class\x3d"quoteResponses js-quoteResponses"\x3e',e=a.quotes.length,g=a.responses.length||a.F8;b=a.notes.length||a.xV;if(e||g||b){if(e){var e='\x3cdiv class\x3d"quoteResponses-section"\x3e'+z.A(z.IA({title:(0,z.N)(z.A(c3a())+" ("+z.A(a.quotes.length)+")"),Qf:!0},c)),k;k={Wja:a.quotes,UJa:!0};var l='\x3cdiv class\x3d"js-quotesList"\x3e';if(!k.UJa)var p=z.n("Learn more"),l=l+z.A(z.IA({title:(0,z.N)(""+z.A(c3a())),Qf:!0,Lg:(0,z.N)(""+z.A(z.HA({href:(0,z.M)(""+z.G((0,z.Sj)("https://medium.com/the-story/introducing-highlights-a4df69e8ed43"))),
moreText:(0,z.N)(""+p),wb:!0},c)))},c));for(var p="list u-marginTop5 u-marginBottom15"+(k.Wja.length?"":" u-hide"),p=(0,z.N)(p),l=l+('\x3cul class\x3d"'+z.F(p)+'"\x3e'),p=k.Wja,r=p.length,u=0;u<r;u++){for(var w=p[u],C="",H=w.quotes,R=H.length,P=0;P<R;P++)C+=""+H[P].quoteId+(P!=R-1?",":"");C=z.E(C);l+='\x3cli class\x3d"list-item list-item--inline u-border0" data-quote-ids\x3d"'+z.F(C)+'" data-quote-creator-id\x3d"'+z.F(w.user.userId)+'" data-action\x3d"highlight-quote" data-action-type\x3d"hover"\x3e'+
z.A(z.fn(z.D({user:w.user,Ee:!0},k),c))+"\x3c/li\x3e"}k=(0,z.y)(l+"\x3c/ul\x3e\x3c/div\x3e");e=e+z.A(k)+"\x3c/div\x3e"}else e="";g?(g='\x3cdiv class\x3d"quoteResponses-section'+(a.F8?" is-withEditor":"")+'"\x3e'+z.A(z.IA({title:(0,z.N)(""+z.A(z.Tm())),Qf:!0},c)),a.F8&&c.supportsEdit&&c.isAuthenticated?(k={},k=(0,z.y)('\x3cdiv class\x3d"js-inlineNewPostControl inlineNewPostControl inlineNewPostControl--quoteResponses"\x3e'+z.uQ(z.D({user:c.currentUser,isCollapsed:!0,eD:!0,type:"quoteResponses",hv:(0,z.N)(""+
z.A(z.oea()))},k),c)+"\x3c/div\x3e"),k=z.A(k)):k="",g=g+k+K3a(a,0,c)+"\x3c/div\x3e"):g="";d+=e+g;if(a.EHa&&b){g=z.n("Who can see this?");d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed u-paddingLeft0 u-paddingRight0"\x3e';e=b="";k=a.post.homeCollection;k=a.post.creator.userId!=c.currentUser.userId?k?z.n("Private notes are visible to you, the author, and the editors of {$name}.",{name:z.A(k.name)}):z.n("Private notes are visible to you, the author, and the editors of any publication this story is added to."):
k?z.n("Private notes are visible to you and the editors of {$name}.",{name:z.A(k.name)}):z.n("Private notes are visible to you and the editors of any publication this story is added to.");e+=k;e=(0,z.y)(e);e=""+z.A(e);e=(0,z.N)(e);b+='\x3cspan data-tooltip\x3d"'+z.F(e)+'"\x3e'+g+"\x3c/span\x3e";g={};g=(0,z.y)(z.dl(z.D({name:"lock",size:"19px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14 14.052a1 1 0 0 1-.992.998H5.992A.99.99 0 0 1 5 14.052v-4.004a1 1 0 0 1 .992-.998h7.016a.99.99 0 0 1 .992.998v4.004zM7 5.445C7 4.187 8.114 3.15 9.5 3.15c1.385 0 2.5 1.04 2.5 2.295V8.05H7V5.445zm6.008 2.605H13V5.445c0-1.822-1.578-3.295-3.5-3.295C7.577 2.15 6 3.618 6 5.445V8.05h-.008A2 2 0 0 0 4 10.048v4.004a1.99 1.99 0 0 0 1.992 1.998h7.016A2 2 0 0 0 15 14.052v-4.004a1.99 1.99 0 0 0-1.992-1.998z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
g)));g=(0,z.N)(""+z.A(g));e=z.n("Private notes");e=(0,z.y)(""+e);b={sJa:g,title:(0,z.N)(""+z.A(e)),Qf:!0,Lg:(0,z.N)(b),l:"heading--privateNotes"};b=(0,z.y)(z.FA(z.D({jk:(0,z.N)(""+z.GA(b,c)),rGa:!0},b)));b=d+=z.A(b);d=""+('\x3cdiv class\x3d"privateNotes-list js-notesList'+(a.xV?" is-showingNoteEditor":"")+(0==a.notes.length?" is-empty":"")+'"\x3e');g=a.notes;e=g.length;for(k=0;k<e;k++)d+=U7({note:g[k],post:a.post,zL:a.zL},0,c);a.xV?(g=a.post.creator,a="",g=c.currentUser.userId==g.userId?z.n("Leave yourself a note"):
z.n("Send {$name} a private note…",{name:z.A(g.name)}),a+=g,a=(0,z.y)(a),a='\x3cdiv class\x3d"privateNotes-actions js-noteActions"\x3e'+z.A(z.Vl({action:"show-note-editor",text:(0,z.N)(""+z.A(a)),l:"privateNotes-prompt"},0,c)),g=z.y,e='\x3cdiv class\x3d"privateNotes-editor"\x3e'+z.A(z.gn({user:c.currentUser,wf:!0},c))+'\x3cdiv class\x3d"js-noteEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',k=z.n("Send"),k=(0,z.y)(""+k),c=g(e+z.A(z.Vl({action:"save-note",isPrimary:!0,l:"js-saveNoteButton",
text:(0,z.N)(""+z.A(k))},0,c))+z.A(z.Vl({action:"hide-note-editor",text:(0,z.N)(""+z.A(J3a()))},0,c))+"\x3c/div\x3e\x3c/div\x3e"),c=a+c+"\x3c/div\x3e"):c="";c=(0,z.y)(d+("\x3c/div\x3e"+c));d=b+('\x3cdiv class\x3d"quoteResponses-inner privateNotes"\x3e'+c+"\x3c/div\x3e\x3c/div\x3e")}}else 0<a.aE&&(a=z.n("Show next tip"),b=z.n("Show previous tip"),d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed quoteResponses-section--tips u-textAlignCenter u-paddingLeft0 u-paddingRight0"\x3e\x3cdiv class\x3d"quoteResponses-section--tipsInner u-alignMiddle"\x3e'+
z.A(z.Wl({Cb:!0,Ic:!0,wa:!0,action:"previous-highlight-tip",icon:(0,z.N)(""+z.A(z.rca())),title:(0,z.N)(""+b)},c))+"\x3cdiv class\x3d'u-alignBlock quoteResponses-section--tipsContent u-paddingLeft20 u-paddingRight20 js-highlightTip'\x3e\x3c/div\x3e"+z.A(z.Wl({Cb:!0,Ic:!0,wa:!0,action:"next-highlight-tip",icon:(0,z.N)(""+z.A(z.sca())),title:(0,z.N)(""+a)},c))+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");return(0,z.y)(d+"\x3c/div\x3e")},K3a=function(a,b,c){return(0,z.y)(z.A(z.ZQ({posts:a.responses,source:"quoteResponses",
yT:!0},0,c)))},U7=function(a,b,c){var d,e=null==a.note.replies?null:a.note.replies.length,g=null==a.note.replyId,k=a.post.creator.userId==c.currentUser.userId,l=a.post.creator.userId==a.note.author.userId;d=a.note.author.userId==c.currentUser.userId;b=k||(null==a.post.homeCollection?null:a.post.homeCollection.virtuals.permissions.canEditPosts);var p=""+(g?"js-note-item"+(a.note.noteId?" js-note-"+a.note.noteId:""):"js-reply-item"+(a.note.replyId?" js-reply-"+a.note.replyId:"")),p=z.E(p),p='\x3cdiv class\x3d"privateNotes-item '+
z.F(p)+' js-note" data-note-id\x3d"'+z.F(a.note.noteId)+'"\x3e'+(g?z.A(z.fn({user:a.note.author},c)):z.A(z.KO({user:a.note.author},c)))+'\x3cdiv class\x3d"privateNotes-authorLockup"\x3e\x3cdiv class\x3d"privateNotes-author"\x3e'+z.A(z.mm({user:a.note.author},c));g||!(k||d||(null==a.post.homeCollection?0:a.post.homeCollection.virtuals.permissions.canEditPosts))||l||a.ria?k="":(k=z.n("(Editor)"),k=(0,z.y)(""+k),k='\x3cspan class\x3d"privateNotes-author--supplemental"\x3e '+z.A(k)+"\x3c/span\x3e");p=
p+k+'\x3c/div\x3e\x3cdiv class\x3d"privateNotes-supplemental"\x3e'+z.A(z.Mi(Number(a.note.createdAt),c))+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"privateNotes-content js-privateNotesContent"\x3e';k=z.A(z.Mv(String(a.note.content),c));l=String(k).replace(/(\r\n|\r|\n)/g,"\x3cbr\x3e");k=z.Zh(k,z.ai)?(0,z.y)(l,z.dba(k)):l;d=""+(p+k+"\x3c/div\x3e"+(d?M3a({note:a.note,isPrimary:g},c):""));if(g){d+='\x3cdiv class\x3d"privateNotes-replies'+(e?"":" is-empty")+' js-repliesList"\x3e';if(e)for(e=a.note.replies,
g=e.length,p=0;p<g;p++)k=e[p],d+=U7({note:k,post:a.post,ria:a.note.author.userId==k.author.userId},0,c);e=d;a.zL?(g=z.y,d='\x3cdiv class\x3d"privateNotes-editor privateNotes-editor--reply"\x3e'+z.A(z.QHa({user:c.currentUser,wf:!0},c))+'\x3cdiv class\x3d"js-replyEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',p=z.n("Send"),p=(0,z.y)(""+p),g=g(d+z.A(z.Vl({action:"save-reply",isPrimary:!0,text:(0,z.N)(""+z.A(p))},0,c))+z.A(z.Vl({action:"hide-reply-editor",text:(0,z.N)(""+z.A(J3a()))},0,c))+
"\x3c/div\x3e\x3c/div\x3e")):g="";g="\x3c/div\x3e"+g+'\x3cdiv class\x3d"privateNotes-actions'+(b?" privateNotes-actions--withDismiss":"")+' u-clearfix"\x3e';a.zL?(d=z.y,p=z.n("Reply"),p=(0,z.y)(""+p),d='\x3cdiv class\x3d"u-floatLeft"\x3e'+d(z.A(z.Vl({isPrimary:!0,action:"show-reply-editor",l:"privateNotes-prompt",text:(0,z.N)(""+z.A(p))},0,c)))+"\x3c/div\x3e"):d="";d=e+(g+d+(b?'\x3cdiv class\x3d"u-floatRight"\x3e'+M3a({note:a.note,isPrimary:!0,bia:!0},c)+"\x3c/div\x3e":"")+"\x3c/div\x3e")}return(0,z.y)(d+
"\x3c/div\x3e")},M3a=function(a,b){var c=z.y,d=a.isPrimary?a.note.noteId:a.note.replyId,e=a.bia?"dismiss-note":a.isPrimary?"delete-note":"delete-reply";a=a.bia?z.n("Dismiss note"):z.n("Delete");a=(0,z.y)(""+a);a=z.A(a);return c(z.A(z.Vl({actionValue:d,action:e,l:"privateNotes-delete js-deleteNote",text:(0,z.N)(""+a)},0,b)))},N3a=function(a,b,c){b="";if(0==a.t8)a=1==a.aE?z.n("People highlighted this passage. You can click on an existing highlight to add to it, like below:"):z.n("{$topQuoteCount} people highlighted this passage. You can click on an existing highlight to add to it, like below:",
{topQuoteCount:z.A(a.aE)}),b+=a,b+='\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.F(z.Bi(z.Uk({imageId:"1*SyXCciYXeNpx4-GUAuh0XQ.gif"},0,c)))+'"\x3e';else if(1==a.t8)a=z.n("Or, select any passage to create your own highlight and tell the author and others what resonated with you:"),b+=a+'\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.F(z.Bi(z.Uk({imageId:"1*dEp02HXMKtAeKxsV5MWqGg.gif"},0,c)))+'"\x3e';else if(2==a.t8){a=z.n("so that you can save your highlights and share them with others.");
var d=z.n("Sign up and create a profile");b+=z.A(z.Vl({text:(0,z.N)(""+d),ac:!0,source:(0,z.N)(""+z.A(z.Uj({name:c.j.kd.Dma,susiEntry:c.j.Ia.wE}))),l:"u-textUnderline"},0,c))+" "+a}return(0,z.y)(b)},V7=function(a,b,c,d,e,g,k,l){z.Q.call(this);this.ra=a;this.ya=a.get("butter-bar");this.fb=b;this.Ne=c;this.Zj=e;this.ue=a.get("quotes-data");this.uf=a.get("notes-data");this.wj=a.get("responses-data");this.jf=g;this.q0=d;this.m1=(this.aI=k)?k.Zi():null;this.Kf=this.Fc=null;this.ak={};this.Yba=!!z.Yr();
this.Zba=!!z.$r();this.XA=this.Yba&&this.Zba&&z.TF(b);this.Qq=null;this.aP=0;this.$ea=S2a(this.ue,this.Ne);this.uw=l;this.Wa(this.Jq());this.Yca=z.Yr()?2:3},O3a=function(a){a.qb(".js-block").forEach(function(a){this.Sa(a,"mouseenter",this.Ysa,this);this.Sa(a,"mouseleave",this.G2,this)},a)},P3a=function(a){a.qb(".js-note").forEach(function(a){this.Sa(a,"mouseenter",this.Wsa,this);this.Sa(a,"mouseleave",this.G2,this)},a)},Q3a=function(a,b){var c=a.query(".js-note-"+b);a.ak[b]||(a.ak[b]=new T7(a.ra,
c.querySelector(".js-replyEditor"),a.fb.Oa(),b,a.Ne),z.my(a,a.ak[b],"saving",a.wwa,a),z.my(a,a.ak[b],"save",a.qwa,a),z.my(a,a.ak[b],"fail",a.ova,a));z.Id(c,"is-noteEditorVisible");a.ak[b].focus()},R3a=function(a,b){var c=a.ak[b];c&&(c.cb()&&c.hd(""),a=a.query(".js-note-"+b),z.Pd(a,"is-noteEditorVisible"))},S3a=function(a,b,c){var d=Q7(a.jf,a.Ne);if(d){var e=[];a.uw&&(e=a.uw.quotes.map(function(a){return a.Zi()}));(0,z.Eb)(d.querySelectorAll(".markup--quote"),function(a){var d=a.getAttribute("data-creator-ids").split(" "),
d=z.Wa(d,b);if(this.uw)var l=a.getAttribute("name").split(" "),d=d&&(0,z.td)(l,z.Wa.bind(null,e));z.Xd(a,"is-selected",c&&d)},a)}},W7=function(a){return(a=z.Ot(a,function(a){return z.Hd(a,"js-note-item")}))&&a.getAttribute("data-note-id")},T3a=function(a,b,c,d){b=new z.GF(b,300);b.Wa(c);b.subscribe("dismiss",d,a);b.ua();return b},X7=function(a){var b=a.gc(),c=a.Bd();a=a.ye();1<b.length&&(a=b[0].Ha().length);var d=new z.yt;d.hq(b[0].getName());d.Cg(c);z.K(d,"endIndex",a);d.hd(b[0].Ha().substring(c,
a));return d},Y7=function(a,b){b%=a.Yca;0>b&&(b=a.Yca-1);a.aP=b;(b=a.query(".js-highlightTip"))&&z.lx(b,N3a,{t8:a.aP,aE:a.$ea})},Z7=function(a,b,c,d){z.Q.call(this);this.Wa(this.Jq(d));this.Bb=a.get("dom-monitor");this.fb=b;this.dca=!b.Ya().Ir()||b.Mb();this.nb=b.Oa();this.jf=c;this.ue=a.get("quotes-data");this.wj=a.get("responses-data");this.uf=a.get("notes-data");this.aw=null;this.Hh={}},U3a=function(a,b){b.forEach(function(a){a&&$7(this,a)},a)},$7=function(a,b){if(!a.aw)if(Q7(a.jf,b)){var c=V3a(a,
b),c=W3a(a,c),c=X3a(a,c),c=Y3a(a,c);a.Hh[b]=c;Z3a(a,b)}else delete a.Hh[b]},$3a=function(a,b){if(!a.aw){var c=a.Hh[b];if(c){var d=c.length,c=X3a(a,c),c=Y3a(a,c);a.Hh[b]=c;d!=c.length?Z3a(a,b):c.forEach(function(a){a.Xa&&a.offsetTop&&(a.Xa.style.top=a.offsetTop+"px")})}}},a4a=function(a,b,c){return z.Ua(a.Hh[b]||[],function(a){return a.Xa==c})},V3a=function(a,b){var c=[];K7(a.uf,b).Pg(function(a){var e=a.tC(),g;e?(g=this.uf.VS(e),e=g.hb(),g=z.J(g,"endIndex")):(e=0,g=a.cb().length);c.push({anchor:b,
startIndex:e,endIndex:g,notes:[a],quotes:[],responses:[]})},a);if(a.dca)return c;(a.ue.Rt[b]||[]).forEach(function(a){var e=b4a(a);c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[a],responses:[]})},a);y7(a.wj,b).forEach(function(a){var e=w7(a);e&&(e=x7(e)&&x7(e).Zn())&&(e=b4a(e),c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[],responses:[a]}))},a);return c},W3a=function(a,b){var c=[];b.sort(function(a,b){return a.startIndex-b.startIndex});
b.forEach(function(a){var b=z.Sa(c,function(b){return b.endIndex>=a.startIndex-1&&b.startIndex<=a.endIndex+1});0<=b?this.sH(c[b],a):c.push(a)},a);return c},Y3a=function(a,b){var c=[];b.forEach(function(a){if(a.offsetTop){var b=z.Sa(c,function(b){return 30>=Math.abs(b.offsetTop-a.offsetTop)});0<=b?this.sH(c[b],a):c.push(a)}},a);return c},Z3a=function(a,b){a.qb(".js-paragraphControl-"+b).forEach(z.Dh);a.Hh[b]=a.Hh[b].map(function(a){var b=c4a(this,a),b=z.nx(d4a,b);b.style.top=a.offsetTop+"px";a.Xa=
b;this.oa().appendChild(a.Xa);z.Id(b,"is-visible");return a},a)},c4a=function(a,b){var c=b.notes,d=b.responses,e=s7(a.ue,b.quotes),g=d?d.length:0,k=c?c.length:0,l=0,p=0,r=0,u=!1,w=!1,C={},H={},R=z.Xr().userId,P=a.fb.Ya().Gf().mb();c.forEach(function(a){var b=a.HJ();b&&((a=z.J(a,"replies"))&&a.forEach(function(a){k++;a.author&&(a.author.userId==R&&l++,a.author.social&&a.author.social.isFollowing&&(C[a.author.userId]=a.author),H[a.author.userId]=!0)}),H[b.userId]=!0,b.userId==R&&l++,b.userId==P?p++:
r++,b.social&&b.social.isFollowing&&(C[b.userId]=b))});e.forEach(function(a){a=a.user;H[a.userId]=!0;a.userId==R&&(u=!0);a.social&&a.social.isFollowing&&(C[a.userId]=a)});d.forEach(function(a){a=a.Gf();H[a.userId]=!0;a.userId==R&&(w=!0);a.social&&a.social.isFollowing&&(C[a.userId]=a)});c=b.quotes.filter(function(a){return"anon"==a.mb()});return{postId:a.nb,UB:b.anchor,CHa:k,pIa:g,My:w,Dy:l,mja:p,DHa:r,T_a:e.length,Ly:u,Rha:Object.keys(H).length,uFa:z.ob(C),aE:c.length}},b4a=function(a){var b=a.Bd(),
c=a.ye();1<a.paragraphs.length&&(c=a.paragraphs[0].text.length);return{startIndex:b,endIndex:c}},X3a=function(a,b){var c=z.Ix();return b.map(function(a){var b=this.jf.get(a.anchor),g=this.fb.Yi(b);if(!g)return a;var k;4==g.type&&(g.Ha()&&(k=b.querySelector("figcaption")),k||(k=b));if(!k){g=a.startIndex+1;b=[b];k=0;for(var l=null;0<b.length&&k<g;)if(l=b.pop(),!(l.nodeName in z.iIa))if(3==l.nodeType){var p=l.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");k+=p.length}else if(l.nodeName in z.FR)k+=
z.FR[l.nodeName].length;else for(p=l.childNodes.length-1;0<=p;p--)b.push(l.childNodes[p]);k=l}g=z.Lx(k,!0);a.offsetTop=Math.round(g.top+c.top);return a},a)},d4a=function(a,b,c){b=z.y;var d='\x3cdiv class\x3d"paragraphControls js-paragraphControl js-paragraphControl-'+z.F(a.UB)+' u-noUserSelect"\x3e',e=z.y,g;if(a.CHa||a.pIa){g='\x3cdiv class\x3d"notesMarker u-noUserSelect" data-action\x3d"select-anchor" data-action-value\x3d"'+z.F(a.UB)+'"\x3e';var k;k={};k=(0,z.y)(z.dl(z.D({name:"asteriskFilled",
size:"19px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14.78 8.07a8.681 8.681 0 0 0-.427-1.383.478.478 0 0 0-.584-.27l-3.12.77V4.034c0-.247-.19-.48-.43-.5a7.23 7.23 0 0 0-1.38 0c-.24.02-.43.253-.43.5V7.19L5.3 6.415a.48.48 0 0 0-.583.27c-.18.448-.324.91-.426 1.383-.05.24.1.5.32.58l3.06.754-1.98 2.956c-.14.196-.13.502.04.67.34.332.7.632 1.09.896.2.136.49.077.63-.117l2.09-3.114 2.09 3.112c.15.193.43.252.63.116.39-.26.75-.56 1.09-.89.17-.17.19-.47.04-.67L11.4 9.41l3.06-.76a.517.517 0 0 0 .32-.58" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
k)));g=g+z.A(k)+"\x3c/div\x3e"}else g="";var l=k="",p="",r=1==a.Dy?z.n("a note"):z.n("notes"),p=p+(""+r),p=z.E(p);1==a.Rha&&(0<a.Dy||a.Ly||a.My)&&(0<a.Dy&&a.Ly&&a.My?(p=z.n("highlighted, responded, and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):0<a.Dy&&a.My?(p=z.n("responded and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):0<a.Dy&&a.Ly?(p=z.n("highlighted and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):a.Ly&&a.My?(p=z.n("highlighted and responded"),l+=" "+p):a.Ly?
(p=z.n("highlighted"),l+=" "+p):0<a.Dy?(p=z.n("left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):a.My&&(p=z.n("responded"),l+=" "+p));l=z.E(l);k+='\x3cspan class\x3d"paragraphControls-itemText"\x3e';p="";if(0<a.mja&&0==a.DHa&&!a.Ly&&!a.My)c=1==a.mja?z.n("Note to self"):z.n("Notes to self"),p+=c;else{r="";if(0<a.aE)var u=z.n("Top highlight"),r=r+u;p+=z.A(z.JQ(z.D({social:a.uFa,isActive:0<a.Dy||a.Ly||a.My,Fi:a.Rha,V5:!0,OHa:!0,uga:(0,z.N)(r)},a),c));p+=z.A(l)}p=(0,z.N)(p);k+=z.A(z.zGa(z.D({text:p},
a)))+"\x3c/span\x3e";a=(0,z.y)(k);a=e(g+a);return b(d+a+"\x3c/div\x3e")},a8=function(a,b,c){z.Q.call(this);this.ra=a;this.Ja=a.get("app");this.Fra=a.get("floating-components");this.Pa=a.get("screen");this.tb=a.get("screen-service");this.Bb=a.get("dom-monitor");this.fb=b;this.Ud=b.Ud;this.em=this.Ud.querySelector(".js-postField");this.nda=this.Pa.oa().querySelector(".js-notesPositionContainer");this.ue=a.get("quotes-data");this.uf=a.get("notes-data");this.uf.subscribe("new_note_list",this.Mva,this);
this.wj=a.get("responses-data");this.dm=null;this.jf=new y3a(this.Ud.querySelector(".js-notesSource"));this.qH=this.Hh=this.JQ=null;this.Hh=new Z7(a,b,this.jf,this.nda);this.track(this.Hh);this.qH=this.Hh.oa();this.ah=this.T_=null;this.Pe=c},c8=function(a,b){if(a.isActive()){var c=(b=b||a.T_)&&b.rT,d=b&&b.noteId;c&&(a.Vw(c),d&&a.uf.Kp(d,c)&&a.ah&&z.t(a.ah,function(){return b8(a,c,null,d)}));z.Gma(a.Ja,"")}else a.T_=b||null},b8=function(a,b,c,d,e,g){var k={Ck:!0,O5:z.rx()};a.u1();c=new V7(a.ra,a.fb,
b,d||"",c||null,a.jf,e||null,g||null);c.subscribe("set-active-highlight",a.iea,a);c.subscribe("reset-highlight",a.cza,a);c.subscribe("close",a.u1,a);b=g&&g.Xa?g.Xa:a.jf.get(b);g=z.mwa(a.Fra);g.Fn=b;b=g.eE(c);b.RI=k;k=b.dW(a.zn.bind(a));k.zQ=!0;a.dm=k.ua()},e4a=function(a,b,c){var d=a.fb.Yi(Q7(a.jf,b));if(d&&4!=d.type){z.xu(d,4);if(c){if(!w3a(c,d))return;z.vu(d,z.eu(c.startIndex,c.endIndex,c.id))}c=a.fb.Mb();var e=a.fb.Ya();c={mode:c?"edit":"view",Kj:z.Ku(e),media:null,Sl:null,sections:!0,Dk:!1,yk:!1,
xl:!1,Mf:!1,postId:e.id};a.jf.get(b).innerHTML=z.Cv(d,z.ho,c)}},f4a=function(a,b){var c=z.tp();if(!c||c.isCollapsed())if(b&&(c=b),!c||c.isCollapsed())return null;b=c.Pf();var d=A3a(a.jf,b);if(!d)return null;a=(b=z.Ot(b,z.wC,d))&&a.fb.Yi(b);if(!b)return null;var d=z.Nx(c,b,!0),e=z.Nx(c,b,!1);return-1==d||-1==e?null:new x3a(c,b,new z.yt({anchor:b.getAttribute("name"),startIndex:d,endIndex:e,content:a.Ha().substring(d,e)}))},g4a=function(){},d8=function(a,b){z.Q.call(this);this.Mh=b||d3a;this.kb=a.get("screen-request");
this.va=null;this.R2=a.get("screen-view-state");this.ra=a;this.wea=this.W1=!1;this.J0=this.Fc=null},e8=function(a){z.ky.call(this);this.hz=a},h4a=function(a,b,c){a=z.qa(a)?new z.Je(a):a;(a=l3a(a,b,c||{}))&&(new e8(a)).focus()},i4a=function(a){this.pa=a.get("request");this.ma=a.get("route-builder")},f8=function(a){z.jo.call(this);this.ra=a;this.bG=a.get("dialog");this.pa=a.get("request");this.ma=a.get("route-builder");this.ya=a.get("butter-bar");this.aJ=this.Da=this.lx=this.va=null;this.fP=!1},k4a=
function(a){var b=a.Da.query(".js-tweetEditor-image"),c=a.Da.query(".js-tweetEditor-imageContainer"),d=a.Da.query(".js-tweetEditor-imageStatus");z.Id(c,"u-hide");var e=j4a(a);e.base64=!0;z.v(z.t(a.pa.post(z.mx(o3a),e,{VB:!1,withCredentials:!1}),function(a){b.src="data:image/png;base64,"+a;z.Pd(c,"u-hide");z.Id(d,"u-hide");this.fP=!0},a),function(a){z.gy(a);z.lx(d,q3a)},a)},l4a=function(a,b){return 280>=A7(b)?!0:(b=a.Da.query(".js-tweetEditor-text"),(new z.jB(b,{name:"shimmy-shake",duration:400})).start(),
a=a.Da.query(".js-tweetEditor-error"),z.lx(a,u3a),!1)},j4a=function(a){var b=a.va,c=a.lx.pJa;a=a.lx.oJa;var d=b.creator,e=b.approvedHomeCollection,g=z.ho,k=null;e&&(k=e.image);var l=null;e&&e.logo&&e.logo.imageId&&(l=e.logo.imageId);var p=null;e&&e.tintColor&&2==e.colorBehavior&&e.logo&&e.logo.imageId&&(p=e.tintColor);var r=null;e&&e.tintColor&&(r=z.ZHa(e.tintColor),r=z.kt(r,.6).color);return new C7({content:c,altText:a,title:b.title,author:d&&d.name,date:z.Li(b.createdAt,g),authorAvatarId:d&&d.imageId,
collection:e&&e.name,collectionAvatarId:k?k.imageId:null,collectionLogoId:l,collectionBackgroundColor:p,collectionHighlightColor:r,version:2})},m4a=function(a){this.pa=a.get("request");this.ma=a.get("route-builder");this.ra=a};z.q(q7,z.L);z.f=q7.prototype;z.f.ca=function(){return""};z.f.ea=function(){return"Placement"};z.f.yf=function(){return z.J(this,"items")};z.f.Wc=z.h(380);z.f.rL=function(a){return z.K(this,"location",a)};z.f.Ad=z.h(422);z.f.Ub=function(a){return z.K(this,"index",a)};
z.f.ha=function(){return q7.prototype};z.f.fa={name:"Placement",ia:!1,fields:{items:{name:"items",g:function(){return z.SM},qa:z.U,h:1},location:{name:"location",g:function(){return z.yza},h:2},index:{name:"index",g:z.W,h:3}},ka:{}};z.f.Ad=z.Y(422,function(){return z.J(this,"index")});z.f.Wc=z.Y(380,function(a){return z.K(this,"items",a)});z.m(t7,z.zf);t7.prototype.qk=function(a){var b={};z.pE(this,b,a.Pb(),"");return b};
t7.prototype.Hb=function(a,b){if(!a||!b)return null;var c=new a;Object.keys(b).forEach(function(a){for(var e=a.split(/[[\]]+/).filter(function(a){return!!a}),g=c,k=e.shift();k;){var l=z.hj(g,k);if(!l)break;var p=l.g();if(l.qa()){var r=z.dj(g,k)||[],u=e.shift(),w=Number(u);if(void 0===u||!Number.isInteger(w)||0>w)break;if(p.prototype instanceof z.Si)l=r[w],l||(l=new p,r[w]=l),z.K(g,k,r),g=l;else{if(void 0!==e.shift())break;p=L2a(b[a],l);r[w]=p;z.K(g,k,r)}}else if(p.prototype instanceof z.Si)r=z.dj(g,
k),r||(r=new p,z.K(g,k,r)),g=r;else{if(void 0!==e.shift())break;p=L2a(b[a],l);z.K(g,k,p)}k=e.shift()}});return c};z.q(u7,z.jj);z.f=u7.prototype;z.f.ca=function(){return""};z.f.ea=function(){return""};z.f.gT=z.h(564);z.f.ha=function(){return u7.prototype};z.f.fa={name:"PlacementsResponse",ia:!1,fields:{placements:{name:"placements",g:function(){return q7},qa:z.U,h:1}},ka:{}};z.q(v7,z.L);v7.prototype.ca=function(){return""};v7.prototype.ea=function(){return""};v7.prototype.ha=function(){return v7.prototype};
v7.prototype.fa={name:"PlacementsRequestQuery",ia:!1,fields:{requestContext:{name:"requestContext",g:function(){return z.ms},h:1},slots:{name:"slots",g:function(){return z.os},qa:z.U,h:2}},ka:{}};z.tW.prototype.sV=z.Y(579,function(a){a!=this.pP&&this.yb&&(this.yb.ci.contentEditable=a);this.pP=a});z.JH.prototype.dW=z.Y(570,function(a){this.zn=a;return this});z.OH.prototype.dW=z.Y(569,function(a){this.zn=a;return this});
z.tH.prototype.O4=z.Y(568,function(a){a=w7(a);if(!a)return null;a=x7(a)&&x7(a).Zn();return a?(a=a.gc())&&a.length?a[0].getName():null:null});u7.prototype.gT=z.Y(564,function(){return z.J(this,"placements")});z.qE.prototype.gT=z.Y(563,function(a,b){var c=this;a=N2a(O2a(new v7,a),b);a=(new t7).qk(a);var d=this.ma.la(z.Exa,{},a);return z.rE(this,d,function(){return z.t(c.pa.get(d,{background:!0}),function(a){a=c.Ka.ic(u7,a);c.Aa.lc(a);return a})})});
z.Ey.prototype.Kp=z.Y(480,function(){return z.J(this,"note")});z.kE.prototype.Kp=z.Y(479,function(a){return this.pc("Note",a)});z.xt.prototype.Yx=z.Y(450,function(){return z.J(this,"replyId")});z.Ey.prototype.Yx=z.Y(449,function(){return z.J(this,"replyId")});z.vt.prototype.Sy=z.Y(448,function(a){return z.K(this,"highlight",a)});z.vt.prototype.VS=z.Y(447,function(){return z.J(this,"highlight")});z.vt.prototype.mv=z.Y(446,function(a){return z.K(this,"author",a)});
z.xt.prototype.mv=z.Y(445,function(a){return z.K(this,"author",a)});z.vt.prototype.HJ=z.Y(444,function(){return z.J(this,"author")});z.xt.prototype.HJ=z.Y(443,function(){return z.J(this,"author")});z.vt.prototype.tC=z.Y(442,function(){return z.J(this,"highlightId")});z.vt.prototype.Ds=z.Y(441,function(a){return z.K(this,"state",a)});z.xt.prototype.Ds=z.Y(440,function(a){return z.K(this,"state",a)});z.yy.prototype.Ds=z.Y(439,function(a){return z.K(this,"state",a)});
z.vt.prototype.sg=z.Y(438,function(){return z.J(this,"noteId")});z.xt.prototype.sg=z.Y(437,function(){return z.J(this,"noteId")});z.Ey.prototype.sg=z.Y(436,function(){return z.J(this,"noteId")});z.Qs.prototype.nv=z.Y(435,function(a){return z.K(this,"authorId",a)});z.vt.prototype.nv=z.Y(434,function(a){return z.K(this,"authorId",a)});z.xt.prototype.nv=z.Y(433,function(a){return z.K(this,"authorId",a)});z.Mr.prototype.Je=z.Y(342,function(){return z.J(this,"catalogId")});
z.eL.prototype.Je=z.Y(341,function(){return z.J(this,"catalogId")});z.WK.prototype.Je=z.Y(340,function(){return z.J(this,"catalogId")});z.UK.prototype.Je=z.Y(339,function(){return z.J(this,"catalogId")});z.SM.prototype.Je=z.Y(338,function(){return z.J(this,"catalogId")});z.AK.prototype.Je=z.Y(337,function(){return z.J(this,"catalogId")});z.xM.prototype.Je=z.Y(336,function(){return z.J(this,"catalogId")});z.tL.prototype.Je=z.Y(335,function(){return z.J(this,"catalogId")});
z.pM.prototype.Je=z.Y(334,function(){return z.J(this,"catalogId")});z.oM.prototype.Je=z.Y(333,function(){return z.J(this,"catalogId")});z.nM.prototype.Je=z.Y(332,function(){return z.J(this,"catalogId")});z.Qs.prototype.Je=z.Y(331,function(){return z.J(this,"catalogId")});z.Ey.prototype.Je=z.Y(330,function(){return z.J(this,"catalogId")});z.pI.prototype.Je=z.Y(329,function(){return z.J(this,"catalogId")});z.mq.prototype.hT=z.Y(82,function(){return z.J(this,"point")});var Y2a=/(?:https?:\/\/|www\.)\w[\w~#-@![\]]*/g;
z7.prototype.hT=function(){var a=window.document.body;return z.Kh(a,this.li.node)?this.li:this.Mk&&z.Kh(a,this.Mk)?z.EN(this.UP,this.Mk):this.Ne&&(a=z.Rt(this.Bra,this.Ne))?z.EN(this.UP,a):null};z.q(B7,z.Go);B7.prototype.bL=function(){if(!this.dk)return null;var a=this.dk.hT();if(!a)return null;var b=this.im.hT();return b?z.gp(a.node,a.offset,b.node,b.offset):null};z.q(C7,z.L);z.f=C7.prototype;z.f.ca=function(){return""};z.f.ea=function(){return""};z.f.cb=function(){return z.J(this,"content")};
z.f.hd=function(a){return z.K(this,"content",a)};z.f.Gb=function(){return z.J(this,"title")};z.f.Oc=function(a){return z.K(this,"title",a)};z.f.HJ=function(){return z.J(this,"author")};z.f.mv=function(a){return z.K(this,"author",a)};z.f.getDate=function(){return z.J(this,"date")};z.f.setDate=function(a){return z.K(this,"date",a)};z.f.Fb=function(){return z.J(this,"collection")};z.f.setVersion=function(a){return z.K(this,"version",a)};z.f.vL=function(a){return z.K(this,"template",a)};
z.f.Xd=function(){return z.J(this,"subtitle")};z.f.Bf=function(a){return z.K(this,"subtitle",a)};z.f.ha=function(){return C7.prototype};
z.f.fa={name:"TextshotInfo",ia:!1,fields:{content:{name:"content",g:z.V,h:1},altText:{name:"altText",g:z.V,h:2},title:{name:"title",g:z.V,h:3},author:{name:"author",g:z.V,h:4},date:{name:"date",g:z.V,h:5},authorAvatarId:{name:"authorAvatarId",g:z.V,h:6},collection:{name:"collection",g:z.V,h:7},collectionAvatarId:{name:"collectionAvatarId",g:z.V,h:8},collectionLogoId:{name:"collectionLogoId",g:z.V,h:9},collectionBackgroundColor:{name:"collectionBackgroundColor",g:z.V,h:10},collectionHighlightColor:{name:"collectionHighlightColor",
g:z.V,h:11},version:{name:"version",g:z.W,h:12},base64:{name:"base64",g:z.yI,h:13},template:{name:"template",g:z.V,h:14},mainStat:{name:"mainStat",g:z.V,h:15},mainStatTitle:{name:"mainStatTitle",g:z.V,h:16},subtitle:{name:"subtitle",g:z.V,h:17},icon:{name:"icon",g:z.V,h:18},imgKey:{name:"imgKey",g:z.V,h:19}},ka:{}};var n4a={mRa:"quote-respond"};z.q(E7,z.Q);z.f=E7.prototype;z.f.rk=function(){return this.nm.rk()};
z.f.na=function(){E7.xa.na.call(this);z.my(this,this.LZ,"data-redirect-type-quote",this.Wua,this);this.Sa(this.Ud,"click",this.nw,this);z.UF(this.fb)&&z.px()&&this.Sa(this.Ud,"mouseover",this.qsa,this);this.fb.Ya().Ir()&&!this.fb.Mb()&&z.v(this.ue.load(this.fb.Oa()),z.gy);var a=this.rk();a&&(z.my(this,a,"quote",this.nsa,this),z.my(this,a,"quote-respond",this.osa,this),z.my(this,a,"show",this.J2,this),z.my(this,a,"hide",this.pva,this))};
z.f.Wua=function(a){var b=z.CF(this.nm,this.rk().ix);b&&(a.url=new z.Je(this.ma.la(z.JAa,{postId:this.fb.Oa()},{paragraphs:JSON.stringify([b.gy.Hb().Pb()]),startOffset:b.start,endOffset:b.end})))};z.f.nw=function(a){z.Ot(a.target,function(a){if(a===this.Ud)return!0;var c=z.FC(a);if(3==c)return!0;if(7==c){if(c=h3a(this,a))if(F7(this,c),z.px())H7(this,c);else{var d=new z.EF;f3a(this,c,a,d)}return!0}return!1}.bind(this))};
z.f.qsa=function(a){z.Ot(a.target,function(a){if(a===this.Ud)return!0;var c=z.FC(a);if(3==c)return!0;if(7==c){c=z.tp();if(!(c&&!c.isCollapsed()||this.rk()&&this.rk().Mm())&&(c=h3a(this,a))){var d=this.Ud.querySelector('.markup--quote[name~\x3d"'+c.Zi()+'"]');a=new z.GF(a,100);f3a(this,c,d,a);F7(this,c)}return!0}return!1}.bind(this))};
z.f.J2=function(){var a=z.tp();a&&!a.isCollapsed()&&F7(this,null);if(z.UF(this.fb)&&(a=z.CF(this.nm,this.rk().ix))){var a=z.yta(this.ue,a.gy,a.start,a.end),b=this.rk().Ra().querySelector(".js-highlightMenuQuoteButton");z.Xd(b,"is-active",!!a)}};z.f.pva=function(){this.wp&&F7(this,null)};
z.f.nsa=function(){if(z.UF(this.fb)){var a=z.xF(this.rk());if(a){var b=a.range,c=a.MGa,a=this.rk().Ra().querySelector(".js-highlightMenuQuoteButton"),d=z.Hd(a,"is-active"),b=z.CF(this.nm,b);z.v(z.t(this.ue.toggle(b.gy,b.start,b.end,!c),function(a){z.cIa();d?z.zF(this.rk()):H7(this,a);var b=c?"selection_menu":"quote_click_menu";I7(this,a.Zi(),!d,b)},this),z.gy)}}};
z.f.osa=function(){if(z.UF(this.fb)&&z.ho.supportsEdit){var a=z.xF(this.rk());if(a){var b=z.CF(this.nm,a.range);z.v(z.t(this.ue.create(b.gy,b.start,b.end,1,!0),function(a){I7(this,a.Zi(),!0,"selection_menu_quote_respond");this.za("quote-respond",a,b.gy.name)},this),z.gy)}}};
z.f.xsa=function(a){var b=this.wp,c=G7(this,b),d=b.Bd(),e=b.ye(),b=a.query(".js-quoteAttributions-pileOn"),g=z.Hd(b,"is-active");z.v(z.t(this.ue.toggle(c,d,e,!0),function(b){var l=a.query(".js-quoteAttributions-pileOn");z.Yd(l,"is-active");if(l=z.tF(this.ue,c,d,e)){var p=e3a(this,l),r=a.query(".js-quoteAttributions-info");z.lx(r,X2a,p)}else a.Sc();!g&&z.px()&&(a.Sc(),H7(this,l));l=z.px()?"quote_hover":"quote_click_mobile";I7(this,b.Zi(),!g,l)},this),z.gy)};
z.f.ysa=function(){if(z.UF(this.fb)&&z.ho.supportsEdit){var a=G7(this,this.wp),b=this.wp.Bd(),c=this.wp.ye();z.v(z.t(this.ue.create(a,b,c,1,!0),function(b){I7(this,b.Zi(),!0,"quote_respond");this.za("quote-respond",b,a.name)},this),z.gy)}};z.f.zsa=function(){var a=j3a(this,this.wp);a&&z.Ita(this.nm,a)};
z.f.Xda=function(){var a=new B7(this.Ud),b=this.ue.Rt,c=Object.keys(b).concat(this.Baa);z.fb(c);c.forEach(function(a){var c=b[a]||[],g=this.fb;if(g=(a=g.Ud&&z.Rt(g.Ud,a))&&this.fb.Yi(a))W2a(g,c),a.innerHTML=z.Cv(g,z.ho,z.Yta(this.fb)),z.ywa(this.gya,a)},this);this.Baa=Object.keys(b);(a=a.restore())&&a.select()};z.q(J7,z.ky);z.f=J7.prototype;
z.f.load=function(a){if(!z.Yr())return z.xd([]);this.nb=a;this.Eh||(this.Eh=z.v(z.t(this.jl.get(this.ma.la(z.BAa,{postId:a}),{background:!0}),this.eya,this),z.gy));return this.Eh.Zc()};z.f.Sp=function(){return this.yaa};z.f.tk=function(){return this.uda};z.f.VS=function(a){return this.Mba[a]||null};z.f.Kp=function(a,b){return z.mO(K7(this,b),a)};z.f.Sy=function(a,b){this.Mba[a]=b};z.f.Oa=function(){return this.nb};
z.f.eya=function(a){var b=a.references.User;this.uda=a.post.visibility;var c=a.value;if(c)for(var d=0;d<c.length;d++){var e=c[d];if("HIDDEN"!=e.state){var g=e.replies,k=b;if(g)for(var l=0;l<g.length;l++){var p=g[l],r=p.authorId||null;p.author=r&&k[r]||null}g=e.anchor;k=e.authorId||null;e.author=k&&b[k]||null;g=K7(this,g);e=z.wt(e);g.add(z.pD(this.Aa,e))}}if(a=a.highlights)for(b=0;b<a.length;b++)this.Sy(a[b].id,z.bq.Hb(z.yt,a[b]));this.yaa=!0};z.m(N7,z.Q);N7.prototype.na=function(){var a=this;z.Q.prototype.na.call(this);z.t(this.kb.gT(this.Vya,this.Rxa),function(b){b.placements&&b.placements.forEach(a.kta,a)})};N7.prototype.kta=function(a){if(this.isActive()){var b;switch(a.location){case 1:b=this.Pa.query(".js-postFooterPlacements");if(!b)break;z.lx(b,z.VQ,{items:a.items,context:9});z.T(b).ba("show-more-recommendations",this.AAa,this);break;case 2:(b=this.Pa.query(".js-readNextMetabarRight"))&&z.lx(b,z.VQ,{items:a.items,context:2})}}};
N7.prototype.AAa=function(a){z.Jy(z.kEa,{});var b=this.Pa.query(".js-moreRecommendations");b&&(z.Ut(b),z.Tt(a.target))};z.m(O7,z.Q);z.f=O7.prototype;
z.f.na=function(){var a=this;z.Q.prototype.na.call(this);this.gp&&(z.my(this,this.gp,z.TEa,function(){z.Id(a.oa(),"is-abovePostActions");a.nP=!0}),z.my(this,this.gp,z.UEa,function(){z.Pd(a.oa(),"is-abovePostActions");a.nP=!1}));z.T(this.oa()).ba("dismiss-meter",this.ft,this).ba("expand-meter",this.vra,this);var b=this.gh.postIds&&1<this.gh.postIds.length,c=z.Or().isMobile&&!z.Or().isTablet;if(b||c)this.Sv=(0,window.setTimeout)(this.ft.bind(this),o4a);z.t(z.Co(300),this.Eya,this)};
z.f.Ca=function(){this.ah&&(this.ah.cancel(),this.ah=null);this.Sv&&((0,window.clearTimeout)(this.Sv),this.Sv=null);z.Q.prototype.Ca.call(this)};z.f.ft=function(){var a=this;this.ah=new z.jB(this.oa(),{name:this.nP?z.Or().isMobile?"pop-shift-down-35":"pop-shift-down-44":"pop-shift-down-0",duration:550,timing:"ease-in-out"});z.t(this.ah,function(){z.Tt(a.oa());z.Or().isMobile&&z.Ut(a.Pa.query(".js-openInAppButton"))});this.ah.start()};
z.f.vra=function(a){a=a.target;var b=this.query(p4a),c=this.query(q4a);z.Tt(a);z.Id(b,"is-visible");this.Sv&&((0,window.clearTimeout)(this.Sv),this.Sv=null);z.lx(c,z.Oua);z.Pd(c,"u-xs-hide");z.Jy(z.sEa,{unlockCount:this.gh.postIds.length})};
z.f.Eya=function(){var a=this;this.Pa.oa().appendChild(this.oa());z.t((new z.jB(this.oa(),{name:this.nP?z.Or().isMobile?"pop-shift-up-35":"pop-shift-up-44":"pop-shift-up-0",duration:800,timing:"ease-in-out"})).start(),function(){if(a.gh&&a.gh.postIds&&a.gh.postIds.length){for(var b=a.qb(".js-meterThumbnail"),c=new z.dd,d=0;d<a.gh.postIds.length;d++)z.t(c,a.OX.bind(a,b[d],d==b.length-1));c.callback()}})};
z.f.OX=function(a,b){b=new z.jB(a,{name:b?"pulse-grow-50-110":"pulse-grow-50-105",duration:800+(b?200:0)});var c=z.t(new z.jB(a.querySelector(".js-thumbnailImage"),{name:"fade-in",duration:800}),function(){z.Id(a,"is-read")}),d=new z.jB(a.querySelector(".js-thumbnailText"),{name:"color-light-to-white",duration:800});return new z.io([b.start(),c.start(),d.start()])};var o4a=6E3,q4a=".js-dismissMeterIndicator",p4a=".js-moreInfo";P7.prototype.jS=function(a,b,c){return new E7(a,b,c)};P7.prototype.Nr=function(){return n4a};y3a.prototype.get=function(a){return Q7(this,a)};z.q(R7,z.tW);z.f=R7.prototype;z.f.oI=!1;z.f.KA="";z.f.pI=0;z.f.Yr=z.U;z.f.sg=function(){return this.q0};z.f.save=function(){this.cb().length<=this.mm&&this.ll()};z.f.Db=function(){(0,window.clearTimeout)(this.pI);R7.xa.Db.call(this)};
z.f.na=function(){function a(a){a.stopPropagation()}R7.xa.na.call(this);this.KA=this.cb();this.hd(this.KA);this.ux(13,this.u0,this);this.ux(27,this.v0,this);this.yb.Sa("blur",this.t0,!1,this);var b=this.yb.Ra();z.Ax(b,"keydown",a);z.Ax(b,"keyup",a);z.Ax(b,"keypress",a)};z.f.W6=function(a){return a};
z.f.ll=function(){if(this.isEnabled()){var a=this.cb().trim();if(a){this.sV(!1);var b=this.jha(),a=this.iha(a);this.za("saving",a);z.od(z.v(z.t(this.jl.post(b,a.Pb()),this.Qva,this),this.Ova.bind(this,a)),this.sV.bind(this,!0))}}};z.f.Qva=function(a){this.za("save",this.W6(a.value))};z.f.Ova=function(a,b){this.za("fail",a);this.Da.error(B3a());z.gy(b)};z.f.u0=function(a){if(this.cu&&z.ZX(this.cu))return!1;a.shiftKey||(a.preventDefault(),this.save());return!0};
z.f.v0=function(a){if(this.cu&&z.ZX(this.cu))return!1;a.preventDefault();this.hd(this.KA);this.za("cancel");return!1};z.f.t0=function(){this.oI&&(this.cb().length>=this.mm?(0,window.confirm)(this.lha())?(this.hd(this.KA),this.za("cancel")):this.focus():this.pI=(0,window.setTimeout)(this.ll.bind(this),100))};z.q(S7,R7);z.f=S7.prototype;z.f.KX=null;z.f.S$=null;z.f.LX=null;z.f.Zj=null;z.f.j_=null;z.f.i_=null;z.f.Lba=null;z.f.Sy=function(a){this.Zj=a;this.j_=a.startIndex;this.i_=a.endIndex;this.Lba=a.content;return this};z.f.lha=function(){var a=z.n("Your note is too long; do you want to abandon your changes?");return(0,z.y)(""+a)};z.f.W6=function(a){var b=z.jx();a=z.wt(a).mv(b).nv(b.mb());this.Zj&&a.tC()&&this.uf.Sy(a.tC(),this.Zj);var b=this.uf,c;c=z.pD(b.Aa,a);K7(b,c.oe()).add(c);return a};
z.f.jha=function(){return this.sg()?this.ma.la(z.CAa,{postId:this.nb,noteId:this.sg()}):this.ma.la(z.AAa,{postId:this.nb})};z.f.iha=function(a){var b=z.jx();a=(new z.vt({content:a,anchor:this.KX,anchorContent:this.S$,anchorImage:this.LX?this.LX.Pb():null,replies:[],createdAt:Date.now()})).mv(b);null!=this.j_&&null!=this.i_&&(b=new z.yt({anchor:this.KX,startIndex:this.j_,endIndex:this.i_,content:this.Lba}),a.Sy(b));return a};z.q(T7,R7);T7.prototype.lha=function(){var a=z.n("Your reply is too long; do you want to abandon your changes?");return(0,z.y)(""+a)};T7.prototype.W6=function(a){var b=z.jx();a=z.$ha(a).mv(b).nv(b.mb());z.J(this.uf.Kp(a.sg(),this.Ne),"replies").push(a);return a};T7.prototype.jha=function(){return this.Tda?this.ma.la(z.FAa,{postId:this.nb,noteId:this.sg(),replyId:this.Tda}):this.ma.la(z.EAa,{postId:this.nb,noteId:this.sg()})};
T7.prototype.iha=function(a){var b=z.jx();return(new z.xt({replyId:"",postId:this.nb,noteId:this.sg(),content:a,createdAt:Date.now()})).mv(b)};z.q(V7,z.Q);z.f=V7.prototype;
z.f.na=function(){V7.xa.na.call(this);z.T(this.oa()).ba("show-note-editor",this.b2,this).ba("hide-note-editor",this.f_.bind(this,!0)).ba("show-reply-editor",this.OAa,this).ba("hide-reply-editor",this.Usa,this).ba("save-note",this.uza,this).ba("save-reply",this.vza,this).ba("highlight-quote",this.Xsa,this).ba("dismiss-note",this.Faa.bind(this,!0),this).ba("delete-note",this.Faa.bind(this,!1),this).ba("delete-reply",this.Kqa,this).ba("previous-highlight-tip",this.cya,this).ba("next-highlight-tip",this.yua,
this);P3a(this);this.wj&&r7(this.wj)&&(O3a(this),z.my(this,r7(this.wj),"add",this.Nva,this));if(this.m1&&this.Yba&&this.Zba){var a=this.query(".js-inlineNewPostControl"),b=this.m1,c=this.fb.Oa(),d=new z.iX(this.ra);d.mL("web-inline-quote-responses");d.Wa(a);d.dG=!0;d.QY=!0;d.JY=!0;d.vL(Z2a);d.JA=b;d.qL(c);z.jX(d,!0);this.Fc=d;this.Fc.ua();a=X7(this.aI);this.za("set-active-highlight",this.Ne,a)}this.Zj&&(this.b2(),this.Kf&&this.Kf.focus());Y7(this,0)};
z.f.Ca=function(){this.Qq&&this.Qq.Y3();(this.Zj||this.aI)&&this.za("reset-highlight",this.Ne,null);V7.xa.Ca.call(this)};z.f.Db=function(){z.Qy(this.oa());z.Dh(this.oa());z.lo(this.Fc);z.lo(this.Kf);z.lo(this.Qq);z.mo(z.ob(this.ak));this.Qq=this.ak=this.Kf=this.Fc=null;V7.xa.Db.call(this)};z.f.eo=function(){if(this.Kf&&this.Kf.cb())return!0;for(var a=z.ob(this.ak),b=0;b<a.length;b++)if(a[b]&&a[b].cb())return!0;return this.Fc&&!this.Fc.isDismissable()?!0:!1};
z.f.Jq=function(){var a=[],b=[],c=[],d=this.XA&&(this.Zj||this.aI);d||(this.uw?(a=this.ue?s7(this.ue,this.uw.quotes):[],b=this.uw.notes,c=this.uw.responses):(b=this.uf?z.UD(K7(this.uf,this.Ne)):[],this.q0||(this.ue?(a=this.ue,a=s7(a,a.Rt[this.Ne]||[])):a=[],c=this.wj?y7(this.wj,this.Ne):[])));return z.nx(L3a,{post:this.fb.Ya(),quotes:a,notes:b,responses:c,F8:!!this.m1,xV:d,zL:this.XA,aE:this.$ea,EHa:z.TF(this.fb)})};
z.f.Nva=function(){var a=this.query(".js-postList"),b=z.nx(K3a,{responses:y7(this.wj,this.Ne)});z.Eh(b,a);O3a(this)};
z.f.b2=function(){if(this.XA){if(!this.Kf){var a=this.query(".js-noteEditor"),b=z.mx(I3a),a=this.Kf=new S7(this.ra,a,this.fb.Oa(),null,b),b=this.Ne,c=this.fb.Yi(this.jf.get(this.Ne)),d=c.Ha(),c=4==c.type?c.ze():null;a.KX=b;a.S$=d;a.LX=c;(a=this.Zj)&&this.Kf.Sy(a);z.my(this,this.Kf,"saving",this.vwa,this);z.my(this,this.Kf,"fail",this.nva,this);z.my(this,this.Kf,"save",this.pwa,this)}z.Id(this.query(".js-noteActions"),"is-noteEditorVisible");this.Kf&&this.Kf.focus()}};z.f.uza=function(){this.Kf&&this.Kf.save()};
z.f.vwa=function(a){this.Kf.hd("");var b=this.query(".js-notesList");a={note:a,post:this.fb.Ya(),xV:this.XA,zL:this.XA};a=z.nx(U7,a);b.appendChild(a);z.Pd(b,"is-empty");P3a(this);this.f_()};z.f.pwa=function(a){var b=this.query(".js-notesList").lastChild;a=a.sg();z.Id(b,"js-note-"+a);b.setAttribute("data-note-id",a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};z.f.nva=function(){var a=this.query(".js-notesList");a.removeChild(a.lastChild);z.Id(a,"is-empty");this.b2()};
z.f.f_=function(a){a?this.za("close"):this.Kf&&(this.Kf.cb()&&this.Kf.hd(""),z.Pd(this.query(".js-noteActions"),"is-noteEditorVisible"))};z.f.OAa=function(a){(a=W7(a.target))&&this.XA&&Q3a(this,a)};z.f.vza=function(a){a=W7(a.target);(a=this.ak[a])&&a.save()};
z.f.wwa=function(a){var b=a.sg();this.ak[b]&&this.ak[b].hd("");var c=this.uf.Kp(b,this.Ne).author.userId==a.author.userId,d=this.query(".js-note-"+a.sg()+" .js-repliesList");a={note:a,post:this.fb.Ya(),ria:c};a=z.nx(U7,a);d.appendChild(a);z.Pd(d,"is-empty");R3a(this,b)};z.f.qwa=function(a){var b=this.query(".js-note-"+a.sg()).querySelector(".js-repliesList").lastChild;a=a.Yx();z.Id(b,"js-reply-"+a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};
z.f.ova=function(a){var b=this.query(".js-note-"+a.sg()+" .js-repliesList");b.removeChild(b.lastChild);z.Id(b,"is-empty");Q3a(this,a.sg())};z.f.Usa=function(a){(a=W7(a.target))&&R3a(this,a)};z.f.Xsa=function(a){a=a.target;var b=a.getAttribute("data-quote-creator-id"),c=Q7(this.jf,this.Ne);c&&(this.Qq&&this.Qq.Y3(),this.Qq=T3a(this,c,a,function(){S3a(this,b,!1);z.lo(this.Qq);this.Qq=null}),S3a(this,b,!0))};
z.f.Wsa=function(a){var b=Q7(this.jf,this.Ne);(a=this.uf.Kp(a.target.getAttribute("data-note-id"),this.Ne))&&b&&(b=(b=a.tC())?this.uf.VS(b):null,this.za("set-active-highlight",this.Ne,b))};z.f.Ysa=function(a){var b=Q7(this.jf,this.Ne),c;c=this.wj;a=a.target.getAttribute("data-post-id");c=r7(c)?z.mO(r7(c),a):null;b&&c&&(b=w7(c))&&(b=x7(b)&&x7(b).Zn())&&(c=b.gc())&&c.length&&(b=X7(b),this.za("set-active-highlight",this.Ne,b))};
z.f.G2=function(){var a=null;this.aI&&(a=X7(this.aI));this.Zj&&(a=this.Zj);this.za("reset-highlight",this.Ne,a)};
z.f.Faa=function(a,b){b=b.value;var c=this.uf.Kp(b,this.Ne),d=this.query(".js-note-"+b);if(c&&d){z.Tt(d);this.G2();this.qb(".js-note-item").every(function(a){return z.Hd(a,"u-hide")})&&this.f_(!0);var e=L7(this.uf,c,"HIDDEN");z.v(e.Al,function(b){this.ya.ua(a?C3a():D3a(),"error");e.dL();z.Ut(d);(400>b.status||499<b.status)&&L7(this.uf,c,"NEW")},this);z.t(this.ya.ua(a?F3a():G3a(),{type:"success",bE:!0}),function(){this.ya.Sc();e.dL();L7(this.uf,c,"NEW");z.Ut(d)},this)}};
z.f.Kqa=function(a){var b=a.value,c=this.query(".js-reply-"+b),d=W7(a.target);if(d&&c){z.Tt(c);var e=M7(this.uf,b,d,this.fb.Oa(),this.Ne,"HIDDEN");z.v(e.Al,function(){this.ya.ua(E3a(),"error");e.dL();z.Ut(c);M7(this.uf,b,d,this.fb.Oa(),this.Ne,"")},this);z.t(this.ya.ua(H3a(),{type:"success",bE:!0}),function(){this.ya.Sc();e.dL();M7(this.uf,b,d,this.fb.Oa(),this.Ne,"");z.Ut(c)},this)}};z.f.cya=function(){Y7(this,this.aP-1)};z.f.yua=function(){Y7(this,this.aP+1)};z.q(Z7,z.Q);z.f=Z7.prototype;z.f.na=function(){Z7.xa.na.call(this);var a=[];z.TF(this.fb)&&a.push(this.uf.load(this.nb));this.dca||(a.push(this.ue.load(this.nb)),a.push(this.wj.load(this.nb)));this.aw=z.t(z.t(z.t(z.jS(a),function(){this.aw=null},this),this.qs,this),this.Hpa,this);z.my(this,this.Bb,"resize-end",this.Rf,this)};z.f.Ca=function(){this.aw&&this.aw.cancel();Z7.xa.Ca.call(this)};z.f.Db=function(){this.aw=null;Z7.xa.Db.call(this)};z.f.qs=function(){z3a(this.jf,function(a,b){$7(this,b)},this)};
z.f.Rf=function(){z3a(this.jf,function(a,b){$3a(this,b)},this)};z.f.Hpa=function(){var a=this.ue.kp;z.my(this,a,"add",this.eda,this);z.my(this,a,"remove",this.eda,this);(a=r7(this.wj))&&z.my(this,a,"add",this.mwa,this)};z.f.eda=function(a){U3a(this,Object.keys(z.Cta(this.ue,a instanceof Array?a:[a])))};z.f.mwa=function(a){U3a(this,(a instanceof Array?a:[a]).map(this.wj.O4,this.wj))};z.f.Jq=function(a){var b=window.document.createElement("div");b.className="notesMarkers";a.appendChild(b);return b};
z.f.sH=function(a,b){z.Ab(a,{startIndex:Math.min(a.startIndex,b.startIndex),endIndex:Math.max(a.endIndex,b.endIndex),notes:a.notes.concat(b.notes),quotes:a.quotes.concat(b.quotes),responses:a.responses.concat(b.responses)})};z.q(a8,z.Q);z.f=a8.prototype;
z.f.na=function(){a8.xa.na.call(this);this.Sa(this.Pa.oa(),"click",this.$ta,this,!0);z.T(this.qH).ba("select-anchor",this.Cwa,this);var a=this.fb.Ya();if(a.Ir()&&!this.fb.Mb()){var b=z.Fr(a),b=2==a.visibility&&b&&!z.J(b.Kl(),"memberOfMembershipPlanId");a.allowResponses&&!b&&z.v(this.wj.load(this.fb.Oa(),"best"),z.gy);z.v(this.ue.load(this.fb.Oa()),z.gy)}a.Kl().GJ()&&(this.SP=z.t(this.uf.load(this.fb.Oa()),this.Rva,this));this.T_&&c8(this,null);z.my(this,this.tb,"historyUpdate",function(){c8(this,
z.IF())},this);this.Pe&&z.my(this,this.Pe,"highlight",this.Pva,this)};z.f.Db=function(){z.lo(this.Hh);this.Hh=null;z.lo(this.dm);this.dm=null;this.qH&&z.T(this.qH).clear("select-anchor");this.SP&&this.SP.cancel();this.SP=null;a8.xa.Db.call(this)};z.f.KHa=function(a,b){b8(this,b,null,null,a)};z.f.EJa=function(){this.Hh&&this.Hh.Rf()};z.f.eo=function(){if(!this.dm)return!1;var a=this.dm.cb();return a?a.eo():!1};z.f.Mva=function(a){a.subscribe("add",this.ifa,this);a.subscribe("remove",this.ifa,this)};
z.f.ifa=function(a){(z.oa(a)?a:[a]).forEach(function(a){$7(this.Hh,a.oe())},this)};z.f.Rva=function(){var a=(0,z.Ka)();this.SP=null;c8(this,z.IF());this.Sa(this.em,z.cJ,this.F0,this);z.Yz(z.VCa,(0,z.Ka)()-a)};z.f.F0=function(a){(a=a.target.getAttribute("name"))&&Q7(this.jf,a)&&$3a(this.Hh,a)};z.f.Pva=function(){if(this.Pe){var a=f4a(this,this.Pe.ix);z.zF(this.Pe);a&&(a=a.highlight,this.iea(a.anchor,a),b8(this,a.anchor,a))}};
z.f.$ta=function(a){if(this.dm){var b=a.target;if(!z.Kh(this.dm.oa(),b)){var c=this.dm.cb(),d;if(!(d=!c)){a:if(c.Kf&&c.Kf.cb())c=!0;else{d=z.ob(c.ak);for(var e=0;e<d.length;e++)if(d[e]&&d[e].cb()){c=!0;break a}c=c.Fc&&!c.Fc.cj()?!0:!1}d=!c}d&&(c=this.dm&&this.dm.Fn,d="select-anchor"==b.getAttribute("data-action"),this.u1(),c&&d&&z.Kh(c,b)&&a.stopPropagation())}}};
z.f.zn=function(a){if(!z.rx()){var b=a.Fn,c=z.Lx(b);a.Fl();a=a.oa();var d=z.Lx(a),e=window.innerHeight,g=window.innerWidth,k=this.Pa.query(".js-metabar"),l=0;k&&(l=z.Lx(k).height);d.height>=e-l?m3a(a):(z.Hx(b),b=c.top+d.height>=e?z.Ix().top+e-d.height-10:z.Hx(b),c=z.Lx(this.qH).left+10,c+d.width>=g&&(c=g-d.width-10),a.style.top=b+"px",a.style.left=c+"px")}};z.f.u1=function(){z.lo(this.dm);this.dm=null};
z.f.Cwa=function(a){var b=z.Ot(a.target,function(a){return z.Hd(a,"js-paragraphControl")},this.nda),b=a4a(this.Hh,a.value,b);b8(this,a.value,null,null,null,b)};z.f.iea=function(a,b){if(this.fb.Mb()){var c=z.tp();this.JQ=(c=c&&A3a(this.jf,c.Pf()))&&new B7(c)}e4a(this,a,b)};z.f.cza=function(a,b){e4a(this,a,b);this.fb.Mb()&&this.JQ&&(a=this.JQ.restore())&&a.select();this.JQ=null};
z.f.Vw=function(a){if(this.jf&&(a=Q7(this.jf,a))){a=Math.max(z.Hx(a),0);var b=window.document.body;this.ah&&this.ah.cancel();this.ah=new z.$p(b,"scrollTop",600,a)}};g4a.prototype.jS=function(a,b,c){return new a8(a,b,c)};z.m(d8,z.Q);z.f=d8.prototype;z.f.Lc=function(a){this.va=a};z.f.vL=function(a){this.Mh=a};z.f.LIa=function(a){this.W1=a};z.f.MIa=function(a){this.wea=a};
z.f.na=function(){this.oa()?(z.Q.prototype.na.call(this),z.T(this.oa()).ba("show-responses-stream-editor",this.Nwa,this).ba("show-other-responses",this.Cea,this),z.lx(this.oa(),this.Mh,{post:this.va}),this.va.Ir()&&z.v(z.t(z.t(z.t(V2a(this.kb,this.va.Ab(),"best"),this.Rda.bind(this,"best")),this.Kya,this),function(){this.R2.d8&&this.Cea()},this),z.gy)):z.gy("Attempted to initialize ResponsesStreamControl without root element.")};z.f.Ca=function(){z.T(this.oa()).clear("show-other-responses");z.Q.prototype.Ca.call(this)};
z.f.Rda=function(a,b){this.isActive()&&(b=b.Me,"best"==a?(a=this.query(".js-responsesStream"),z.my(this,b,"add",this.Hca.bind(this,b)),this.Hca(b)):a=this.query(".js-responsesStreamOther"),b&&(z.$r()||0<b.Ke())&&a&&(z.lx(a,z.VQ,{items:z.UD(b),context:2}),b=new z.VS(this.ra,b),b.Wa(a),b.Ed(2),this.track(b),z.Ut(this.query(".js-responsesStreamWrapper"))),this.wea&&(a=z.Hx(a),z.Ex(window.document.body,0,a)))};
z.f.Kya=function(){var a=this.query(".js-inlineNewPostControl"),b=this.query(".js-responsesLoggedOutPrompt");z.$r()?a?(this.Fc=z.jX(P2a((new z.iX(this.ra)).mL("web-inline-post-response").qL(this.va.Ab()),z.kx(z.Wj,{post:this.va,kV:!0})),this.W1).Wa(a),this.track(this.Fc)):b&&this.W1&&(a=z.Gx(b),b=z.Hx(b),z.Ex(a,0,b)):b&&z.Id(b,"u-hide")};
z.f.Cea=function(){this.J0||(this.J0=z.od(z.t(z.t(V2a(this.kb,this.va.Ab(),"other"),this.Rda.bind(this,"other")),function(){z.Tt(this.query(".js-showOtherResponses"));this.R2.d8=!0},this),function(){this.J0=null},this))};z.f.Hca=function(a){(a=a.bl)&&a.next&&"other"==a.next.filter&&!this.R2.d8&&(z.Ut(this.query(".js-responsesStreamWrapper")),z.Ut(this.query(".js-showOtherResponses")))};z.f.Lx=function(){this.Fc&&(z.XR(this.Fc.oa(),new z.zp(60,0,200,0)),this.Fc.Lx())};
z.f.Nwa=function(){var a=this.query(".js-responsesStreamEditor"),b=this.query(".js-showResponsesStreamEditorButton");z.Vt(a)&&(z.Ut(a),z.Tt(b),this.Lx())};z.q(e8,z.ky);e8.prototype.focus=function(){this.isActive&&this.hz.focus()};e8.prototype.close=function(){this.hz&&!this.hz.closed&&this.hz.close();this.za("close");this.$f()};e8.prototype.isActive=function(){return this.hz?!this.hz.closed:!1};e8.prototype.Va=function(){this.hz=null;e8.xa.Va.call(this)};z.f=i4a.prototype;z.f.PD=function(a,b,c){var d;d=z.ho;var e=new z.Vj(z.eo(d)),e=new z.Je(e.vl(a));d=D7(e,d);this.Dw(d);z.Jy(z.MJ,{postId:a.id,type:b,source:c,dest:"facebook",dialogType:"native"})};z.f.W7=function(a){var b;b=z.ho;var c=new z.Vj(z.eo(b));a=new z.Je(c.la(z.Gw,{catalogSlug:a.Je(),username:a.Gf().wk()}));b=D7(a,b);this.Dw(b)};z.f.X7=function(a){var b;b=z.ho;var c=new z.Vj(z.eo(b));a=new z.Je(c.la(z.xw,{sequenceSlug:a.sd()}));b=D7(a,b);this.Dw(b)};
z.f.J4=function(){var a=this.ma.la(z.hAa);return this.pa.get(a)};z.f.Dw=function(a){h4a(a,"facebook-share",{width:550,height:320})};z.q(f8,z.jo);
f8.prototype.open=function(a,b){this.va=a;this.lx=b;this.Da=this.bG.open({bodyHtml:z.kx(r3a,this.lx),type:"tweet"},!0);a=this.Da.query(".js-tweetEditor-text");b=this.ra;var c=String,d;d=z.n("Enter tweet text.");d=(0,z.y)(""+d);this.aJ=new z.VX(b,a,c(d),!0);a=new z.PW(280,!0);a.taa=A7;this.aJ.$a(a);a=a3a(n3a,this.lx,z.ho);this.aJ.hd(a);this.aJ.focus();k4a(this);z.T(this.Da.Zb).ba("remove-textshot",this.nea.bind(this,!1),this).ba("add-textshot",this.nea.bind(this,!0),this).ba("toggle-expand-image",this.GBa,
this);this.Da.subscribe(z.yA,this.tCa.bind(this))};f8.prototype.tCa=function(){var a=this.aJ.cb();if(l4a(this,a)){var b=this.fP?j4a(this):null;z.v(z.t(this.pa.post(this.ma.la(z.fAa),{tweet:a,textshotInfo:b}),function(a){a=z.mx(p3a,{id:a.value});a=z.kx(t3a,{yJa:a});this.ya.ua(a,{type:"success",Bo:1E4})},this),function(a){z.gy(a);this.ya.ua(s3a(),"error")},this);z.Sz(z.LCa,{postId:this.va.id,type:this.lx.shareType,source:this.lx.QIa,dest:"twitter",style:this.fP?"textshot":null});this.Da.close()}};
f8.prototype.nea=function(a){this.fP=a;z.Xd(this.Da.query(".js-tweetEditor-imageContainer"),"u-hide",!a);z.Xd(this.Da.query(".js-tweetEditor-addTextshot"),"u-hide",a)};f8.prototype.GBa=function(){var a=this.Da.query(".js-tweetEditor-image");z.Yd(a,"tweetEditor-image--expanded")};z.f=m4a.prototype;z.f.PIa=function(a,b){var c=z.Xr(),d=a.creator||{},e=U2a(b),g=T2a(b),k=b3a(a,z.ho);(b=v3a(b.L4()))&&z.Ye(k,b||"");var l={name:d.name||"",username:d.username||"",twitterScreenName:d.twitterScreenName||"",url:k.toString(),content:a.title,user:c,pJa:e,oJa:g,shareType:"highlight",QIa:"highlight_menu"};z.v(z.t(this.ra.load("tweet-dialog"),function(b){b.open(a,l)}),z.gy);z.Sz(z.MJ,{postId:a.id,type:"highlight",source:"highlight_menu",dest:"twitter",dialogType:"inapp"});return!0};
z.f.PD=function(a,b,c,d,e){var g=z.Xr().userId,k="highlight"==c?n3a:z.fia,l=z.ho,p=a.creator||{};b={content:b,name:p.name||"",username:p.username||"",twitterScreenName:p.twitterScreenName||"",Qfa:p.userId==g,url:b3a(a,l).toString(),collaborators:d||[]};d=d&&d.length?String(k(b,null,l)):a3a(k,b,l);k=new z.Je("https://twitter.com/intent/tweet");z.bf(k,"text",d);this.Dw(k);z.Jy(z.MJ,{postId:a.id,type:c,source:e,dest:"twitter",dialogType:"native"})};
z.f.W7=function(a){var b=z.ho,c=new z.Vj(z.eo(b)),c=(new z.Je(c.la(z.Gw,{catalogSlug:a.Je(),username:a.Gf().wk()}))).toString();a=z.B(""+z.Sm(String(a.name))+((null==a.creator?null:a.creator.userId)!=b.currentUser.userId?" — "+z.Ft({twitterScreenName:null==a.creator?null:a.creator.twitterScreenName,name:null==a.creator?null:a.creator.name}):"")+" "+(""+c));b=new z.Je("https://twitter.com/intent/tweet");z.bf(b,"text",a);this.Dw(b)};
z.f.X7=function(a){var b=new z.Vj(z.eo(z.ho)),b=(new z.Je(b.la(z.xw,{sequenceSlug:a.sd()}))).toString();a=z.B(""+z.Sm(String(a.title))+" "+(""+b));b=new z.Je("https://twitter.com/intent/tweet");z.bf(b,"text",a);this.Dw(b)};z.f.Dw=function(a){h4a(a,"twitter-share",{width:670,height:420})};var r4a=z.dz,s4a=r4a.Fa();z.gz(s4a.scope("screen").add("quotes",P7).add("quote-responses",g4a).add("responses-stream-control",d8).add("notes-data",J7),"PostMeterBar",O7);z.gz(s4a.scope("app"),"PlacementsControl",N7).add("twitter",m4a).add("facebook",i4a).add("tweet-dialog",f8);z.nO(r4a,"notes");}).call(this, _mdm);
