(function(g){var window=this;var Sfa=function(a,b){return g.ac(a,b)},Tfa=function(a){if(a.Vb&&"function"==typeof a.Vb)return a.Vb();
if(g.w(a))return a.split("");if(g.Aa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Xb(a)},Ufa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Aa(a)||g.w(a))(0,g.G)(a,b,void 0);else{if(a.jd&&"function"==typeof a.jd)var c=a.jd();else if(a.Vb&&"function"==typeof a.Vb)c=void 0;else if(g.Aa(a)||g.w(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Yb(a);d=Tfa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},o4=function(a){g.to(a,"zx",g.Ib());
return a},p4=function(a,b,c){g.za(c)||(c=[String(c)]);
g.zo(a.o,b,c)},q4=function(){},r4=function(a){if(!a.l&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},s4=function(a){var b;
(b=a.g)||(b={},r4(a)&&(b[0]=!0,b[1]=!0),b=a.g=b);return b},t4=function(a){return(a=r4(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},u4=function(a,b){return b+" ["+a.X+" "+a.I+" "+a.getStatus()+"]"},Vfa=function(a){return"content-type"==a.toLowerCase()},v4=function(a){a.g&&a.L&&(a.g.ontimeout=null);
a.F&&(g.x.clearTimeout(a.F),a.F=null)},Wfa=function(a){return g.qd&&g.wc(9)&&g.va(a.timeout)&&g.t(a.ontimeout)},w4=function(a){a.R||(a.R=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},x4=function(a,b){if(a.g){v4(a);
var c=a.g,d=a.P[0]?g.wa:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},y4=function(a,b){a.l=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.B=b;a.A=5;w4(a);x4(a)},z4=function(a){return a.g?a.g.readyState:0},A4=function(a){if(a.l&&"undefined"!=typeof g.DW)if(a.P[1]&&4==z4(a)&&2==a.getStatus())u4(a,"Local request error detected and ignored");
else if(a.H&&4==z4(a))g.gg(a.qr,0,a);else if(a.dispatchEvent("readystatechange"),4==z4(a)){u4(a,"Request complete");a.l=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.yg(String(a.I))[1]||null;if(!f&&g.x.self&&g.x.self.location){var k=g.x.self.location.protocol;f=k.substr(0,k.length-1)}e=!Xfa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.A=6;try{var l=2<z4(a)?a.g.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";w4(a)}}finally{x4(a)}}},B4=function(a){g.lf.call(this);
this.headers=new g.go;this.U=a||null;this.l=!1;this.P=this.g=null;this.X=this.I="";this.A=0;this.B="";this.o=this.aa=this.H=this.R=!1;this.C=0;this.F=null;this.ba="";this.L=this.V=!1},C4=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},D4=function(){this.g=[];
this.l=[]},Yfa=function(a,b){var c=[];
g.Mk(b,function(a){try{var b=g.sq.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.rq(b)&&c.push(a):c.push(a)},a);
return c},Zfa=function(a,b){var c=Yfa(a,b);
(0,g.G)(c,function(a){g.sq.prototype.remove.call(this,a)},a)},$fa=function(){var a=g.pu;
Zfa(a,a.g.Me(!0))},aga=function(a,b,c,d){var e=new g.jo(null,void 0);
a&&g.ko(e,a);b&&g.lo(e,b);c&&g.mo(e,c);d&&(e.l=d);return e},E4=function(a){g.ut[a]&&(a=g.ut[a],(0,g.G)(a,function(a){g.rt[a]&&delete g.rt[a]}),a.length=0)},cga=function(a){var b=g.qt();
if(b)if(b.clear(a),a)E4(a);else for(var c in g.ut)E4(c)},F4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.go;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",dga(this,a.capabilities||""),ega(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},dga=function(a,b){a.capabilities.clear();
(0,g.Gd)(b.split(","),g.B(Sfa,fga)).forEach(function(b){a.capabilities.add(b)})},ega=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},G4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},H4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},I4=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},gga=function(a){return new G4(a)},J4=function(a){return g.za(a)?(0,g.I)(a,gga):[]},K4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},L4=function(a){return g.za(a)?"["+(0,g.I)(a,K4).join(",")+"]":"null"},M4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},hga=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},N4=function(a,b){return g.Pa(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},O4=function(a,b){return g.Pa(a,function(a){return H4(a,b)})},P4=function(){var a=g.tu("yt-remote-connected-devices")||[];
g.kb(a);return a},iga=function(a){if(g.Ua(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},Q4=function(a){g.ru("yt-remote-connected-devices",a,86400)},S4=function(){if(R4)return R4;
var a=g.tu("yt-remote-device-id");a||(a=M4(),g.ru("yt-remote-device-id",a,31536E3));for(var b=P4(),c=1,d=a;g.Ta(b,d);)c++,d=a+"#"+c;return R4=d},T4=function(){var a=P4(),b=S4();
g.Ta(a,b);if(g.yu()){var c=a,d=g.ib(c,b,void 0);0>d&&g.eb(c,-(d+1),0,b)}a=iga(a);if(g.Ua(a))try{g.wu.remove("remote_sid","/","youtube.com")}catch(e){}else try{g.xu("remote_sid",a.join(","),-1)}catch(e){}},U4=function(){return g.tu("yt-remote-session-browser-channel")},V4=function(){return g.tu("yt-remote-local-screens")||[]},W4=function(){g.ru("yt-remote-lounge-token-expiration",!0,86400)},jga=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(V4(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.Kn)(c,function(a){return!g.Ta(b,a)})&&W4();
g.ru("yt-remote-local-screens",a,31536E3)},kga=function(a,b){g.ru("yt-remote-session-browser-channel",a);
g.ru("yt-remote-session-screen-id",b);var c=P4(),d=S4();g.Ta(c,d)||c.push(d);Q4(c);T4()},X4=function(a){a||(g.uu("yt-remote-session-screen-id"),g.uu("yt-remote-session-video-id"));
T4();a=P4();g.Ya(a,S4());Q4(a)},Z4=function(){if(!Y4){var a=g.zq();
a&&(Y4=new g.mq(a))}return Y4?!!Y4.get("yt-remote-use-staging-server"):!1},lga=function(){var a=window.document.createElement("a");
g.Sc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Mb(a)},mga=function(a,b){var c=g.zd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Tc(c,g.Vd("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},nga=function(){var a=lga(),b=window.document.getElementById(a),c=b&&g.Cs(b,"loaded");
c||b&&!c||(b=mga(a,function(){g.Cs(b,"loaded")||(g.Bs(b,"loaded","true"),g.zt(a),g.or(g.B(cga,a),0))}))},$4=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},a5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},c5=function(a){a.length?b5(a.shift(),function(){c5(a)}):d5()},oga=function(a){return"chrome-extension://"+a+e5},b5=function(a,b,c){var d=
window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},f5=function(a){return 0<=window.navigator.userAgent.indexOf(a)},d5=function(){var a=a5();
a&&a(!1,"No cast extension found")},g5=function(){if(pga){var a=2,b=a5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;b5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",d5,c)}},qga=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(g5(),a({command:"cast.sender.init"}))},rga=function(){g5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);c5(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+e5,"//www.gstatic.com/eureka/clank"+e5])},h5=function(a,b,c){g.J.call(this);
this.C=null!=c?(0,g.A)(a,c):a;this.Hb=b;this.B=(0,g.A)(this.Wy,this);this.g=!1;this.l=0;this.o=this.xa=null;this.A=[]},i5=function(){},j5=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.C=d||1;this.A=45E3;this.da=new g.Ao(this);this.l=new g.fg;this.l.setInterval(250)},l5=function(a,b,c){a.ih=1;
a.Ff=o4(b.clone());a.Mg=c;a.B=!0;k5(a,null)},m5=function(a,b,c,d,e){a.ih=1;
a.Ff=o4(b.clone());a.Mg=null;a.B=c;e&&(a.Av=!1);k5(a,d)},k5=function(a,b){a.yh=(0,g.H)();
n5(a);a.Wf=a.Ff.clone();p4(a.Wf,"t",a.C);a.dj=0;a.Zb=a.g.nm(a.g.Xi()?b:null);0<a.Nm&&(a.dl=new g.Hl((0,g.A)(a.Fw,a,a.Zb),a.Nm));a.da.ea(a.Zb,"readystatechange",a.gI);var c=a.tg?g.hc(a.tg):{};a.Mg?(a.El="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Zb.send(a.Wf,a.El,a.Mg,c)):(a.El="GET",a.Av&&!g.sd&&(c.Connection="close"),a.Zb.send(a.Wf,a.El,null,c));a.g.ee(1)},u5=function(a,b,c){for(var d=!0;!a.jg&&a.dj<c.length;){var e=sga(a,c);
if(e==o5){4==b&&(a.Gf=4,p5(15),d=!1);break}else if(e==q5){a.Gf=4;p5(16);d=!1;break}else r5(a,e)}4==b&&0==c.length&&(a.Gf=1,p5(17),d=!1);a.ge=a.ge&&d;d||(s5(a),t5(a))},sga=function(a,b){var c=a.dj,d=b.indexOf("\n",c);
if(-1==d)return o5;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return q5;d+=1;if(d+c>b.length)return o5;var e=b.substr(d,c);a.dj=d+c;return e},x5=function(a,b){a.yh=(0,g.H)();
n5(a);var c=b?window.location.hostname:"";a.Wf=a.Ff.clone();g.to(a.Wf,"DOMAIN",c);g.to(a.Wf,"t",a.C);try{a.he=new window.ActiveXObject("htmlfile")}catch(n){s5(a);a.Gf=7;p5(22);t5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in v5)k=v5[l];else if(l in w5)k=v5[l]=w5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
v5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Uc(g.Cc("b/12014412"),d);a.he.open();a.he.write(g.Qc(c));a.he.close();a.he.parentWindow.m=(0,g.A)(a.yH,a);a.he.parentWindow.d=(0,g.A)(a.Mu,a,!0);a.he.parentWindow.rpcClose=(0,g.A)(a.Mu,a,!1);c=a.he.createElement("DIV");a.he.parentWindow.document.body.appendChild(c);d=g.Mc(a.Wf.toString());d=g.Cb(g.Jc(d));d=g.Uc(g.Cc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Qc(d);a.g.ee(1)},n5=function(a){a.wp=
(0,g.H)()+a.A;
y5(a,a.A)},y5=function(a,b){if(null!=a.Lh)throw Error("WatchDog timer not null");
a.Lh=z5((0,g.A)(a.IH,a),b)},A5=function(a){a.Lh&&(g.x.clearTimeout(a.Lh),a.Lh=null)},t5=function(a){a.g.mr()||a.jg||a.g.Sk(a)},s5=function(a){A5(a);
g.Ee(a.dl);a.dl=null;a.l.stop();g.Co(a.da);if(a.Zb){var b=a.Zb;a.Zb=null;b.abort();b.dispose()}a.he&&(a.he=null)},r5=function(a,b){try{a.g.Gu(a,b),a.g.ee(4)}catch(c){}},C5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;B5(a,b,function(e){e?c(!0):g.x.setTimeout(function(){C5(a,b,c,d,f)},f)})}},B5=function(a,b,c){var d=new window.Image;
d.onload=function(){try{D5(d),c(!0)}catch(e){}};
d.onerror=function(){try{D5(d),c(!1)}catch(e){}};
d.onabort=function(){try{D5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{D5(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},D5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},E5=function(a){this.g=a;
this.l=new i5},G5=function(a){var b=F5(a.g,a.Ph,"/mail/images/cleardot.gif");
o4(b);C5(b.toString(),5E3,(0,g.A)(a.ty,a),3,2E3);a.ee(1)},I5=function(a){var b=a.g.I;
if(null!=b)p5(5),b?(p5(11),H5(a.g,a,!1)):(p5(12),H5(a.g,a,!0));else if(a.sd=new j5(a,void 0,void 0,void 0),a.sd.tg=a.Km,b=a.g,b=F5(b,b.Xi()?a.li:null,a.Mm),p5(5),!g.qd||g.yc(10))p4(b,"TYPE","xmlhttp"),m5(a.sd,b,!1,a.li,!1);else{p4(b,"TYPE","html");var c=a.sd;a=!!a.li;c.ih=3;c.Ff=o4(b.clone());x5(c,a)}},J5=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new i5;this.H=a||null;this.I=null!=b?b:null;this.C=c||!1},tga=function(a,b){this.g=a;
this.map=b;this.context=null},K5=function(a){g.Ge.call(this,"statevent",a)},L5=function(a,b){g.Ge.call(this,"timingevent",a);
this.size=b},M5=function(a){g.Ge.call(this,"serverreachability",a)},Q5=function(a){N5(a);
if(3==a.g){var b=a.Mi++,c=a.ak.clone();g.to(c,"SID",a.o);g.to(c,"RID",b);g.to(c,"TYPE","terminate");O5(a,c);b=new j5(a,a.o,b,void 0);b.ih=2;b.Ff=o4(c.clone());(new window.Image).src=b.Ff;b.yh=(0,g.H)();n5(b)}P5(a)},S5=function(a){a.Fy(1,0);
a.ak=F5(a,null,a.Jm);R5(a)},N5=function(a){a.wf&&(a.wf.abort(),a.wf=null);
a.Gb&&(a.Gb.cancel(),a.Gb=null);a.Oe&&(g.x.clearTimeout(a.Oe),a.Oe=null);T5(a);a.Xc&&(a.Xc.cancel(),a.Xc=null);a.zf&&(g.x.clearTimeout(a.zf),a.zf=null)},U5=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new tga(a.ZD++,b));2!=a.g&&3!=a.g||R5(a)},R5=function(a){a.Xc||a.zf||(a.zf=z5((0,g.A)(a.Ku,a),0),a.eh=0)},X5=function(a,b){if(1==a.g){if(!b){a.Mi=Math.floor(1E5*Math.random());
var c=a.Mi++,d=new j5(a,"",c,void 0);d.tg=null;var e=V5(a),f=a.ak.clone();g.to(f,"RID",c);g.to(f,"CVER","1");O5(a,f);l5(d,f,e);a.Xc=d;a.g=2}}else 3==a.g&&(b?W5(a,b):0==a.l.length||a.Xc||W5(a))},W5=function(a,b){if(b)if(6<a.kg){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.Mi-1;var d=V5(a)}else c=b.F,d=b.Mg;else c=a.Mi++,d=V5(a);var e=a.ak.clone();g.to(e,"SID",a.o);g.to(e,"RID",c);g.to(e,"AID",a.mh);O5(a,e);c=new j5(a,a.o,c,a.eh+1);c.tg=null;c.setTimeout(Math.round(1E4)+Math.round(1E4*Math.random()));a.Xc=c;l5(c,e,d)},O5=function(a,b){if(a.yc){var c=a.yc.Vq();
c&&g.Sb(c,function(a,c){g.to(b,c,a)})}},V5=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.kg&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.kg?e:f-d;try{g.Sb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},Y5=function(a){a.Gb||a.Oe||(a.F=1,a.Oe=z5((0,g.A)(a.Ju,a),0),a.Yg=0)},$5=function(a){if(a.Gb||a.Oe||3<=a.Yg)return!1;
a.F++;a.Oe=z5((0,g.A)(a.Ju,a),Z5(a,a.Yg));a.Yg++;return!0},H5=function(a,b,c){a.Dl=c;
a.Wd=b.Ue;a.C||S5(a)},T5=function(a){null!=a.mg&&(g.x.clearTimeout(a.mg),a.mg=null)},Z5=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},b6=function(a,b){if(2==b||9==b){var c=null;
a.yc&&(c=null);var d=(0,g.A)(a.NI,a);c||(c=new g.jo("//www.google.com/images/cleardot.gif"),o4(c));B5(c.toString(),1E4,d)}else p5(2);a6(a,b)},a6=function(a,b){a.g=0;
a.yc&&a.yc.gq(b);P5(a);N5(a)},P5=function(a){a.g=0;
a.Wd=-1;if(a.yc)if(0==a.A.length&&0==a.l.length)a.yc.fm();else{g.bb(a.A);var b=g.bb(a.l);a.A.length=0;a.l.length=0;a.yc.fm(b)}},F5=function(a,b,c){var d=g.uo(c);
if(""!=d.g)b&&g.lo(d,b+"."+d.g),g.mo(d,d.B);else{var e=window.location;d=aga(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Yh&&g.Sb(a.Yh,function(a,b){g.to(d,b,a)});
g.to(d,"VER",a.kg);O5(a,d);return d},z5=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},p5=function(a){c6.dispatchEvent(new K5(c6,a))},d6=function(){},uga=function(a,b){this.action=a;
this.params=b||{}},f6=function(a,b){g.J.call(this);
this.g=new g.P(this.o,0,this);g.K(this,this.g);this.l=this.Hb=0;if(g.Ba(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a;e6(this)},e6=function(a){a.g.stop();
a.Hb=5E3+2E4*Math.random()},g6=function(a,b,c){this.L=a;
this.C=b;this.o=new g.iq;this.l=new f6(this.pJ,this);this.g=this.Ze=null;this.K=!1;this.B=null;this.I="";this.H=this.A=0;this.F=[];this.P=c||!1},vga=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Dl,sessionId:a.g.o,arrayId:a.g.mh}},h6=function(a,b){a.H=b||0;
a.l.stop();a.g&&(3==a.g.g&&X5(a.g),Q5(a.g));a.H=0},i6=function(a){return!!a.g&&3==a.g.g},wga=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},j6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Bg(a)||"";b&&(this.port=":"+b);this.domain=g.Ag(a)||"";a=g.Qb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Lb(a,"10.0")&&(this.l=!1))},k6=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Kg(c+b,{})},l6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,ib:g.B(a.A,d,!0),onError:g.B(a.o,e),Qc:g.B(a.B,e)};c&&(a.jb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Fr(b,a)},xga=function(){var a=m6;
n6();o6.push(a);p6(o6)},q6=function(a,b){n6();
var c=o6,d=yga(a,String(b));g.Ua(c)?zga(d):(p6(c),(0,g.G)(c,function(a){a(d)}))},n6=function(){o6||(o6=g.z("yt.mdx.remote.debug.handlers_")||[],g.y("yt.mdx.remote.debug.handlers_",o6,void 0))},zga=function(a){var b=(r6+1)%50;
r6=b;s6[b]=a;t6||(t6=49==b)},p6=function(a){var b=s6;
if(b[0]){var c=r6,d=t6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.G)(a,function(a){a(e)})}while(d!=c);
s6=Array(50);r6=-1;t6=!1}},yga=function(a,b){var c=((0,g.H)()-Aga)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},u6=function(a){g.R.call(this);
this.F=a;this.g=[]},v6=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Bga=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Gd)(a.g,function(a){return!!N4(b,a)});
for(var d=0,e=b.length;d<e;d++)c=v6(a,b[d])||c;return c},Cga=function(a,b){var c=a.g.length;
a.g=(0,g.Gd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},w6=function(a,b,c,d){g.R.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.xa=window.NaN},y6=function(a){u6.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;x6(this);this.info("Initializing with "+L4(this.g))},z6=function(a){if(a.g.length){var b=(0,g.I)(a.g,function(a){return a.id}),c=k6(a.o,"/pairing/get_lounge_token_batch");
l6(a.o,c,{screen_ids:b.join(",")},(0,g.A)(a.ez,a),(0,g.A)(a.dz,a))}},x6=function(a){var b=J4(V4());
b=(0,g.Gd)(b,function(a){return!a.uuid});
return Bga(a,b)},A6=function(a,b){jga((0,g.I)(a.g,I4));
b&&W4()},C6=function(a,b){g.R.call(this);
this.C=b;var c=g.tu("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ta(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;B6("Initialized with "+g.qg(this.g))},D6=function(a,b,c){var d=k6(a.B,"/pairing/get_screen_availability");
l6(a.B,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},E6=function(a,b){a:if(g.Wb(b)!=g.Wb(a.g))var c=!1;
else{c=g.Yb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(B6("Updated online screens: "+g.qg(a.g)),a.g=b,a.O("screenChange"));Dga(a)},F6=function(a){(0,window.isNaN)(a.o)||g.qr(a.o);
a.o=g.or((0,g.A)(a.No,a),0<a.A&&a.A<(0,g.H)()?2E4:1E4)},B6=function(a){q6("OnlineScreenService",a)},G6=function(a){var b={};
(0,g.G)(a.C(),function(a){a.token?b[a.token]=a.id:this.Cb("Requesting availability of screen w/o lounge token.")});
return b},Dga=function(a){a=g.Yb(g.Tb(a.g,function(a){return a}));
g.kb(a);a.length?g.ru("yt-remote-online-screen-ids",a.join(","),60):g.uu("yt-remote-online-screen-ids")},H6=function(a){u6.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};Ega(this)},J6=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.md();if(k=(c?O4(k,c):null)||O4(k,b)){k.uuid=b;var l=I6(a,k);D6(a.l,l,function(a){e(a?l:null)})}else c?Fga(a,c,(0,g.A)(function(a){var f=I6(this,new G4({name:d,
screenId:c,loungeToken:a,dialId:b||""}));D6(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},K6=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Fga=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={jb:{screen_ids:b},method:"POST",context:a,ib:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Fr(k6(a.C,"/pairing/get_lounge_token_batch"),e)},L6=function(a){a.g=a.o.md();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+L4(a.g))},Ega=function(a){M6(a);
a.o=new y6(a.C);a.o.subscribe("screenChange",(0,g.A)(a.rz,a));L6(a);a.A=J4(g.tu("yt-remote-automatic-screen-cache")||[]);M6(a);a.info("Initializing automatic screens: "+L4(a.A));a.l=new C6(a.C,(0,g.A)(a.md,a,!0));a.l.subscribe("screenChange",(0,g.A)(function(){this.O("onlineScreenChange")},a))},I6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=O4(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.ru("yt-remote-automatic-screen-cache",(0,g.I)(a.A,I4)));M6(a);a.B[b.uuid]=b.id;g.ru("yt-remote-device-id-map",a.B,31536E3);return b},M6=function(a){a.B=g.tu("yt-remote-device-id-map")||{}},N6=function(a,b,c){g.R.call(this);
this.P=c;this.I=a;this.l=b;this.o=null},O6=function(a,b){q6(a.P,b)},Q6=function(a,b){N6.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.A)(this.vJ,this);this.B=(0,g.A)(this.SH,this);this.A=g.or((0,g.A)(function(){P6(this,null)},this),12E4)},Gga=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.qg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.wa,(0,g.A)(function(){O6(this,"Failed to send message: getMdxSessionStatus.")},a)):O6(a,"Sending yt message without session: "+g.qg(b))},P6=function(a,b){g.qr(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.A)(a.Tk,a),d=(0,g.A)(a.qd,a);a.fr(b,c,d,5)}}else a.qd(Error("Waiting for session status timed out."))},R6=function(a,b,c){N6.call(this,a,b,"DialSession");
this.A=this.H=null;this.K="";this.U=c;this.B=null;this.F=g.wa;this.C=window.NaN;this.L=(0,g.A)(this.yJ,this);this.g=g.wa},S6=function(a){a.g=a.I.Lw(a.K,a.l.label,a.l.friendlyName,(0,g.A)(function(a){this.g=g.wa;
this.Tk(a)},a),(0,g.A)(function(a){this.g=g.wa;
this.qd(a)},a))},T6=function(a){var b={};
b.pairingCode=a.K;b.theme=a.U;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}Z4()&&(b.env_useStageMdx=1);return g.Ig(b)},U6=function(a,b){N6.call(this,a,b,"ManualSession");
this.g=g.or((0,g.A)(this.nh,this,null),150)},V6=function(a,b,c,d){g.R.call(this);
this.l=a;this.F=b||"233637DE";this.C=c||"cl";this.H=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.A)(this.KG,this)},W6=function(a,b){return b?g.Pa(a.o,function(a){return H4(b,a.label)},a):null},X6=function(a){q6("Controller",a)},m6=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},Y6=function(a){return a.B||!!a.o.length||!!a.g},Z6=function(a,b,c){b!=a.g&&(g.Ee(a.g),(a.g=b)?(c?a.O("yt-remote-cast2-receiver-resumed",b.l):a.O("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.A)(a.Iu,a,b)),b.o?a.O("yt-remote-cast2-session-change",b.o):c&&a.g.nh(null)):a.O("yt-remote-cast2-session-change",null))},$6=function(a){var b=a.l.Kw(),c=a.g&&a.g.l;
a=(0,g.I)(b,function(a){c&&H4(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=W6(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Kga=function(a,b,c,d,e,f,k){Hga()?Iga(b,e,f,k)&&(b7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?c7(a,c):(window.__onGCastApiAvailable=function(b,d){b?c7(a,c):(d7("Failed to load cast API: "+d),e7(!1),b7(!1),g.uu("yt-remote-cast-available"),g.uu("yt-remote-cast-receiver"),f7(),c(!1))},
d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):nga():f5("CriOS")?qga():f5("Android")&&f5("Chrome/")&&window.navigator.presentation?rga():window.chrome&&window.navigator.presentation&&!f5("Edge")?(g5(),c5(Jga.map(oga))):d5())):a7("Cannot initialize because not running Chrome")},f7=function(){a7("dispose");
var a=g7();a&&a.dispose();g.y("yt.mdx.remote.cloudview.instance_",null,void 0);h7(!1);g.wt(i7);i7.length=0},j7=function(){return!!g.tu("yt-remote-cast-installed")},k7=function(){var a=g.tu("yt-remote-cast-receiver");
return a?a.friendlyName:null},l7=function(){a7("clearCurrentReceiver");
g.uu("yt-remote-cast-receiver")},m7=function(){return j7()?g7()?g7().getCastSession():(d7("getCastSelector: Cast is not initialized."),null):(d7("getCastSelector: Cast API is not installed!"),null)},o7=function(){j7()?g7()?n7()?(a7("Requesting cast selector."),g7().requestSession()):(a7("Wait for cast API to be ready to request the session."),i7.push(g.vt("yt-remote-cast2-api-ready",o7))):d7("requestCastSelector: Cast is not initialized."):d7("requestCastSelector: Cast API is not installed!")},p7=
function(a,b){n7()?g7().setConnectedScreenStatus(a,b):d7("setConnectedScreenStatus called before ready.")},Hga=function(){var a=0<=g.Qb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Px||a},Lga=function(a,b){g7().init(a,b)},Iga=function(a,b,c,d){var e=!1;
g7()||(a=new V6(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.ru("yt-remote-cast-available",a);g.At("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){a7("onReceiverSelected: "+a.friendlyName);
g.ru("yt-remote-cast-receiver",a);g.At("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){a7("onReceiverResumed: "+a.friendlyName);
g.ru("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){a7("onSessionChange: "+K4(a));
a||g.uu("yt-remote-cast-receiver");g.At("yt-remote-cast2-session-change",a)}),g.y("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
a7("cloudview.createSingleton_: "+e);return e},g7=function(){return g.z("yt.mdx.remote.cloudview.instance_")},c7=function(a,b){e7(!0);
b7(!1);Lga(a,function(a){a?(h7(!0),g.zt("yt-remote-cast2-api-ready")):(d7("Failed to initialize cast API."),e7(!1),g.uu("yt-remote-cast-available"),g.uu("yt-remote-cast-receiver"),f7());b(a)})},a7=function(a){q6("cloudview",a)},d7=function(a){q6("cloudview",a)},e7=function(a){a7("setCastInstalled_ "+a);
g.ru("yt-remote-cast-installed",a)},n7=function(){return!!g.z("yt.mdx.remote.cloudview.apiReady_")},h7=function(a){a7("setApiReady_ "+a);
g.y("yt.mdx.remote.cloudview.apiReady_",a,void 0)},b7=function(a){g.y("yt.mdx.remote.cloudview.initializing_",a,void 0)},q7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.F=this.H=0;this.l=null;this.hasNext=this.te=!1;this.K=this.I=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},r7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.te=!1;a.hasNext=!1;a.H=0;a.F=(0,g.H)();a.B=0;a.o=0;a.I=0;a.K=0;a.A=window.NaN;a.C=!1},s7=function(a){return a.gb()?((0,g.H)()-a.F)/1E3:0},t7=function(a,b){a.H=b;
a.F=(0,g.H)()},u7=function(a){switch(a.g){case 1:case 1081:return((0,g.H)()-a.F)/1E3+a.H;
case -1E3:return 0}return a.H},v7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&r7(a)},w7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ic(a.l);b.hasPrevious=a.te;b.hasNext=a.hasNext;b.playerTime=a.H;b.playerTimeAt=a.F;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.I;b.loadedTime=a.K;b.liveIngestionTime=a.A;return b},z7=function(a,b){g.R.call(this);
this.g=0;this.A=a;this.C=[];this.B=new D4;this.o=this.l=null;this.I=(0,g.A)(this.EE,this);this.F=(0,g.A)(this.Ni,this);this.H=(0,g.A)(this.DE,this);this.K=(0,g.A)(this.RE,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.yp,this),x7(this))):c=3;0!=c&&(b?this.yp(c):g.or((0,g.A)(function(){this.yp(c)},this),0));
var d=m7();d&&y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},A7=function(a){return new q7(a.A.getPlayerContextData())},x7=function(a){(0,g.G)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.B(this.HG,a),this))},a)},B7=function(a){(0,g.G)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},C7=function(a,b){50>a.B.Sd()&&a.B.l.push(b)},E7=function(a,b,c){var d=A7(a);
t7(d,c);-1E3!=d.g&&(d.g=b);D7(a,d)},F7=function(a,b,c){a.A.sendMessage(b,c)},D7=function(a,b){B7(a);
a.A.setPlayerContextData(w7(b));x7(a)},y7=function(a,b){a.o&&(a.o.removeUpdateListener(a.I),a.o.removeMediaListener(a.F),a.Ni(null));
a.o=b;a.o&&(q6("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.I),a.o.addMediaListener(a.F),a.o.media.length&&a.Ni(a.o.media[0]))},G7=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=A7(a);b.contentId!=d.videoId&&q6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;t7(d,a.l.getEstimatedTime());D7(a,d)}else q6("CP","No cast media video. Ignoring state update.")},H7=function(a,b,c){return(0,g.A)(function(a){this.Cb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Cb("Retrying "+b+" using MDx browser channel."),F7(this,b,c))},a)},I7=function(a,b,c){g.R.call(this);
this.B=window.NaN;this.U=!1;this.K=this.I=this.L=this.P=window.NaN;this.R=[];this.A=this.F=this.o=this.La=this.g=null;this.ya=a;this.R.push(g.Ss(window,"beforeunload",(0,g.A)(this.Yy,this)));this.l=[];this.La=new q7;this.aa=b.id;this.g=Mga(this,c);this.g.subscribe("handlerOpened",this.IE,this);this.g.subscribe("handlerClosed",this.FE,this);this.g.subscribe("handlerError",this.GE,this);this.g.subscribe("handlerMessage",this.HE,this);wga(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.La.videoId;g.yu()&&g.ru("yt-remote-session-video-id",a)},this)},J7=function(a){q6("conn",a)},Mga=function(a,b){return new g6(k6(a.ya,"/bc"),b)},K7=function(a,b){a.O("proxyStateChange",b)},Nga=function(a){a.B=g.or((0,g.A)(function(){J7("Connecting timeout");
this.C(1)},a),2E4)},L7=function(a){g.qr(a.B);
a.B=window.NaN},M7=function(a){g.qr(a.P);
a.P=window.NaN},Oga=function(a){N7(a);
a.L=g.or((0,g.A)(function(){O7(this,"getNowPlaying")},a),2E4)},N7=function(a){g.qr(a.L);
a.L=window.NaN},Q7=function(a,b){b&&(L7(a),M7(a));
b==(i6(a.g)&&(0,window.isNaN)(a.B))?b&&(K7(a,1),O7(a,"getSubtitlesTrack")):b?(a.V()&&a.La.reset(),K7(a,1),O7(a,"getNowPlaying"),P7(a)):a.C(1)},Pga=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.La.videoId&&(g.dc(b.params)?a.La.l=null:a.La.l=b.params,a.O("remotePlayerChange"))},S7=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.La.listId=b.params.listId||a.La.listId;v7(a.La,c,d);a.O("remoteQueueChange")},Qga=function(a,b){b.params=b.params||{};
S7(a,b);T7(a,b);a.O("autoplayDismissed")},T7=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
t7(a.La,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.La.g&&(c=-1E3);a.La.g=c;c=Number(b.params.loadedTime);a.La.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.La.I=(0,window.isNaN)(c)?0:c;c=a.La;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.La;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.La.g?Oga(a):N7(a);
a.O("remotePlayerChange")},Rga=function(a,b){if(-1E3!=a.La.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.La.g=c;c=(0,window.parseInt)(b.params.currentTime,10);t7(a.La,(0,window.isNaN)(c)?0:c);a.O("remotePlayerChange")}},Sga=function(a,b){var c="true"==b.params.muted;
a.La.volume=(0,window.parseInt)(b.params.volume,10);a.La.muted=c;a.O("remotePlayerChange")},Tga=function(a,b){a.F=b.params.videoId;
a.O("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},Uga=function(a,b){var c="true"==b.params.hasNext;
a.La.te="true"==b.params.hasPrevious;a.La.hasNext=c;a.O("previousNextChange")},P7=function(a){g.qr(a.K);
a.K=g.or((0,g.A)(a.C,a,1),864E5)},O7=function(a,b,c){c?J7("Sending: action="+b+", params="+g.qg(c)):J7("Sending: action="+b);
a.g.sendMessage(b,c)},U7=function(a){u6.call(this,"ScreenServiceProxy");
this.oc=a;this.l=[];this.l.push(this.oc.$_s("screenChange",(0,g.A)(this.tJ,this)));this.l.push(this.oc.$_s("onlineScreenChange",(0,g.A)(this.oG,this)))},Zga=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.hr("MDX_CONFIG")||b;g.pu&&$fa();T4();V7||(V7=new j6(b?b.loungeApiHost:void 0),Z4()&&(V7.g="/api/loungedev"));W7||(W7=g.z("yt.mdx.remote.deferredProxies_")||[],g.y("yt.mdx.remote.deferredProxies_",W7,void 0));Vga();var c=X7();if(!c){var d=new H6(V7);g.y("yt.mdx.remote.screenService_",d,void 0);c=X7();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Kga(a,d,function(a){a?Y7()&&p7(Y7(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.At("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.z("yt.mdx.remote.initialized_")&&(g.y("yt.mdx.remote.initialized_",!0,void 0),Z7("Initializing: "+g.qg(b)),$7.push(g.vt("yt-remote-cast2-availability-change",function(){g.At("yt-remote-receiver-availability-change")})),$7.push(g.vt("yt-remote-cast2-receiver-selected",function(){a8(null);
g.At("yt-remote-auto-connect","cast-selector-receiver")})),$7.push(g.vt("yt-remote-cast2-receiver-resumed",function(){g.At("yt-remote-receiver-resumed","cast-selector-receiver")})),$7.push(g.vt("yt-remote-cast2-session-change",Wga)),$7.push(g.vt("yt-remote-connection-change",function(a){a?p7(Y7(),"YouTube TV"):b8()||(p7(null,null),l7())})),a=c8(),b.isAuto&&(a.id+="#dial"),g.es("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),Z7(" -- with channel params: "+
g.qg(a)),Xga(a),c.start(),Y7()||Yga())},$ga=function(){var a=d8();
j7()&&g.tu("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},d8=function(){var a=X7().oc.$_gos();
var b=e8();b&&f8()&&(N4(a,b)||a.push(b));return hga(a)},g8=function(){var a=aha();
!a&&j7()&&k7()&&(a={key:"cast-selector-receiver",name:k7()});return a},aha=function(){var a=d8(),b=e8();
b||(b=b8());return g.Pa(a,function(a){return b&&H4(b,a.key)?!0:!1})},e8=function(){var a=Y7();
if(!a)return null;var b=X7().md();return O4(b,a)},Wga=function(a){Z7("remote.onCastSessionChange_: "+K4(a));
if(a){var b=e8();b&&b.id==a.id?p7(b.id,"YouTube TV"):(b&&h8(),i8(a,1))}else f8()&&h8()},h8=function(){n7()?g7().stopSession():d7("stopSession called before API ready.");
var a=f8();a&&(a.disconnect(1),j8(null))},k8=function(){var a=f8();
return!!a&&3!=a.getProxyState()},Z7=function(a){q6("remote",a)},X7=function(){if(!l8){var a=g.z("yt.mdx.remote.screenService_");
l8=a?new U7(a):null}return l8},Y7=function(){return g.z("yt.mdx.remote.currentScreenId_")},m8=function(a){g.y("yt.mdx.remote.currentScreenId_",a,void 0)},n8=function(){return g.z("yt.mdx.remote.connectData_")},a8=function(a){g.y("yt.mdx.remote.connectData_",a,void 0)},f8=function(){return g.z("yt.mdx.remote.connection_")},j8=function(a){var b=f8();
a8(null);a||m8("");g.y("yt.mdx.remote.connection_",a,void 0);W7&&((0,g.G)(W7,function(b){b(a)}),W7.length=0);
b&&!a?g.At("yt-remote-connection-change",!1):!b&&a&&g.At("yt-remote-connection-change",!0)},b8=function(){var a=g.yu();
if(!a)return null;var b=X7().md();return O4(b,a)},i8=function(a,b){e8()&&e8();
m8(a.id);var c=new I7(V7,a,c8());c.connect(b,n8());c.subscribe("beforeDisconnect",function(a){g.At("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){f8()&&j8(null)});
j8(c)},Yga=function(){var a=b8();
a?(Z7("Resume connection to: "+K4(a)),i8(a,0)):(X4(),l7(),Z7("Skipping connecting because no session screen found."))},Vga=function(){var a=c8();
if(g.dc(a)){a=S4();var b=g.tu("yt-remote-session-name")||"",c=g.tu("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.y("yt.mdx.remote.channelParams_",a,void 0)}},c8=function(){return g.z("yt.mdx.remote.channelParams_")||{}},Xga=function(a){a?(g.ru("yt-remote-session-app",a.app),g.ru("yt-remote-session-name",a.name)):(g.uu("yt-remote-session-app"),g.uu("yt-remote-session-name"));
g.y("yt.mdx.remote.channelParams_",a,void 0)},o8=function(a,b,c){g.J.call(this);
this.H=a;this.l=b;this.o=new g.dt(this);g.K(this,this.o);this.o.M(b,"onCaptionsTrackListChanged",this.IF);this.o.M(b,"captionschanged",this.CE);this.o.M(b,"captionssettingschanged",this.Xv);this.o.M(b,"videoplayerreset",this.Uk);this.o.M(b,"mdxautoplaycancel",this.qy);this.R=this.o.M(b,"onVolumeChange",this.wu);this.F=!1;this.g=c;c.subscribe("proxyStateChange",this.Fu,this);c.subscribe("remotePlayerChange",this.Oi,this);c.subscribe("remoteQueueChange",this.Uk,this);c.subscribe("autoplayUpNext",this.gu,
this);c.subscribe("previousNextChange",this.Cu,this);c.subscribe("nowAutoplaying",this.yu,this);c.subscribe("autoplayDismissed",this.fu,this);this.suggestion=null;this.I=new g.FE(64);this.A=new g.P(this.Tv,500,this);g.K(this,this.A);this.B=new g.P(this.Uv,1E3,this);g.K(this,this.B);this.L=new h5(this.XI,0,this);g.K(this,this.L);this.C={};this.P=new g.P(this.Dw,1E3,this);g.K(this,this.P);this.K=new g.Hl(this.uB,1E3,this);g.K(this,this.K);this.U=g.wa;this.Xv();this.Uk();this.Oi()},p8=function(a,b){var c=
a.H,d=a.l.Y().lengthSeconds;
c.I=b||0;c.g.O("progresssync",b,d)},r8=function(a){p8(a,0);
a.A.stop();q8(a,new g.FE(64))},t8=function(a,b){if(s8(a)&&!a.F){var c=null;
b&&(c={style:a.l.Hg()},g.kc(c,b));a.g.Mv(a.l.Y(1).videoId,c);c=A7(a.g).l;a.C=c}},u8=function(a,b){var c=a.l.De();
if(c){var d=c.Oa;var e=c.listId.toString()}var f=a.l.Y(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.kh;var m=A7(c),n=e||m.listId;l=l||0;var p={videoId:k,currentIndex:l};v7(m,k,l);g.t(b)&&(t7(m,b),p.currentTime=b);g.t(n)&&(p.listId=n);null!=d&&(p.playerParams=d);null!=f&&(p.clickTrackingParams=f);F7(c,"setPlaylist",p);e||D7(c,m);q8(a,new g.FE(1))},v8=function(a,b){if(b){var c=a.l.Lb("captions","tracklist",{Gr:1});
c&&c.length?(a.l.Pc("captions","track",b),a.F=!1):(a.l.Di("captions"),a.F=!0)}else a.l.Pc("captions","track",{})},s8=function(a){return A7(a.g).videoId==a.l.Y(1).videoId},q8=function(a,b){a.B.stop();
var c=a.I;if(!g.OE(c,b)){var d=g.T(b,2);d!=g.T(a.I,2)&&g.BL(a.l,d);a.I=b;w8(a.H,c,b)}},y8=function(a){g.W.call(this,{D:"div",
J:"ytp-remote",G:[{D:"div",J:"ytp-remote-display-status",G:[{D:"div",J:"ytp-remote-display-status-icon",G:[g.nP()]},{D:"div",J:"ytp-remote-display-status-text",G:["{{statustext}}"]}]}]});this.g=new g.fQ(this,250);g.K(this,this.g);this.l=a;this.M(a,"presentingplayerstatechange",this.o);x8(this,g.yL(a))},x8=function(a,b){if(3==a.l.Ca()){var c={RECEIVER_NAME:a.l.Lb("remote","currentReceiver").name};
c=g.T(b,128)?g.S("YTP_MDX_STATUS_ERROR_2",c):b.gb()||g.T(b,4)?g.S("YTP_MDX_STATUS_PLAYING_2",c):g.S("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.g.show()}else a.g.hide()},z8=function(a,b){g.CU.call(this,g.S("YTP_MDX_TITLE"),0,a,b);
this.g=a;this.F={};this.M(a,"onMdxReceiversChange",this.I);this.M(a,"presentingplayerstatechange",this.I);this.I()},A8=function(a){g.bM.call(this,a);
g.Au({YTP_MDX_CAST_SELECTOR:"Cast...",YTP_MDX_MY_COMPUTER:"This computer",YTP_MDX_PLAYER_ERROR:"This video is not available for remote playback.",YTP_MDX_STATUS_CONNECTED_2:"Connected to $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"Error on $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"Playing on $RECEIVER_NAME",YTP_MDX_TITLE:"Play on"});this.o={key:M4(),name:g.S("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.K=this.l=null;this.H=[this.o];this.A=this.o;this.F=new g.FE(64);this.I=0;if(!g.BB(g.U(this.g))){a=
this.g;var b=g.sL(a).I;b&&(b=b.o&&b.o.g)&&(b=new z8(a,b),g.K(this,b));b=new y8(a);g.K(this,b);g.TL(a,b.element,4)}},w8=function(a,b,c){a.F=c;
a.g.O("presentingplayerstatechange",new g.UE(c,b))},B8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)h8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.Y(1),e=d.videoId;if(c||e){var f=a.g.De();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Eb(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.kh,index:Math.max(a.g.Vs(),0),currentTime:0==f?void 0:f}}else c=null;Z7("Connecting to: "+g.qg(b));"cast-selector-receiver"==b.key?(a8(c||null),n7()?g7().setLaunchParams(c||null):d7("setLaunchParams called before ready.")):!c&&
k8()&&Y7()==b.key?g.At("yt-remote-connection-change",!0):(h8(),a8(c||null),c=X7().md(),(c=O4(c,b.key))&&i8(c,1))}},Xfa=/^https?$/i,bha=["POST",
"PUT"];g.F(B4,g.lf);g.h=B4.prototype;g.h.Ze=null;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.I+"; newUri="+a);b=b?b.toUpperCase():"GET";this.I=a;this.B="";this.A=0;this.X=b;this.R=!1;this.l=!0;this.g=this.U?t4(this.U):t4(g.$W);this.P=this.U?s4(this.U):s4(g.$W);this.g.onreadystatechange=(0,g.A)(this.qr,this);try{q4(u4(this,"Opening Xhr")),this.aa=!0,this.g.open(b,String(a),!0),this.aa=!1}catch(f){q4(u4(this,"Error opening Xhr: "+f.message));y4(this,f);return}a=c||"";var e=this.headers.clone();
d&&Ufa(d,function(a,b){e.set(b,a)});
d=g.Pa(e.jd(),Vfa);c=g.x.FormData&&a instanceof g.x.FormData;!g.Ta(bha,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.g.setRequestHeader(b,a)},this);
this.ba&&(this.g.responseType=this.ba);"withCredentials"in this.g&&this.g.withCredentials!==this.V&&(this.g.withCredentials=this.V);try{v4(this),0<this.C&&(this.L=Wfa(this.g),q4(u4(this,"Will abort after "+this.C+"ms if incomplete, xhr2 "+this.L)),this.L?(this.g.timeout=this.C,this.g.ontimeout=(0,g.A)(this.rr,this)):this.F=g.gg(this.rr,this.C,this)),q4(u4(this,"Sending request")),this.H=!0,this.g.send(a),this.H=!1}catch(f){q4(u4(this,"Send error: "+f.message)),y4(this,f)}};
g.h.rr=function(){"undefined"!=typeof g.DW&&this.g&&(this.B="Timed out after "+this.C+"ms, aborting",this.A=8,u4(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.l&&(u4(this,"Aborting"),this.l=!1,this.o=!0,this.g.abort(),this.o=!1,this.A=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),x4(this))};
g.h.T=function(){this.g&&(this.l&&(this.l=!1,this.o=!0,this.g.abort(),this.o=!1),x4(this,!0));B4.ua.T.call(this)};
g.h.qr=function(){this.ga()||(this.aa||this.H||this.o?A4(this):this.JG())};
g.h.JG=function(){A4(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<z4(this)?this.g.status:-1}catch(a){return-1}};
g.h=D4.prototype;g.h.Sd=function(){return this.g.length+this.l.length};
g.h.isEmpty=function(){return g.Ua(this.g)&&g.Ua(this.l)};
g.h.clear=function(){this.g=[];this.l=[]};
g.h.contains=function(a){return g.Ta(this.g,a)||g.Ta(this.l,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Rba)(b,a);0<=c?(g.Xa(b,c),b=!0):b=!1;return b||g.Ya(this.l,a)};
g.h.Vb=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};
var w5={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},v5={"'":"\\'"},cha={},fga={HJ:"atp",YL:"ska",KL:"que",hL:"mus",XL:"sus"};
F4.prototype.Nj=function(){var a=new F4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var Y4,R4="",e5=$4("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",pga=$4("loadCastFramework")||$4("loadCastApplicationFramework"),Jga=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.F(h5,g.J);g.h=h5.prototype;g.h.Vy=function(a){this.A=arguments;this.g=!1;this.xa?this.o=(0,g.H)()+this.Hb:this.xa=g.gg(this.B,this.Hb)};
g.h.stop=function(){this.xa&&(g.x.clearTimeout(this.xa),this.xa=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.T=function(){this.stop();h5.ua.T.call(this)};
g.h.Wy=function(){this.o?(this.xa=g.gg(this.B,this.o-(0,g.H)()),this.o=null):(this.xa=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};i5.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
i5.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=j5.prototype;g.h.tg=null;g.h.ge=!1;g.h.Lh=null;g.h.wp=null;g.h.yh=null;g.h.ih=null;g.h.Ff=null;g.h.Wf=null;g.h.Mg=null;g.h.Zb=null;g.h.dj=0;g.h.he=null;g.h.El=null;g.h.Gf=null;g.h.mi=-1;g.h.Av=!0;g.h.jg=!1;g.h.Nm=0;g.h.dl=null;var q5={},o5={};g.h=j5.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.gI=function(a){a=a.target;var b=this.dl;b&&3==z4(a)?b.gh():this.Fw(a)};
g.h.Fw=function(a){try{if(a==this.Zb)a:{var b=z4(this.Zb),c=this.Zb.A,d=this.Zb.getStatus();if(g.qd&&!g.yc(10)||g.sd&&!g.wc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.ph&&!C4(this.Zb))break a;this.jg||4!=b||7==c||(8==c||0>=d?this.g.ee(3):this.g.ee(2));A5(this);var e=this.Zb.getStatus();this.mi=e;var f=C4(this.Zb);(this.ge=200==e)?(4==b&&s5(this),this.B?(u5(this,b,f),g.ph&&this.ge&&3==b&&(this.da.ea(this.l,"tick",this.YH),this.l.start())):r5(this,f),this.ge&&!this.jg&&(4==b?this.g.Sk(this):(this.ge=
!1,n5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Gf=3,p5(13)):(this.Gf=0,p5(14)),s5(this),t5(this))}}catch(k){this.Zb&&C4(this.Zb)}finally{}};
g.h.YH=function(){var a=z4(this.Zb),b=C4(this.Zb);this.dj<b.length&&(A5(this),u5(this,a,b),this.ge&&4!=a&&n5(this))};
g.h.yH=function(a){z5((0,g.A)(this.xH,this,a),0)};
g.h.xH=function(a){this.jg||(A5(this),r5(this,a),n5(this))};
g.h.Mu=function(a){z5((0,g.A)(this.wH,this,a),0)};
g.h.wH=function(a){this.jg||(s5(this),this.ge=a,this.g.Sk(this),this.g.ee(4))};
g.h.cancel=function(){this.jg=!0;s5(this)};
g.h.IH=function(){this.Lh=null;var a=(0,g.H)();0<=a-this.wp?(2!=this.ih&&this.g.ee(3),s5(this),this.Gf=2,p5(18),t5(this)):y5(this,this.wp-a)};g.h=E5.prototype;g.h.Km=null;g.h.sd=null;g.h.fl=!1;g.h.pr=null;g.h.Xj=null;g.h.Lm=null;g.h.Mm=null;g.h.Gd=null;g.h.Ue=-1;g.h.li=null;g.h.Ph=null;g.h.connect=function(a){this.Mm=a;a=F5(this.g,null,this.Mm);p5(3);this.pr=(0,g.H)();var b=this.g.H;null!=b?(this.li=b[0],(this.Ph=b[1])?(this.Gd=1,G5(this)):(this.Gd=2,I5(this))):(p4(a,"MODE","init"),this.sd=new j5(this,void 0,void 0,void 0),this.sd.tg=this.Km,m5(this.sd,a,!1,null,!0),this.Gd=0)};
g.h.ty=function(a){if(a)this.Gd=2,I5(this);else{p5(4);var b=this.g;b.Wd=b.wf.Ue;b6(b,9)}a&&this.ee(2)};
g.h.nm=function(a){return this.g.nm(a)};
g.h.abort=function(){this.sd&&(this.sd.cancel(),this.sd=null);this.Ue=-1};
g.h.mr=function(){return!1};
g.h.Gu=function(a,b){this.Ue=a.mi;if(0==this.Gd)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Wd=this.Ue;b6(c,2);return}this.li=c[0];this.Ph=c[1]}else c=this.g,c.Wd=this.Ue,b6(c,2);else if(2==this.Gd)if(this.fl)p5(7),this.Lm=(0,g.H)();else if("11111"==b){if(p5(6),this.fl=!0,this.Xj=(0,g.H)(),c=this.Xj-this.pr,!g.qd||g.yc(10)||500>c)this.Ue=200,this.sd.cancel(),p5(12),H5(this.g,this,!0)}else p5(8),this.Xj=this.Lm=(0,g.H)(),this.fl=!1};
g.h.Sk=function(){this.Ue=this.sd.mi;if(this.sd.ge)0==this.Gd?this.Ph?(this.Gd=1,G5(this)):(this.Gd=2,I5(this)):2==this.Gd&&((!g.qd||g.yc(10)?!this.fl:200>this.Lm-this.Xj)?(p5(11),H5(this.g,this,!1)):(p5(12),H5(this.g,this,!0)));else{0==this.Gd?p5(9):2==this.Gd&&p5(10);var a=this.g;a.Wd=this.Ue;b6(a,2)}};
g.h.Xi=function(){return this.g.Xi()};
g.h.isActive=function(){return this.g.isActive()};
g.h.ee=function(a){this.g.ee(a)};g.h=J5.prototype;g.h.Yh=null;g.h.Xc=null;g.h.Gb=null;g.h.Jm=null;g.h.ak=null;g.h.Yp=null;g.h.mk=null;g.h.Mi=0;g.h.ZD=0;g.h.yc=null;g.h.zf=null;g.h.Oe=null;g.h.mg=null;g.h.wf=null;g.h.Dl=null;g.h.mh=-1;g.h.Rr=-1;g.h.Wd=-1;g.h.eh=0;g.h.Yg=0;g.h.kg=8;var c6=new g.lf;g.F(K5,g.Ge);g.F(L5,g.Ge);g.F(M5,g.Ge);g.h=J5.prototype;g.h.connect=function(a,b,c,d,e){p5(0);this.Jm=b;this.Yh=c||{};d&&g.t(e)&&(this.Yh.OSID=d,this.Yh.OAID=e);this.C?(z5((0,g.A)(this.xq,this,a),100),S5(this)):this.xq(a)};
g.h.xq=function(a){this.wf=new E5(this);this.wf.Km=null;this.wf.l=this.B;this.wf.connect(a)};
g.h.mr=function(){return 0==this.g};
g.h.Ku=function(a){this.zf=null;X5(this,a)};
g.h.Ju=function(){this.Oe=null;this.Gb=new j5(this,this.o,"rpc",this.F);this.Gb.tg=null;this.Gb.Nm=0;var a=this.Yp.clone();g.to(a,"RID","rpc");g.to(a,"SID",this.o);g.to(a,"CI",this.Dl?"0":"1");g.to(a,"AID",this.mh);O5(this,a);if(!g.qd||g.yc(10))g.to(a,"TYPE","xmlhttp"),m5(this.Gb,a,!0,this.mk,!1);else{g.to(a,"TYPE","html");var b=this.Gb,c=!!this.mk;b.ih=3;b.Ff=o4(a.clone());x5(b,c)}};
g.h.Gu=function(a,b){if(0!=this.g&&(this.Gb==a||this.Xc==a))if(this.Wd=a.mi,this.Xc==a&&3==this.g)if(7<this.kg){try{var c=this.B.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.Oe){if(this.Gb)if(this.Gb.yh+3E3<this.Xc.yh)T5(this),this.Gb.cancel(),this.Gb=null;else break a;$5(this);p5(19)}}else this.Rr=c[1],0<this.Rr-this.mh&&37500>c[2]&&this.Dl&&0==this.Yg&&!this.mg&&(this.mg=z5((0,g.A)(this.yE,this),6E3));else b6(this,11)}else b!=cha.hK.g&&b6(this,11);else if(this.Gb==a&&
T5(this),!g.tb(b)){c=this.B.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.mh=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.mk=e[2],e=e[3],null!=e?this.kg=e:this.kg=6,this.g=3,this.yc&&this.yc.iq(),this.Yp=F5(this,this.Xi()?this.mk:null,this.Jm),Y5(this)):"stop"==e[0]&&b6(this,7):3==this.g&&("stop"==e[0]?b6(this,7):"noop"!=e[0]&&this.yc&&this.yc.hq(e),this.Yg=0)}}};
g.h.yE=function(){null!=this.mg&&(this.mg=null,this.Gb.cancel(),this.Gb=null,$5(this),p5(20))};
g.h.Sk=function(a){if(this.Gb==a){T5(this);this.Gb=null;var b=2}else if(this.Xc==a)this.Xc=null,b=1;else return;this.Wd=a.mi;if(0!=this.g)if(a.ge)1==b?(b=(0,g.H)()-a.yh,c6.dispatchEvent(new L5(c6,a.Mg?a.Mg.length:0,b,this.eh)),R5(this),this.A.length=0):Y5(this);else{var c=a.Gf,d;if(!(d=3==c||7==c||0==c&&0<this.Wd)){if(d=1==b)this.Xc||this.zf||1==this.g||2<=this.eh?d=!1:(this.zf=z5((0,g.A)(this.Ku,this,a),Z5(this,this.eh)),this.eh++,d=!0);d=!(d||2==b&&$5(this))}if(d)switch(c){case 1:b6(this,5);break;
case 4:b6(this,10);break;case 3:b6(this,6);break;case 7:b6(this,12);break;default:b6(this,2)}}};
g.h.Fy=function(a){if(!g.Ta(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.NI=function(a){a?p5(2):(p5(1),a6(this,8))};
g.h.nm=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new B4;a.V=!1;return a};
g.h.isActive=function(){return!!this.yc&&this.yc.isActive(this)};
g.h.ee=function(a){c6.dispatchEvent(new M5(c6,a))};
g.h.Xi=function(){return!(!g.qd||g.yc(10))};
g.h=d6.prototype;g.h.iq=function(){};
g.h.hq=function(){};
g.h.gq=function(){};
g.h.fm=function(){};
g.h.Vq=function(){return{}};
g.h.isActive=function(){return!0};g.F(f6,g.J);f6.prototype.o=function(){500<this.Hb&&24E4>2*this.Hb&&(this.Hb*=2);this.A();this.l&&this.start()};
f6.prototype.start=function(){g.Up(this.g,this.Hb);this.l=(0,g.H)()+this.Hb};
f6.prototype.stop=function(){this.g.stop();this.l=0};
f6.prototype.isActive=function(){return this.g.isActive()};g.F(g6,d6);g.h=g6.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.wc=function(a){return this.o.wc(a)};
g.h.O=function(a,b){return this.o.O.apply(this.o,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.Ee(this.o),h6(this),g.Ee(this.l),this.l=null)};
g.h.ga=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.I="";this.l.stop();this.B=a||null;this.A=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new J5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.P),e=this.g;e&&(e.yc=null);d.yc=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.mh):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.kc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.F.push(c):i6(this)&&U5(this.g,c)};
g.h.iq=function(){e6(this.l);this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)U5(this.g,a[b])}this.O("handlerOpened")};
g.h.gq=function(a){var b=2==a&&401==this.g.Wd;if(4!=a&&!b){if(6==a||410==this.g.Wd)b=this.l,b.g.stop(),b.Hb=500;this.l.start()}this.O("handlerError",a)};
g.h.fm=function(a){if(!this.l.isActive())this.O("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.Vq=function(){var a={v:2};this.I&&(a.gsessionid=this.I);0!=this.A&&(a.ui=""+this.A);0!=this.H&&(a.ui=""+this.H);this.B&&g.kc(a,this.B);return a};
g.h.hq=function(a){"S"==a[0]?this.I=a[1]:"gracefulReconnect"==a[0]?(e6(this.l),this.l.start(),Q5(this.g)):this.O("handlerMessage",new uga(a[0],a[1]))};
g.h.pJ=function(){this.l.isActive();var a=this.g,b=0;a.Gb&&b++;a.Xc&&b++;0!=b?this.l.start():this.connect(this.B,this.A)};j6.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
j6.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
j6.prototype.B=function(a){a(Error("request timed out"))};var Aga=(0,g.H)(),o6=null,s6=Array(50),r6=-1,t6=!1;g.F(u6,g.R);u6.prototype.md=function(){return this.g};
u6.prototype.contains=function(a){return!!N4(this.g,a)};
u6.prototype.get=function(a){return a?O4(this.g,a):null};
u6.prototype.info=function(a){q6(this.F,a)};g.F(w6,g.R);var C8=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=w6.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.xa)&&this.Jw()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.xa)||(g.qr(this.xa),this.xa=window.NaN)};
g.h.T=function(){this.stop();w6.ua.T.call(this)};
g.h.Jw=function(){this.xa=window.NaN;this.g=g.Fr(k6(this.C,"/pairing/get_screen"),{method:"POST",jb:{pairing_code:this.B},timeout:5E3,ib:(0,g.A)(this.rJ,this),onError:(0,g.A)(this.qJ,this),Qc:(0,g.A)(this.sJ,this)})};
g.h.rJ=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.O("pairingComplete",new G4(c))};
g.h.qJ=function(a){this.g=null;a.status&&404==a.status?this.l>=C8.length?this.O("pairingFailed",Error("DIAL polling timed out")):(a=C8[this.l],this.xa=g.or((0,g.A)(this.Jw,this),a),this.l++):this.O("pairingFailed",Error("Server error "+a.status))};
g.h.sJ=function(){this.g=null;this.O("pairingFailed",Error("Server not responding"))};g.F(y6,u6);g.h=y6.prototype;g.h.start=function(){x6(this)&&this.O("screenChange");!g.tu("yt-remote-lounge-token-expiration")&&z6(this);g.qr(this.l);this.l=g.or((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){x6(this);v6(this,a);A6(this,!1);this.O("screenChange");b(a);a.token||z6(this)};
g.h.remove=function(a,b){var c=x6(this);Cga(this,a)&&(A6(this,!1),c=!0);b(a);c&&this.O("screenChange")};
g.h.zl=function(a,b,c,d){var e=x6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,A6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.O("screenChange")};
g.h.T=function(){g.qr(this.l);y6.ua.T.call(this)};
g.h.ez=function(a){x6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}A6(this,!b);b&&q6(this.F,"Missed "+b+" lounge tokens.")};
g.h.dz=function(a){q6(this.F,"Requesting lounge tokens failed: "+a)};g.F(C6,g.R);g.h=C6.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.tu("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.H)()-144E5<a?0:a)?F6(this):(this.A=(0,g.H)()+3E5,g.ru("yt-remote-fast-check-period",this.A),this.No())};
g.h.isEmpty=function(){return g.dc(this.g)};
g.h.update=function(){B6("Updating availability on schedule.");var a=this.C(),b=g.Tb(this.g,function(b,d){return b&&!!O4(a,d)},this);
E6(this,b)};
g.h.T=function(){g.qr(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);C6.ua.T.call(this)};
g.h.No=function(){g.qr(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=G6(this);if(g.Wb(a)){var b=k6(this.B,"/pairing/get_screen_availability");this.l=l6(this.B,b,{lounge_token:g.Yb(a).join(",")},(0,g.A)(this.cH,this,a),(0,g.A)(this.bH,this))}else E6(this,{}),F6(this)};
g.h.cH=function(a,b){this.l=null;var c=g.Yb(G6(this));if(g.ob(c,g.Yb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;E6(this,d);F6(this)}else this.Cb("Changing Screen set during request."),this.No()};
g.h.bH=function(a){this.Cb("Screen availability failed: "+a);this.l=null;F6(this)};
g.h.Cb=function(a){q6("OnlineScreenService",a)};g.F(H6,u6);g.h=H6.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.O("screenChange"),this.l.isEmpty()||this.O("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.zl=function(a,b,c,d){this.o.contains(a)?this.o.zl(a,b,c,d):(a="Updating name of unknown screen: "+a.name,q6(this.F,a),d(Error(a)))};
g.h.md=function(a){return a?this.g:g.ab(this.g,(0,g.Gd)(this.A,function(a){return!this.contains(a)},this))};
g.h.Kw=function(){return(0,g.Gd)(this.md(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.Lw=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new w6(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.Ee(f);d(I6(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Ee(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.uJ=function(a,b,c,d){g.Fr(k6(this.C,"/pairing/get_screen"),{method:"POST",jb:{pairing_code:a},timeout:5E3,ib:(0,g.A)(function(a,d){var e=new G4(d.screen||{});if(!e.name||K6(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);K6(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(I6(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Qc:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.Ee(this.o);g.Ee(this.l);H6.ua.T.call(this)};
g.h.rz=function(){L6(this);this.O("screenChange");this.l.update()};
H6.prototype.dispose=H6.prototype.dispose;g.F(N6,g.R);g.h=N6.prototype;g.h.Tk=function(a){this.o=a;this.O("sessionScreen",this.o)};
g.h.qd=function(a){this.ga()||(a&&O6(this,""+a),this.o=null,this.O("sessionScreen",null))};
g.h.info=function(a){q6(this.P,a)};
g.h.Nw=function(){return null};
g.h.Vo=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){O6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.Vo("");N6.ua.T.call(this)};g.F(Q6,N6);g.h=Q6.prototype;g.h.Uo=function(a){if(this.g){if(this.g==a)return;O6(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);Gga(this)};
g.h.nh=function(a){this.info("launchWithParams no-op for Cast: "+g.qg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.A)(function(){this.qd()},this),(0,g.A)(function(){this.qd(Error("Failed to stop receiver app."))},this)):this.qd(Error("Stopping cast device witout session."))};
g.h.Vo=g.wa;g.h.T=function(){this.info("disposeInternal");g.qr(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;Q6.ua.T.call(this)};
g.h.SH=function(a,b){if(!this.ga())if(b){var c=g.aq(b);if(c){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.qg(c));switch(d){case "mdxSessionStatus":P6(this,c.screenId);break;default:O6(this,"Unknown youtube message: "+d)}}else O6(this,"Unable to parse message.")}else O6(this,"No data in message.")};
g.h.fr=function(a,b,c,d){J6(this.I,this.l.label,a,this.l.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(O6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.or((0,g.A)(this.fr,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.Nw=function(){return this.g};
g.h.vJ=function(a){this.ga()||a||(O6(this,"Cast session died."),this.qd())};g.F(R6,N6);g.h=R6.prototype;g.h.Uo=function(a){this.A=a;this.A.addUpdateListener(this.L)};
g.h.nh=function(a){this.B=a;this.F()};
g.h.stop=function(){this.g();this.g=g.wa;g.qr(this.C);this.A?this.A.stop((0,g.A)(this.qd,this,null),(0,g.A)(this.qd,this,"Failed to stop DIAL device.")):this.qd()};
g.h.T=function(){this.g();this.g=g.wa;g.qr(this.C);this.A&&this.A.removeUpdateListener(this.L);this.A=null;R6.ua.T.call(this)};
g.h.yJ=function(a){this.ga()||a||(O6(this,"DIAL session died."),this.g(),this.g=g.wa,this.qd())};
g.h.bn=function(a){this.K=M4();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,T6(this));a(b);S6(this)}else this.F=(0,g.A)(function(){g.qr(this.C);this.F=g.wa;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,T6(this));a(b);S6(this)},this),this.C=g.or((0,g.A)(function(){this.F()},this),100)};
g.h.Pz=function(a,b,c){J6(this.I,this.H.receiver.label,a,this.l.friendlyName,(0,g.A)(function(a){a&&a.token?(this.Tk(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.bn(b,c)},this),(0,g.A)(function(a){O6(this,"Failed to get DIAL screen: "+a);
this.bn(b,c)},this))};g.F(U6,N6);U6.prototype.stop=function(){this.qd()};
U6.prototype.Uo=g.wa;U6.prototype.nh=function(){g.qr(this.g);this.g=window.NaN;var a=O4(this.I.md(),this.l.label);a?this.Tk(a):this.qd(Error("No such screen"))};
U6.prototype.T=function(){g.qr(this.g);this.g=window.NaN;U6.ua.T.call(this)};g.F(V6,g.R);g.h=V6.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.F);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.A)(this.Hu,this),(0,g.A)(this.OG,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.bF,this);window.chrome.cast.initialize(c,
(0,g.A)(function(){this.ga()||(window.chrome.cast.addReceiverActionListener(this.A),xga(),this.l.subscribe("onlineScreenChange",(0,g.A)(this.Mw,this)),this.o=$6(this),window.chrome.cast.setCustomReceivers(this.o,g.wa,(0,g.A)(function(a){this.Cb("Failed to set initial custom receivers: "+g.qg(a))},this)),this.O("yt-remote-cast2-availability-change",Y6(this)),b(!0))},this),(0,g.A)(function(a){this.Cb("Failed to initialize API: "+g.qg(a));
b(!1)},this))};
g.h.DI=function(a,b){X6("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)X6("Unsetting old screen status: "+this.g.l.friendlyName),Z6(this,null)}if(a&&b){if(!this.g){c=O4(this.l.md(),a);if(!c){X6("setConnectedScreenStatus: Unknown screen.");return}var d=W6(this,c);d||(X6("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.wa,(0,g.A)(function(a){this.Cb("Failed to set initial custom receivers: "+g.qg(a))},this)));
X6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);Z6(this,new U6(this.l,d),!0)}this.g.Vo(b)}else X6("setConnectedScreenStatus: no screen.")};
g.h.EI=function(a){this.ga()?this.Cb("Setting connection data on disposed cast v2"):this.g?this.g.nh(a):this.Cb("Setting connection data without a session")};
g.h.xJ=function(){this.ga()?this.Cb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),Z6(this,null)):X6("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.A)(this.Hu,this),(0,g.A)(this.fH,this))};
g.h.T=function(){this.l.unsubscribe("onlineScreenChange",(0,g.A)(this.Mw,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Ya(g.z("yt.mdx.remote.debug.handlers_")||[],m6);g.Ee(this.g);V6.ua.T.call(this)};
g.h.Cb=function(a){q6("Controller",a)};
g.h.Iu=function(a,b){this.g==a&&(b||Z6(this,null),this.O("yt-remote-cast2-session-change",b))};
g.h.KG=function(a,b){if(!this.ga())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),X6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)X6("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{X6("onReceiverAction_: Casting to active receiver.");this.g.o&&this.O("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:Z6(this,
new U6(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:Z6(this,new R6(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:Z6(this,new Q6(this.l,a));break;default:this.Cb("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.Cb("Stopping receiver w/o session: "+a.friendlyName)}else this.Cb("onReceiverAction_ called without receiver.")};
g.h.bF=function(a){if(this.ga())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.Cb("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.Cb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return X6("Reselecting dial screen."),
this.O("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.Cb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);Z6(this,new R6(this.l,b,this.C))}b=this.g;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.A)(b.Pz,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.A)(b.bn,b))};
g.h.Hu=function(a){if(!this.ga()){X6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)X6("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),Z6(this,new Q6(this.l,b),!0);else{this.Cb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=O4(this.l.md(),c.label);
d&&H4(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(X6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ee(this.g),this.g=new Q6(this.l,b),this.g.subscribe("sessionScreen",(0,g.A)(this.Iu,this,this.g)),this.g.nh(null));this.g.Uo(a)}}};
g.h.wJ=function(){return this.g?this.g.Nw():null};
g.h.fH=function(a){this.ga()||(this.Cb("Failed to estabilish a session: "+g.qg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&Z6(this,null))};
g.h.OG=function(a){X6("Receiver availability updated: "+a);if(!this.ga()){var b=Y6(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;Y6(this)!=b&&this.O("yt-remote-cast2-availability-change",Y6(this))}};
g.h.Mw=function(){this.ga()||(this.o=$6(this),X6("Updating custom receivers: "+g.qg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.wa,(0,g.A)(function(){this.Cb("Failed to set custom receivers.")},this)),this.O("yt-remote-cast2-availability-change",Y6(this)))};
V6.prototype.setLaunchParams=V6.prototype.EI;V6.prototype.setConnectedScreenStatus=V6.prototype.DI;V6.prototype.stopSession=V6.prototype.xJ;V6.prototype.getCastSession=V6.prototype.wJ;V6.prototype.requestSession=V6.prototype.requestSession;V6.prototype.init=V6.prototype.init;V6.prototype.dispose=V6.prototype.dispose;var i7=[];q7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";r7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.te=a.hasPrevious,this.hasNext=a.hasNext,this.H=a.playerTime,this.F=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.I=a.duration,this.K=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
q7.prototype.gb=function(){return 1==this.g};
q7.prototype.getDuration=function(){return this.C?this.I+s7(this):this.I};
q7.prototype.clone=function(){return new q7(w7(this))};g.F(z7,g.R);g.h=z7.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.wa,H7(this,"play")):F7(this,"play"),E7(this,1,u7(A7(this))),this.O("remotePlayerChange")):C7(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.wa,H7(this,"pause")):F7(this,"pause"),E7(this,2,u7(A7(this))),this.O("remotePlayerChange")):C7(this,this.pause)};
g.h.Iw=function(a){if(1==this.g){if(this.l){var b=A7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;b.gb()||3==b.g?c.resumeState=window.chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.wa,H7(this,"seekTo",{newTime:a}))}else F7(this,"seekTo",{newTime:a});E7(this,3,a);this.O("remotePlayerChange")}else C7(this,g.B(this.Iw,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.wa,H7(this,"stopVideo")):F7(this,"stopVideo");var a=A7(this);a.index=-1;a.videoId="";r7(a);D7(this,a);this.O("remotePlayerChange")}else C7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=A7(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.A)(function(){q6("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.Cb("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.A)(function(){q6("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.Cb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);F7(this,"setVolume",e)}c.muted=b;c.volume=a;D7(this,c)}else C7(this,g.B(this.setVolume,a,b))};
g.h.Mv=function(a,b){if(1==this.g){var c=A7(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.qg(b.style),g.kc(d,c.l));F7(this,"setSubtitlesTrack",d);D7(this,c)}else C7(this,g.B(this.Mv,a,b))};
g.h.xp=function(a,b){if(1==this.g){F7(this,"setAudioTrack",{videoId:a,audioTrackId:b.dc.id});var c=A7(this);c.audioTrackId=b.dc.id;D7(this,c)}else C7(this,g.B(this.xp,a,b))};
g.h.Hw=function(a,b){if(1==this.g){if(a&&b){var c=A7(this);v7(c,a,b);D7(this,c)}F7(this,"previous")}else C7(this,g.B(this.Hw,a,b))};
g.h.Gw=function(a,b){if(1==this.g){if(a&&b){var c=A7(this);v7(c,a,b);D7(this,c)}F7(this,"next")}else C7(this,g.B(this.Gw,a,b))};
g.h.Jq=function(){1==this.g?F7(this,"dismissAutoplay"):C7(this,this.Jq)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.O("proxyStateChange",a,this.g)}z7.ua.dispose.call(this)};
g.h.T=function(){B7(this);this.A=null;this.B.clear();y7(this,null);z7.ua.T.call(this)};
g.h.yp=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.O("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.Ua(b.g)&&(b.g=b.l,b.g.reverse(),b.l=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.HG=function(a,b){this.O(a,b)};
g.h.EE=function(a){if(!a)this.Ni(null),y7(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=A7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)q6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,D7(this,b)}};
g.h.Ni=function(a){q6("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.H);if(this.l=a)this.l.addUpdateListener(this.H),G7(this),this.O("remotePlayerChange")};
g.h.DE=function(a){a?(G7(this),this.O("remotePlayerChange")):this.Ni(null)};
g.h.RE=function(){var a=m7();a&&y7(this,a)};
g.h.Cb=function(a){q6("CP",a)};g.F(I7,g.R);g.h=I7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.La.listId=c);this.La.videoId=d;this.La.index=k||0;this.La.state=3;t7(this.La,m);this.A="UNSUPPORTED";J7("Connecting with setPlaylist and params: "+g.qg(l));this.g.connect({method:"setPlaylist",params:g.qg(l)},a,U4())}else J7("Connecting without params"),
this.g.connect({},a,U4());Nga(this)};
g.h.dispose=function(){this.ga()||(this.O("beforeDispose"),K7(this,3));I7.ua.dispose.call(this)};
g.h.T=function(){L7(this);N7(this);M7(this);g.qr(this.I);this.I=window.NaN;g.qr(this.K);this.K=window.NaN;this.o=null;g.Ts(this.R);this.R.length=0;this.g.dispose();I7.ua.T.call(this);this.A=this.F=this.l=this.La=this.g=null};
g.h.Yy=function(){this.C(2)};
g.h.IE=function(){J7("Channel opened");this.U&&(this.U=!1,M7(this),this.P=g.or((0,g.A)(function(){J7("Timing out waiting for a screen.");this.C(1)},this),15E3));
kga(vga(this.g),this.aa)};
g.h.FE=function(){J7("Channel closed");(0,window.isNaN)(this.B)?X4(!0):X4();this.dispose()};
g.h.GE=function(a){X4();(0,window.isNaN)(this.H())?(J7("Channel error: "+a+" without reconnection"),this.dispose()):(this.U=!0,J7("Channel error: "+a+" with reconnection in "+this.H()+" ms"),K7(this,2))};
g.h.HE=function(a){a.params?J7("Received: action="+a.action+", params="+g.qg(a.params)):J7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.aq(a.params.devices);this.l=(0,g.I)(a,function(a){return new F4(a)});
a=!!g.Pa(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
Q7(this,a);break;case "loungeScreenDisconnected":g.$a(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
Q7(this,!1);break;case "remoteConnected":var b=new F4(g.aq(a.params.device));g.Pa(this.l,function(a){return b?a.id==b.id:!1})||g.Wa(this.l,b);
break;case "remoteDisconnected":b=new F4(g.aq(a.params.device));g.$a(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":S7(this,a);break;case "nowPlaying":Qga(this,a);break;case "onStateChange":T7(this,a);break;case "onAdStateChange":Rga(this,a);break;case "onVolumeChanged":Sga(this,a);break;case "onSubtitlesTrackChanged":Pga(this,a);break;case "nowAutoplaying":Tga(this,a);break;case "autoplayDismissed":this.O("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.O("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.O("autoplayModeChange",this.A);"DISABLED"==this.A&&this.O("autoplayDismissed");break;case "onHasPreviousNextChanged":Uga(this,a);break;case "requestAssistedSignIn":this.O("assistedSignInRequested",a.params.authCode);break;default:J7("Unrecognized action: "+a.action)}};
g.h.qI=function(){if(this.o){var a=this.o;this.o=null;this.La.videoId!=a&&O7(this,"getNowPlaying")}};
I7.prototype.subscribe=I7.prototype.subscribe;I7.prototype.unsubscribeByKey=I7.prototype.wc;I7.prototype.ia=function(){var a=3;this.ga()||(a=0,(0,window.isNaN)(this.H())?i6(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
I7.prototype.getProxyState=I7.prototype.ia;I7.prototype.C=function(a){J7("Disconnecting with "+a);L7(this);this.O("beforeDisconnect",a);1==a&&X4();h6(this.g,a);this.dispose()};
I7.prototype.disconnect=I7.prototype.C;I7.prototype.fa=function(){var a=this.La;this.o&&(a=this.La.clone(),v7(a,this.o,a.index));return w7(a)};
I7.prototype.getPlayerContextData=I7.prototype.fa;
I7.prototype.sa=function(a){var b=new q7(a);b.videoId&&b.videoId!=this.La.videoId&&(this.o=b.videoId,g.qr(this.I),this.I=g.or((0,g.A)(this.qI,this),5E3));var c=[];this.La.listId==b.listId&&this.La.videoId==b.videoId&&this.La.index==b.index||c.push("remoteQueueChange");this.La.g==b.g&&this.La.volume==b.volume&&this.La.muted==b.muted&&u7(this.La)==u7(b)&&g.qg(this.La.l)==g.qg(b.l)||c.push("remotePlayerChange");this.La.reset(a);(0,g.G)(c,function(a){this.O(a)},this)};
I7.prototype.setPlayerContextData=I7.prototype.sa;I7.prototype.V=function(){var a=this.g.C.id,b=g.Pa(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
I7.prototype.getOtherConnectedRemoteId=I7.prototype.V;I7.prototype.H=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.H)():window.NaN};
I7.prototype.getReconnectTimeout=I7.prototype.H;I7.prototype.X=function(){return this.A||"UNSUPPORTED"};
I7.prototype.getAutoplayMode=I7.prototype.X;I7.prototype.ba=function(){return this.F||""};
I7.prototype.getAutoplayVideoId=I7.prototype.ba;I7.prototype.wa=function(){if(!(0,window.isNaN)(this.H())){var a=this.g.l;g.Vp(a.g);a.start()}};
I7.prototype.reconnect=I7.prototype.wa;I7.prototype.ma=function(a,b){O7(this,a,b);P7(this)};
I7.prototype.sendMessage=I7.prototype.ma;g.F(U7,u6);g.h=U7.prototype;g.h.md=function(a){return this.oc.$_gs(a)};
g.h.contains=function(a){return!!this.oc.$_c(a)};
g.h.get=function(a){return this.oc.$_g(a)};
g.h.start=function(){this.oc.$_st()};
g.h.add=function(a,b,c){this.oc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.oc.$_r(a,b,c)};
g.h.zl=function(a,b,c,d){this.oc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.l.length;a<b;++a)this.oc.$_ubk(this.l[a]);this.l.length=0;this.oc=null;U7.ua.T.call(this)};
g.h.tJ=function(){this.O("screenChange")};
g.h.oG=function(){this.O("onlineScreenChange")};
H6.prototype.$_st=H6.prototype.start;H6.prototype.$_gspc=H6.prototype.uJ;H6.prototype.$_gsppc=H6.prototype.Lw;H6.prototype.$_c=H6.prototype.contains;H6.prototype.$_g=H6.prototype.get;H6.prototype.$_a=H6.prototype.add;H6.prototype.$_un=H6.prototype.zl;H6.prototype.$_r=H6.prototype.remove;H6.prototype.$_gs=H6.prototype.md;H6.prototype.$_gos=H6.prototype.Kw;H6.prototype.$_s=H6.prototype.subscribe;H6.prototype.$_ubk=H6.prototype.wc;var V7=null,W7=null,l8=null,$7=[];g.r(o8,g.J);g.h=o8.prototype;
g.h.T=function(){g.J.prototype.T.call(this);this.A.stop();this.B.stop();this.L.stop();this.U();this.g.unsubscribe("proxyStateChange",this.Fu,this);this.g.unsubscribe("remotePlayerChange",this.Oi,this);this.g.unsubscribe("remoteQueueChange",this.Uk,this);this.g.unsubscribe("autoplayUpNext",this.gu,this);this.g.unsubscribe("previousNextChange",this.Cu,this);this.g.unsubscribe("nowAutoplaying",this.yu,this);this.g.unsubscribe("autoplayDismissed",this.fu,this);this.g=this.H=null};
g.h.Ks=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(s8(this)){if(1081!=A7(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":A7(this.g).gb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.K.gh(c[0],c[1]);break;case "control_subtitles_set_track":t8(this,c[0]);break;case "control_set_audio_track":c=c[0],s8(this)&&this.g.xp(this.l.Y(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();u8(this,0==c?void 0:c);break;case "control_seek":u8(this,c[0]);break;case "control_subtitles_set_track":t8(this,c[0]);break;case "control_set_audio_track":c=c[0],s8(this)&&this.g.xp(this.l.Y(1).videoId,c)}};
g.h.CE=function(a){this.L.Vy(a)};
g.h.XI=function(a){this.Ks("control_subtitles_set_track",g.dc(a)?null:a)};
g.h.Xv=function(){var a=this.l.Lb("captions","track");g.dc(a)||t8(this,a)};
g.h.wu=function(a){if(s8(this)){this.g.unsubscribe("remotePlayerChange",this.Oi,this);var b=Math.round(a.volume);a=!!a.muted;var c=A7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.Oi,this)}};
g.h.IF=function(){g.dc(this.C)||v8(this,this.C);this.F=!1};
g.h.Fu=function(a,b){this.B.stop();2==b&&this.Uv()};
g.h.Oi=function(){if(s8(this)){this.A.stop();var a=A7(this.g);switch(a.g){case 1081:case 1:q8(this,new g.FE(8));this.Tv();break;case 1085:case 3:q8(this,new g.FE(9));break;case 1083:case 0:q8(this,new g.FE(2));this.K.stop();p8(this,this.l.Y().lengthSeconds);break;case 1084:q8(this,new g.FE(4));break;case 2:q8(this,new g.FE(4));p8(this,u7(a));break;case -1:q8(this,new g.FE(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.S("YTP_MDX_PLAYER_ERROR")},q8(this,new g.FE(128,a))}a=A7(this.g).l;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,v8(this,a));a=A7(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.P.isActive()||this.Dw()}else r8(this)};
g.h.Cu=function(){this.l.O("mdxpreviousnextchange")};
g.h.Uk=function(){s8(this)||r8(this)};
g.h.qy=function(){this.g.Jq()};
g.h.gu=function(a){a&&(a=g.Fr("/watch_queue_ajax",{method:"GET",hc:{action_get_watch_queue_item:1,video_id:a},ib:(0,g.A)(this.CH,this)}))&&(this.U=(0,g.A)(a.abort,a))};
g.h.CH=function(a,b){var c=new g.qD({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.O("mdxautoplayupnext",c)};
g.h.yu=function(a){(0,window.isNaN)(a)||this.l.O("mdxnowautoplaying",a)};
g.h.fu=function(){this.l.O("mdxautoplaycanceled")};
g.h.uB=function(a,b){-1==A7(this.g).g?u8(this,a):b&&this.g.Iw(a)};
g.h.Dw=function(){if(s8(this)){var a=A7(this.g);this.o.Pa(this.R);a.muted?this.l.mute():this.l.Ee();this.l.setVolume(a.volume);this.R=this.o.M(this.l,"onVolumeChange",this.wu)}};
g.h.Tv=function(){this.A.stop();if(!this.g.ga()){var a=A7(this.g);a.gb()&&q8(this,new g.FE(8));p8(this,u7(a));this.A.start()}};
g.h.Uv=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.r(y8,g.W);y8.prototype.o=function(a){x8(this,a.state)};g.r(z8,g.CU);z8.prototype.I=function(){var a=this.g.Lb("remote","receivers");a&&1<a.length&&!this.g.Lb("remote","quickCast")?(this.F=g.pb(a,this.A,this),g.DU(this,(0,g.I)(a,this.A)),a=this.g.Lb("remote","currentReceiver"),this.de(this.A(a)),this.enable(!0)):this.enable(!1)};
z8.prototype.A=function(a){return a.key};
z8.prototype.ce=function(a){return"cast-selector-receiver"==a?g.S("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
z8.prototype.zc=function(a){g.CU.prototype.zc.call(this,a);this.g.Pc("remote","currentReceiver",this.F[a]);this.o.qb()};g.r(A8,g.bM);g.h=A8.prototype;g.h.create=function(){Zga(g.qB(g.U(this.g)));this.C.push(g.vt("yt-remote-before-disconnect",this.zE,this));this.C.push(g.vt("yt-remote-connection-change",this.PG,this));this.C.push(g.vt("yt-remote-receiver-availability-change",this.Du,this));this.C.push(g.vt("yt-remote-auto-connect",this.NG,this));this.C.push(g.vt("yt-remote-receiver-resumed",this.MG,this));this.Du()};
g.h.load=function(){this.g.Wn();g.bM.prototype.load.call(this);this.B=new o8(this,this.g,this.l);var a=(a=n8())?a.currentTime:0;var b=k8()?new z7(f8(),void 0):null;0==a&&b&&(a=u7(A7(b)));0!=a&&(this.I=a||0,this.g.O("progresssync",a,void 0));w8(this,this.F,this.F);g.RV(this.g.app,6)};
g.h.unload=function(){this.g.O("mdxautoplaycanceled");this.A=this.o;g.Fe(this.B,this.l);this.l=this.B=null;g.bM.prototype.unload.call(this);g.RV(this.g.app,5)};
g.h.T=function(){g.wt(this.C);g.bM.prototype.T.call(this)};
g.h.yi=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.Ks.apply(this.B,[].concat([a],g.qa(c)))};
g.h.Sy=function(){return this.loaded?this.B.suggestion:null};
g.h.te=function(){return this.l?A7(this.l).te:!1};
g.h.hasNext=function(){return this.l?A7(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.WA=function(){var a=A7(this.l),b=this.g.Y();return{allowSeeking:this.g.qc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+s7(a):a.A,isPeggedToLive:1>=(a.C?a.o+s7(a):a.o)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.C?a.o+s7(a):a.o,seekableStart:0<a.B?a.B+s7(a):a.B}};
g.h.XA=function(){this.l&&this.l.Gw()};
g.h.YA=function(){this.l&&this.l.Hw()};
g.h.zE=function(a){1==a&&(this.K=this.l?A7(this.l):null)};
g.h.PG=function(){var a=k8()?new z7(f8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.K=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.Ee(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.g.Y().videoId&&this.g.Us(a.videoId,u7(a)));this.g.O("videodatachange","newdata",this.g.Y(),3)};
g.h.Du=function(){this.H=[this.o].concat($ga());var a=g8()||this.o;B8(this,a);this.g.la("onMdxReceiversChange")};
g.h.NG=function(){var a=g8();B8(this,a)};
g.h.MG=function(){this.A=g8()};
g.h.VA=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?o7():B8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&o7(),!0):!1}};
g.h.ZA=function(){F7(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Dc=function(){return!1};g.DR.remote=A8;})(_yt_player);
