'use strict';
require.config({
  baseUrl: '/assets/js'
  , paths: {
    backbone: '../components/backbone/backbone'
    , 'backbone-relational': '../components/backbone-relational/backbone-relational'
    , handlebars: '../components/handlebars/handlebars.runtime'
    , underscore: '../components/lodash/lodash'
    , webshims: 'libs/polyfiller'
    , jquery: '../components/jquery/jquery'
    , jqueryAjaxManager: '../components/Ajaxmanager/jquery.ajaxmanager'
    , jqueryCookie: '../components/jquery.cookie/jquery.cookie'
    , jqueryScrollTo: '../components/jquery.scrollTo/jquery.scrollTo.min'
    , jqueryHashChange: '../components/jquery-hashchange/jquery.ba-hashchange'
    , jqueryCycle: '../components/jquery-cycle/jquery.cycle.lite'
    , jqueryTubePlayer: '../components/jquery.TubePlayer/jQuery.tubeplayer'
    , jqueryList: 'libs/jquery.list.min'
    , jqueryScrollDepth: '../components/jquery-scrolldepth/jquery.scrolldepth'
    , hiatus: '../components/hiatus/hiatus'
    , text: '../components/requirejs-text/text'
    , transition: '../components/bootstrap-sass/js/bootstrap-transition'
    , templates: '_templates'
    , components: '../components'
    , modernizr: 'libs/modernizr.custom'
    , moment: '../components/moment/moment'
    , moment_timezone: '../components/moment-timezone/builds/moment-timezone-with-data.min'
    , accordion: '../components/jquery-ui-accordion/jquery-ui-accordion'
  }
  , urlArgs: 'v=' + '1c0pa0ha5' // automatically generated by Gruntfile.js on deploy or clear-cache
  , waitSeconds: 20
  , shim: {
    'backbone': {
      deps: ['underscore', 'modernizr'] // this depends on jquery as well, but jquery is a global that will just always be there
      , exports: 'Backbone'
    }
    , 'backbone-relational': {

      deps: ['underscore', 'backbone']
      , init: function(){
        // see: https://github.com/bestiejs/lodash/issues/172
        this._.findWhere = this._.find
      }
    }
    , 'underscore': {
      exports: '_'
    }
    , 'handlebars': {
      exports: 'Handlebars'
    }
    // webshims depends on modernizr and jquery
  }
})
