var __cvo={account:"eero",sitemap:{},server:"eero.sp1.convertro.com"};(function(){"undefined"===typeof window.$CVO&&(window.$CVO=[]);$CVO.ref_url=__cvo_urlfix("ref_url"in $CVO?$CVO.ref_url:document.referrer);$CVO.page_url=__cvo_urlfix("page_url"in $CVO?$CVO.page_url:document.URL);if($CVO.page_domain){var d=document.createElement("a");d.href=$CVO.page_url;$CVO.page_url=d.protocol+"//"+$CVO.page_domain+("/"==d.pathname.charAt(0)?"":"/")+d.pathname+d.search+d.hash}})();
$CVO.trackEvent=function(d,e,n){null!=d&&null==n&&(n=1,null==e&&(e="{type}-{userid}"));$CVO.push(["trackEvent",{type:d,id:e,amount:n}])};$CVO.trackUser=function(d,e){e=e||{};e.id=d;$CVO.push(["trackUser",e])};$CVO.getCode=function(d){if(!d)return $CVO.sid;var e=100,n=function(){$CVO.sid?d($CVO.sid):setTimeout(n,e*=1.1)};n()};$CVO.getOfflineCode=function(){return $CVO.mid};$CVO.setOfflineCode=function(d){$CVO.push(["setOfflineCode",d])};
$CVO.attachEvent=function(d,e,n,h){null==h&&(h=1,null==e&&(e="{type}-{userid}"));$CVO.push(["attachEvent",d,e,n,h])};$CVO.getVersion=function(){return 2136};$CVO.onUserDataReady=function(d){$CVO.push(["onUserDataReady",d])};function __cvo_overrides(){for(var d=/__cvo_([\w]+)=(.*?)(?:[^\w\.-]|$)/g,e,n=document.cookie+navigator.userAgent;null!=(e=d.exec(n));)__cvo[e[1]]=e[2]}function __cvo_hash(d){var e=5381,n=Math.pow(2,32);for(i=0;i<d.length;i++)var h=d.charCodeAt(i),e=(33*e+h)%n;return e}
function __cvo_urlfix(d){d.match(/^(https?%3A|)%2F%2F/i)&&(d=decodeURIComponent(d));0>d.indexOf("//")&&(d="//"+d);d.match(/^https?:/i)||(d=window.location.protocol+d);return d}
function __cvo_get_site_id(d){var e,n,h=document.createElement("a");d=h.href=d;e=("/"==h.pathname.charAt(0)?"":"/")+h.pathname;n=h.hostname;if("sitematch"in __cvo)for(var L=__cvo.sitematch,h=0;h<L.length;h++){var R=L[h],y="";switch(R[0]){case "url":y=d;break;case "path":y=e}var S=R[2];if(y.match(RegExp(R[1],"i")))return S}if("sitemap"in __cvo){d=__cvo.sitemap;for(e=[n,"."+n];e[e.length-1].match(/^\.[^.]+/);)e[e.length]=e[e.length-1].replace(/\.[^.]+/,"");e[e.length-1]=".";for(h=0;h<e.length;h++)if(n=
__cvo_hash(e[h]),n in d)return d[n]}return 0}function __cvo_get_tagvars(){return window.__cvo_params||{}}function __cvo_info(){$CVO.server=__cvo.server;$CVO.account=__cvo.account;$CVO.site_id=__cvo.site_id;$CVO.atHead=new Date;$CVO.atBody=$CVO.atHead;$CVO.tagvars=__cvo_get_tagvars()}
function __cvo_core(){var d=/(?:^|;\s)__cvo_server=(.*?)(?:;\s|$)/;if($CVO.tserver=document.cookie.match(d)||navigator.userAgent.match(d))$CVO.tserver=$CVO.tserver[1];__cvo_lif('<html><head></head><body><script src="//'+($CVO.tserver||$CVO.server)+"/trax/init/"+$CVO.account+"/"+$CVO.site_d+'">\x3c/script></body></html>')}
function __cvo_lif(d){var e,n=document.createElement("iframe");n.src='javascript:""';n.id="__cvo_iframe";n.style.cssText="width: 0; height: 0; border: 0; position: absolute; left: -2000px";document.body.insertBefore(n,document.body.firstChild);e=document.getElementById(n.id).contentWindow;try{e&&(e.document&&e.document.write)&&(e.document.write(d),e.document.close())}catch(h){n.src="javascript:var d=document.open();d.domain='"+document.domain+"';void(0);";try{e&&(e.document&&e.document.write)&&(e.document.write(d),
e.document.close())}catch(L){$CVO.error=L}}return e}function __cvo_run(){__cvo.site_id=__cvo_get_site_id($CVO.page_url);var d=__cvo.site_id+"";"exclude"!=d&&0!=d.length&&(__cvo_info(),__cvo_core())}
function __cvo_main(){__cvo_overrides();if(!window.__cvo_started){if(__cvo_started=!0,__cvo.loader){var d=document.createElement("script");d.type="text/javascript";d.async=!0;d.src="//stage.convertro.com/unitag/"+__cvo.account+"/"+__cvo.loader+".js";var e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(d,e);return!1}}else if(!__cvo.loader)return!1;__cvo_run();return!0}function __cvo_eval(d){return eval(d)}
function __cvo_core(){function d(a){for(var b,c,g,Ra,d="",e=0;e<a.length;){b=a.charCodeAt(e++);c=a.charCodeAt(e++);g=a.charCodeAt(e++);Ra=b>>2;b=(b&3)<<4|c>>4;c=(c&15)<<2|g>>6;g&=63;var f=a.length-e,d=d+y.charAt(Ra)+y.charAt(b);-2<f&&(d+=y.charAt(c));-1<f&&(d+=y.charAt(g))}return d}function e(a){return a.replace(/[a-zA-Z]/g,function(a){return String.fromCharCode(("Z">=a?90:122)>=(a=a.charCodeAt(0)+13)?a:a-26)})}function n(a){var b=document.createElement("a");b.href=a;return b}var h="$Rev$",L=h.match(/\d+/),
R=function(a){return String(a)},h=L?L[0]:"unknown";(function(){function a(a){c.lastIndex=0;return c.test(a)?'"'+a.replace(c,function(a){var b=e[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function b(c,e){var q,p,l,m,n=g,h,w=e[c];"function"===typeof f&&(w=f.call(e,c,w));switch(typeof w){case "string":return a(w);case "number":return isFinite(w)?String(w):"null";case "boolean":case "null":return String(w);case "object":if(!w)return"null";g+=d;
h=[];if("[object Array]"===Object.prototype.toString.apply(w)){m=w.length;for(q=0;q<m;q+=1)h[q]=b(q,w)||"null";l=0===h.length?"[]":g?"[\n"+g+h.join(",\n"+g)+"\n"+n+"]":"["+h.join(",")+"]";g=n;return l}if(f&&"object"===typeof f)for(m=f.length,q=0;q<m;q+=1)"string"===typeof f[q]&&(p=f[q],(l=b(p,w))&&h.push(a(p)+(g?": ":":")+l));else for(p in w)Object.prototype.hasOwnProperty.call(w,p)&&(l=b(p,w))&&h.push(a(p)+(g?": ":":")+l);l=0===h.length?"{}":g?"{\n"+g+h.join(",\n"+g)+"\n"+n+"}":"{"+h.join(",")+"}";
g=n;return l}}var c=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g,d,e={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},f;R=function(a,c,e){var q;d=g="";if("number"===typeof e)for(q=0;q<e;q+=1)d+=" ";else"string"===typeof e&&(d=e);if((f=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("stringify");return b("",{"":a})}})();var y="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_",
S="createElement",S="createElement",ga="domain",N="match",N="match",ga="domain",ha=window.__cvo?1:0,wa,O=window,T=ha?window:window.parent,E=document,v=ha?document:window.parent.document,B=navigator,f=O.$CVO=T.$CVO,I=[],ia={},Sa=(new Date).getTime(),Y=v.location.protocol,Z=f.server,vb=window.screen.width+"x"+window.screen.height+"x"+window.screen.colorDepth,xa=function(){var a=[];if(B.plugins)for(var b=B.plugins.length,c=0;c<b;c++){var g=B.plugins[c];if(g){var d=g.filename.replace(/\.(plugin|dll)$/i,
""),e=g.name,g=(g.description[N](/\d/g)||[]).join(""),e=(e[N](/\d/g)||[]).join("");a.push(d+","+(g.length>e.length?g:e))}}return a.join(";")}(),ja="";if(!f.skip&&!O.__cvo_skip){f.W=O;f.D=E;f.L=I;f.showlog=function(){alert(I.join("\n"))};var ya=function(){return((new Date).getTime()-Sa)/1E3},l=function(a){I.push(ya().toFixed(3)+" - "+a)},$=function(a){a="string"==typeof a?a:a.toString();I.push(ya().toFixed(3)+" ~ "+a);var b=O.console;b&&b.log&&(b.log("warning"),b.log(a))},U=function(a){var b;b="string"==
typeof a?a:a.toString();I.push(ya().toFixed(3)+" ! "+b);(b=O.console)&&b.log&&(b.log("error"),b.log(a),b.log(I));f.error=a};f.INFO=l;f.WARN=$;f.ERROR=U;try{var aa=function(){for(var a=3,b=document.createElement("div"),c=b.all||[];b.innerHTML="\x3c!--[if gt IE "+ ++a+"]><br><![endif]--\x3e",c[0];);return 4<a?a:!a}(),wb=(B.userAgent[N](/\bAndroid ([\d\.]+)/)||[])[1],xb=(B.userAgent[N](/; Googlebot\/([\d\.]+)/)||[])[1],Ta=aa?8>aa?2083:9>aa?4096:65535:65535,yb=f.atHead.getTime(),Ua=f.tagvars||{},Va=Y+
"//d1ivexoxmp59q7.cloudfront.net/2.gif",V,J,ba,za,ka,Aa,la=Number("1"),zb=Number("0"),Ab=Number("0"),K=Number("6"),Ba=Number("0"),ca=Number("0"),Ca=Number("0"),P=Number("1"),Da=Number("10000"),Bb=Number("0"),Ea=Number("1"),ma=la?T.__cvo.site_id:"",Fa=T.__cvo_hash||function(){U("ZOMGG2")},Ga=P?"ptrx":"trax";if(T.__cvopag)var W="",Wa="",H="",Xa="";var Ya="",Ha=[],Ia=[],Za=[],$a=0,Ja=[],na=0,ab=0,oa=0,C=function(a){bb(a);V&&(Ba&&t!=m)&&(Q(function(){l("ss-fcb: F* "+m);J.set("cvo_sid1",m)}),t=m)},bb=
function(a){f.sid=m=a;m.length?pa("cvo_sid1",m,5E3):qa("cvo_sid1")},ra=function(a){(f.mid=F=a)&&F.length?pa("cvo_mid1",F,5E3):qa("cvo_mid1")},X=function(a){var b=wa?wa.document:E,c=b[S]("script");c.src=a;a=b.getElementsByTagName("script")[0];a.parentNode.insertBefore(c,a)};Number("0")&&(X=function(a){(new Image).src=a});var pa=function(a,b,c,g){if(c){var d=new Date;d.setTime(d.getTime()+864E5*c);c="; expires="+d.toGMTString()}else c="";d="";g||(g=/[^.]*.(?:[^.]*|..\...|...\...)$/.exec(E[ga])[0]);
d="; "+ga+"=."+g;E.cookie=a+"="+b+c+("; path=/"+d)},da=function(a){a=RegExp("^ *"+a+"=");for(var b=E.cookie.split(";"),c=b.length;c--;){var g=b[c].replace(a,"");if(g!=b[c])return g}return null},qa=function(a){pa(a,"",-1);E.cookie=a+"=; expires=Thu, 01-Jan-70 00:00:01 GMT;"},ea=function(a,b,c){var g=a.indexOf(b);if(-1==g)return null;a=a.substr(g+b.length);c=a.indexOf(c);return-1==c?a:a.substr(0,c)},Cb=function(a){var b=0;if(document.selection)a.focus(),b=v.selection.createRange(),b.moveStart("character",
-a.value.length),b=b.text.length;else if(a.selectionStart||"0"==a.selectionStart)b=a.selectionStart;return b},Db=function(a,b){if(a.createTextRange){var c=a.createTextRange();c.move("character",b);c.select()}else if(a.selectionStart||"0"==a.selectionStart)a.selectionStart=b,a.selectionEnd=b,a.focus()},sa=function(a,b){("object"===typeof HTMLElement?b instanceof HTMLElement:b&&"object"===typeof b&&1===b.nodeType&&"string"===typeof b.nodeName)&&a(b);var c=100,g=function(){var d=v.getElementById(b);
d?a(d):setTimeout(g,c*=1.1)};g()},cb=function(a){var b=50,c=function(){E.body?a():setTimeout(c,b*=1.1)};c()};f.run=function(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];b=a.shift();a=ia[b].apply(null,a);Ka();return a};f.pos=0;f.push=function(){for(var a=0;a<arguments.length;a++)f[f.length]=arguments[a];Ka()};var Ka=function(){var a,b;if(oa&&u)for(;f.pos<f.length;)try{if(!(f.pos>=f.length)){var c=f[f.pos++];if(!c||"function"!=typeof c.slice)throw"Non-array element in $CVO";var g=c.slice(0);
if(!g.length)throw"Empty array element in $CVO";var d=g.shift();ia[d].apply(null,g)}}catch(e){U(e)}},r=null,La=null,db=null,Eb=function(a){sa(function(a){var c=m.match(/^[10]/)?m:m.substr(0,K);"INPUT"==a.tagName?a.value=m:a.innerHTML=c;l("% "+c)},a)},Ma=function(a){if((a=a||T.event)&&a.keyCode){var b=a.keyCode,c=48<=b&&105>=b,g=!1;if(!b.toString()[N](/^(8|9|3[4567890]|46)$/)&&!c)g=!0;else if(c&&r.value&&r.value.length>=K)if(window.getSelection)g=r.selectionStart==r.selectionEnd;else if(b=v.selection){g=
r.value;c=b.createRange().duplicate();c.moveEnd("character",g.length);var d=""==c.text?g.length:g.lastIndexOf(c.text),c=b.createRange().duplicate();c.moveStart("character",-g.length);g=d==c.text.length}g&&(a.stopPropagation?(a.stopPropagation(),a.preventDefault()):(a.cancelBubble=!0,a.returnValue=!1))}var e=eb();e!=db&&(db=e,!e||e.length<K?(ra(),fb()):(e!=r.value&&(a=Cb(r),r.value=e,Db(r,a)),r.style.border="solid 2px orange",La&&clearTimeout(La),La=setTimeout(function(){gb(e)},100)))},fb=function(){r.style.border=
"dashed 2px red"},Fb=function(a){a.innerHTML="";var b=r=v[S]("input");b.id="__cvo_input_code";var c=K-0;b.setAttribute("size",c+3);b.setAttribute("maxlength",c);b.setAttribute("autocomplete","off");b.style.textTransform="uppercase";b.style.outline="none";b.value=(F||"").substr(0,K);b.onchange=b.onblur=b.onkeydown=b.onclick=b.onkeyup=function(a){Ma(a)};Ma();a.appendChild(b)},gb=function(a){X(Y+"//"+Z+"/"+Ga+"/code/eero/"+ma+"/?code="+a)},eb=function(){return r.value.toUpperCase().replace(/[^A-Z0-9]/g,
"").substr(0,K)},ta=[],hb=!1,ib=!1,Na={},Oa=function(a){var b={};for(k in a)a.hasOwnProperty(k)&&(b[k]=a[k]);return b},jb=function(a){if(a)a(m);else return m},Pa=function(a){return n(a).hostname.match(/\bintuit\.com$/)?a.replace(/([&?])(authid|uid|username|app|pt|TTOBUid|TTOBFiId|authFormUserID|userid|\w*email)=[^&?]*/gi,"$1cvo_sanitized_$2="):a.replace(/([&?])(\w*email)=[^&?]*/gi,"$1cvo_sanitized_$2=")},fa=function(a,b,c){var g="string"!=typeof a?Oa(a):{type:a,id:b,value:c};if(a=g.attach)delete g.attach,
l("te-a: attaching "+a),sa(function(a){var b="",c="",d="";try{b=a.tagName.toLowerCase(),c=(a.id||"").toLowerCase(),d=(a.name||"").toLowerCase()}catch(e){$(e)}var f,q;if("a"==b)f="onclick",q=function(){var b=!1;document.createEvent?(b=document.createEvent("MouseEvents"),b.initMouseEvent("click",!0,!0,window,0,0,0,0,0,!1,!1,!1,!1,0,null),b=!a.dispatchEvent(b)):a.fireEvent&&(b=!a.fireEvent("onclick"));b||(window.location=a.href)};else if("form"==b)f="onsubmit",q=function(){a.submit()};else{U("te-a: <"+
b+"> is not supported");return}g.cvosrc?l("te-a: attached cvosrc "+g.cvosrc+" on "+b+" <"+c+">"+d):(g.type=g.type||"dom-"+(d||c||tagname),l("te-a: attached typ "+g.type+" on "+b+" <"+c+">"+d));var h=a[f];g.cb=function(){a[f]=h;q()};a[f]=function(){fa(g);return!1}},a);else{b=String(g.id||"");a=g.type||"";c=g.value||g.amount||g.sp;var d=g.cvosrc||T.__cvosrc,q=g.domain,M=Number(na>=f.pos),s=M?null:g.cb;Za[++$a]=s;s=Qa&&F?F:m;a&&!b&&(b="{t}-{c}");for(var z=/{\s*(\w+)\s*(\d*)\s*}|$/g,A=0,p="";null!=(match=
z.exec(b));){p+=b.substr(A,match.index-A);if(match.index==b.length)break;A=match[2]||32;switch(match[1]||""){case "random":case "r":p+=Math.random().toString().substr(2,A);break;case "type":case "t":p+=a?a.toString().substr(0,A):"NULL";break;case "phone":case "p":p+=s.substr(0,Math.max(A,K));break;case "cvoid":case "cid":case "c":p+=s.substr(0,A);break;case "userid":case "uid":case "u":p+=s.substr(0,A);break;case "date":case "d":var r=new Date,A=("0"+r.getDate()).slice(-2),y=("0"+(r.getMonth()+1)).slice(-2),
r=r.getFullYear(),p=p+(""+r+y+A)}A=z.lastIndex}b=p||b;null==c&&(c=1);s="page_url"in f?f.page_url:v.URL;z="ref_url"in f?f.ref_url:v.referrer;ka?Aa?(s=ba,z=za):z=ba:ba&&(z=za,s=ba);z=Pa(z);s=Pa(s);z.match("://$")&&(z="");p=n(s);d&&(s=0<s.indexOf("?")?s+"&cvojssrc=1&cvosrc="+d:s+"?cvojssrc=1&cvosrc="+d);q&&(s=p.protocol+"//"+q+("/"==p.pathname.charAt(0)?"":"/")+p.pathname+p.search+p.hash);var z=z.replace(/^https:\/\/www.facebook.com\/dialog\/oauth\?/,p.protocol+"//"+p.host+"/facebook-oauth-cvorewrite?"),
t;for(t in Ua)s+="&"+t+"="+encodeURIComponent(Ua[t]);kb(["trackEvent",a,b,c,ma]);l(">> te: "+m+"; "+a+"; "+b+"; "+c);d=Number(!u);(new Date).getTime();q=ua?"&tst="+ua:"";t=Y+"//"+Z+"/trax2/eero/"+ma+"/"+Ga+"/hit";b=t+"?sid="+(m||"")+"&mid="+(F||"")+"&eid="+b+"&cid="+(u||"")+"&jid=&typ="+a+"&val="+c+"&isa="+(Qa||"")+"&pag="+encodeURIComponent(s)+"&ref="+encodeURIComponent(z)+"&fup="+M+"&cbi="+$a+"&new="+d+"&nji="+zb+q+"&ver="+h+"&sts=1466805333&bts="+(new Date).getTime()+"&ath="+f.atHead.getTime()+
"&atb="+f.atBody.getTime()+"&dis="+vb;aa&&9<=aa&&(b+="&jua="+encodeURIComponent(B.userAgent));q="";if(P){M=Ea?e(ja):ja;d=Ea?e(xa):xa;c="";ca&&(c+="&lid="+(W||""));q="&tid="+H+c+"&tmz="+(new Date).getTimezoneOffset()+"&pfe="+(Ea?"1":"0");c=q+"&ish=1";d=q+"&ish=0"+("&plu="+encodeURIComponent(d));c+="&plu="+Fa(xa);Ca&&(d+="&fon="+encodeURIComponent(M),c+="&fon="+Fa(ja));if(ua&&(M=ua.match(/^(\w+)-(\d+)$/))&&"bigget"==M[1])for(A=M[2],d+="&foo=";A--;)d+="A";q=c}b+=q;c="&log="+encodeURIComponent(I.join("\n"));
b+=Ta>b.length+c.length?c:"";Ta<b.length&&(b=t+"?ovz=1&sid="+(m||""));X(b);lb&&!a.length&&mb(lb)}},nb=function(a){if(!ab){if(Bb){var b=v.referrer[N](/\/\/([^\/]*)/);if(b&&b[1]&&b[1]==v[ga]){l("Xi");return}}fa(a||{});ab=1}},mb=function(a){a=a instanceof Object?Oa(a):{id:a};var b=a.id;("string"==typeof b||"object"==typeof b&&b.constructor===String)&&0<b.indexOf("@")&&(a.id="hashed-"+Fa(b));var c=/^\w+$/,b=Y+"//"+Z+"/"+Ga+"/user/eero/"+ma+"/?bts="+(new Date).getTime()+"&sid="+m,d=[],e;for(e in a)if(c.test(e)){var f=
"string"==typeof a[e]?a[e]:R(a[e]);d.push(e+"="+encodeURIComponent(f))}d.length&&(e=Pa(v.URL),b+="&"+d.join("&"),b+="&pag="+encodeURIComponent(e),b+="&log="+encodeURIComponent(I.join("\n")),kb(["trackUser"]),l(">> tu: "+m),X(b))},kb=function(a){Ha.push(a);for(var b=0;b<Ia.length;b++){for(var c=Ia[b],d=c[c.length-1],e=1,f=0;f<c.length-1;f++)c[f]!=a[f]&&(e=0);e&&d(a)}},Q=function(a){J?a():V?Ja.push(a):U("afo: wtf")},G=function(){oa=1;f.is_agent=Qa=Number(Ab)||m&&Number("0"==m.charAt(0));nb();Ka()},
pb=function(){if(P)if(va=ob(H),l("i.p: T "+va),D?(l("i.p.u: U "+D),D.match(/[10]/)&&C(D)):u?(l("i.p.c.m: C "+u),u.match(/[10]/)||C(va)):C(va),V){var a=setTimeout(function(){$("i.p.f.e-to");G()},Da);Q(function(){clearTimeout(a);oa?l("i.p.f-cb.tr: L "+W):(l("i.p.f-cb.e: L "+W),G())})}else G();else V&&Ba?(Q(function(){t=J.get("cvo_sid1");l("i.f: F "+t)}),D?(l("i.f.u: U "+D),C(D),G()):u?(l("i.f.c: C "+u),Q(function(){t?t!=u?(l("i.f.c-cb: F+"),C(t),na=f.pos,f.pos=0,G()):l("i.f.c-cb: F="):(l("i.f.c-cb: F-"),
C(u))}),f.sid=m=u,G()):(l("i.f.e: J "+(la?"static":"")),a=setTimeout(function(){$("i.f.e-to");la||bb("");G()},Da),Q(function(){clearTimeout(a);oa?t?t!=m?(l("i.f.e-cb.t: F+"),C(t),na=f.pos,f.pos=0,G()):l("i.f.e-cb.t: F="):l("i.f.e-cb.t: F-"):(t?(l("i.f.e-cb.e: F+ "),C(t)):(l("i.f.e-cb.e: F-"),la||C("")),G())}))):(C(D||u||""),l("i.e: "+(D?"U":u?"C":"J")+" "+m),G())},ob,qb;(function(){function a(a,b,d){for(var e=[];0<a.length;){var f;f=b;for(var l=d,h=[],m=0,p=0;p<a.length;p++){x=a[p];var m=x+m*f,n=
Math.floor(m/l),m=m%l;(h.length||n)&&h.push(n)}f=[h,m];a=f[0];e.unshift(f[1])}return e}var b="23456789ABCDEFGHJKMNPQRSTUVWXYZ".split("");ob=function(c){var d,e,f,l,m;d="";for(var h=0;h<c.length;)e=y.indexOf(c.charAt(h++)),f=y.indexOf(c.charAt(h++)),l=y.indexOf(c.charAt(h++)),m=y.indexOf(c.charAt(h++)),e=e<<2|f>>4,f=(f&15)<<4|l>>2,l=(l&3)<<6|m,m=c.length-h,d+=String.fromCharCode(e),-2<m&&(d+=String.fromCharCode(f)),-1<m&&(d+=String.fromCharCode(l));h=[];for(c=0;c<d.length;c++)h.push(d.charCodeAt(c));
d=a(h,256,b.length);h="";for(c=0;c<d.length;c++)h+=b[d[c]];for(;12>h.length;)h=b[0]+h;return h};qb=function(c){for(var e=[],f=0;f<c.length;f++)e.push("23456789ABCDEFGHJKMNPQRSTUVWXYZ".indexOf(c.charAt(f)));c=a(e,b.length,256);e="";for(f=0;f<c.length;f++)e+=String.fromCharCode(c[f]);for(;8>e.length;)e="\x00"+e;return d(e)}})();var rb=function(){var a=[];if(window.crypto&&window.crypto.getRandomValues&&window.Uint8Array)a=new Uint8Array(8),window.crypto.getRandomValues(a);else for(var b=8;b--;)a[b]=
0;for(var c="",b=8;b--;)c+=String.fromCharCode((7==b?7:255)&(256*Math.random()^a[b]));return d(c)},Gb=function(){var a=da("cvo_tid1");a?(l("iCT val: "+a),a=a.split("|"),H=a[0],Xa=a[1]):u&&!u.match(/[10]/)?(H=qb(u),l("iCT s2t: "+H)):(H=rb(),l("iCT gen: "+H))},sb=function(){if(P&&(Gb(),l("$iP: "+H),V)){var a=setTimeout(function(){$("$iP.f-to")},Da);Q(function(){clearTimeout(a);if(ca&&ca){var b=J.get("cvo_tid1");b?(b=b.split("|"),W=b[0],Wa=b[1]):(W=rb(),lso_tid_ts=null)}Ca&&(ja=J.fonts().join(";"))})}},
Hb=function(){l("F");O.__cvo_f_loaded=function(a){J=a||E.getElementById("__cvo_f");f.F=J;for(l("fld");Ja.length;)Ja.shift()()};var a;a='<object id="__cvo_f_not" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"><param name=Movie value="'+Va+'"><param name=AllowScriptAccess value="always"><embed id="__cvo_f" allowscriptaccess="always" style="" src="'+Va+'" type="application/x-shockwave-flash"/></embed></object>';if(ha)Ya=a;else{var b=E[S]("div");b.style.position="absolute";b.style.left="-2000px";
b.style.display="inline";cb(function(){var c=E.body;c.insertBefore(b,c.firstChild);b.innerHTML=a})}},ia={trackPage:nb,trackEvent:fa,trackSource:function(a){a="string"!=typeof a?Oa(a):{cvosrc:a};fa(a)},trackUser:mb,attachEvent:function(a,b,c,d){l("aE: "+a);fa({id:b,type:c,value:d,attach:a})},trackEventDone:function(a,b){var c=Za[a];"function"==typeof c&&c(b)},showCode:Eb,skipRun:function(a){for(var b=[],c=1;c<arguments.length;c++)b.push(arguments[c]);Aa=1;ia[a].apply(null,b);Aa=0},setOfflineCode:function(a){r&&
(r.value=a);gb(a)},inputCode:function(a){"0"==m.charAt(0)&&sa(function(a){Fb(a)},a)},gotCode:function(a,b){r&&eb()!=a?Ma():(ra(b),r&&(b?r.style.border="solid 2px limegreen":fb()))},showEnteredCode:function(a){sa(function(a){var c=F?F.substr(0,K):"NOCODE";a.innerHTML=c},a)},setUserSid:function(a){m!=a&&C(a);u=m},resetCode:function(){ra("")},loadScript:X,onTrackReady:function(a){na>f.pos||a()},onAction:function(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];Ia.push(a);for(var c=a[a.length-
1],b=0;b<Ha.length;b++){for(var d=Ha[b],e=1,f=0;f<a.length-1;f++)a[f]!=d[f]&&(e=0);e&&c(d)}},stampTids:function(a){var b=(0|Number(new Date)/1E3)-a,c=H+"|"+(Xa||a)+"|"+a+"|"+b;pa("cvo_tid1",c,5E3);ca&&(c=W+"|"+(Wa||a)+"|"+a+"|"+b,Q(function(){l("$st: F* "+c);J.set("cvo_tid1",c)}));u=m},setServer:function(a){Z=f.server=a},onUserDataReady:function(a){hb?a(Na):ta.push(a);ib||(ib=!0,l(">> ud: "+m),a=Y+"//"+Z+"/uda/da1/eero/?sid="+(m||"")+"&ver="+h+"&bts="+(new Date).getTime(),X(a))},recvUserData:function(a){Na=
a;hb=!0;for(a=0;a<ta.length;a++)if("function"==typeof ta[a])ta[a](Na)},getCode:jb,getSid:jb},t,va,m,F,Qa,D=ea(v.URL,"cvo_sid1=","&"),u=da("cvo_sid1")||f.csid,tb=ea(v.URL,"cvo_mid1=","&");tb?ra(tb):f.mid=F=da("cvo_mid1");if("all"==ea(v.URL,"cvo_optout=","&")){var Ib=v.referrer,ub=document.createElement("a");ub.href=Ib;ub.hostname.match(/\b(?:youtube|conduit)\.com$/)||(D="100000000000")}var ua=ea(v.URL,"cvotest=","&"),lb=ea(v.URL,"cvo_user=","&"),P=P&&!(D+" "+u).match(/[10]/);(function(){var a=da("__cvo_skip_doc");
if(a){var a=a.replace(/%7C(?=https?%3A%2F%2)/,"|"),b=da("__cvo_skip_run");qa("__cvo_skip_doc");qa("__cvo_skip_run");a=a.split("|");ba=decodeURIComponent(a[0]);za=decodeURIComponent(a[1]);if(b)for(b=decodeURIComponent(b),l("sk.r: "+b),ka=__cvo_eval("["+b+"]"),b=ka.length;b--;)a=ka[b],a.unshift("skipRun"),f.unshift(a);else l("sk.d")}})();l("@ "+((Sa-yb)/1E3).toFixed(3));(V=function(){if(B.plugins&&B.plugins["Shockwave Flash"]){if(B.plugins["Shockwave Flash"].description&&(!B.mimeTypes||!B.mimeTypes["application/x-shockwave-flash"]||
B.mimeTypes["application/x-shockwave-flash"].enabledPlugin))return!0}else if(O.ActiveXObject)try{if(new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))return!0}catch(a){}return!1}()&&!wb&&!xb&&(Ba||P&&(ca||Ca)))&&Hb();if(ha){var Jb='<html><head><script>var Wp=window.parent;var $CVO=Wp.$CVO;function __cvo_f_loaded(){Wp.__cvo_f_loaded(document.getElementById("__cvo_f"));}\x3c/script></head><body><div>'+Ya+"</div></body></html>";cb(function(){wa=__cvo_lif(Jb);sb();pb()})}else sb(),pb()}catch(Kb){U(Kb)}}}
Number("1")||__cvo_core();__cvo_main()&&$CVO.push(["trackPage"]);
