(function() {(function(d){function k(a){this.id=a;this.b=this.url=0;this.B=[];this.$=this.ca=this.H=0;this.L=null;return this}function x(a,b,c){this.ta=a;this.b=b;this.url=c;this.end=this.start=0;this.f=[];this.A=this.T=this.I=this.c=0;this.da=!1;return this}function r(a,b){this.id=a;this.j=this.o=0;this.W=this.ia();this.P="";this.element=null;this.va(b);return this}function t(a){this.id=a;this.startTime=this.b=this.max=this.total=this.count=0;return this}function p(a,b,c,l){this.t=a;this.g=b;this.la=c;this.xa=
l;this.r=b+l;this.S=a+c;return this}function u(a,b){for(;b;){if(b==a)return!0;b=b.parentElement}return!1}function N(a,b){E[a]=b}function O(a){var b=!0;if(a=new r(a+"_0",0),!a.W)return-1;a&&a.ka();a&&a.ea()?C[0]=a:b=!1;return b?1:0}function A(a){return 999==a||isNaN(a)||0>a}function B(a,b,c){var l,e;b&&(e="v:1.3.2,rand:"+a.b,1==c?(l=a.i?30:a.ha?50<=a.l&&!a.hidden?32:31:34+a.ua,e=a.hidden?e+",iv:0,hdn:1":e+(",iv:"+(a.i?"NA":a.l)),0<a.R&&(e+=",tm:"+a.R),0<a.c&&(e+=",fp:"+a.c),a.i&&a.U&&(e+=",flc:"+a.U),
32==l&&a.N&&a.M&&(e+=",top:"+a.N,e+=",left:"+a.M)):2==c?(l=41,e+=",ao:"+a.ga):3==c?(l=42,e+=",hc:"+a.count+",hd:"+a.duration+",hx:"+a.max):4==c?(l=43,e+=",dur:"+a.duration,0<a.Z&&(e+=",hc:"+a.Z+",hd:"+a.ma+",hx:"+a.na)):5==c&&(l=44+a.sa,0<a.c&&(e+=",fp:"+a.c),0<a.A&&(e+=",td:"+a.A),e+=",iva:"+a.qa,e+=",tls:"+a.start+",tle:"+a.end,e+=",tlc:"+a.count+",tliv:"+a.ra),b=b.replace(/%e/,l.toString(16).toUpperCase()),b=b.replace(/%f/,a.a.toString(16).toUpperCase()),b=b.replace(/%g/,e),"https:"==document.location.protocol&&
(b=b.replace(/^http:/i,"https:")),P(b))}function P(a){var b=new Image(1,1);b.src=a;b.onload=b.onerror=function(){b.onload=b.onerror=null}}function J(a,b,c,l){var e=a?a.id||"ad":"frame";b=b||{};var n=d!=top,m,g,h=999,v=b.a||0,f=!1;b.D&&((g=y.ioStatusList[e])?(m=g.intersectionRect.width*g.intersectionRect.height/(g.boundingClientRect.width*g.boundingClientRect.height),h=Math.floor(100*m),m=g.boundingClientRect.top-g.rootBounds.top,g=g.boundingClientRect.left-g.rootBounds.left):(h=0,g=m=""),v|=2,f=!0);
if(b.w&&!f){m=new p(screen.availTop||0,screen.availLeft||0,screen.availHeight,screen.availWidth);g=new p(void 0!==d.screenY?d.screenY:d.screenTop,void 0!==d.screenX?d.screenX:d.screenLeft,void 0!==d.outerHeight?d.outerHeight:screen.availHeight,void 0!==d.outerWidth?d.outerWidth:screen.availWidth);n?f=new p("undefined"==typeof d.mozInnerScreenY?d.screenTop:d.mozInnerScreenY,"undefined"==typeof d.mozInnerScreenX?d.screenLeft:d.mozInnerScreenX,d.innerHeight,d.innerWidth):(h=a.getBoundingClientRect(),
f=new p(g.t+h.top,g.g+h.left,l?l:h.bottom-h.top,c?c:h.right-h.left));h=f.J(m.J(g)).G();e=f.G();m=(f.t-g.t).toFixed();g=(f.g-g.g).toFixed();if(!n&&document&&document.documentElement){g=m=0;for(f=a;f;)m+=f.offsetLeft,g+=f.offsetTop,f=f.offsetParent;g=new p(g,m,l?l:a.offsetHeight,c?c:a.offsetWidth);c=new p(d.scrollY||d.pageYOffset||document.body&&document.body.scrollTop||0,d.scrollX||d.pageXOffset||document.body&&document.body.scrollLeft||0,document.documentElement.clientHeight,document.documentElement.clientWidth);
m=g.J(c);h=Math.min(h,m.G());m=(g.t-c.t).toFixed();g=(g.g-c.g).toFixed()}h=0<e?parseInt(h/e*100,10):0;v|=2}b.O&&(n||0<a.offsetWidth&&0<a.offsetHeight)&&(n?(n=document.elementFromPoint(0,0),c=document.elementFromPoint(0,d.innerHeight-1),l=document.elementFromPoint(d.innerWidth-1,0),e=document.elementFromPoint(d.innerWidth-1,d.innerHeight-1),f=document.elementFromPoint(d.innerWidth/2,d.innerHeight/2)):(f=a.getBoundingClientRect(),n=u(a,document.elementFromPoint(f.left+1.25,f.top+1.25)),c=u(a,document.elementFromPoint(f.right-
1.25,f.top+1.25)),l=u(a,document.elementFromPoint(f.left+1.25,f.bottom-1.25)),e=u(a,document.elementFromPoint(f.right-1.25,f.bottom-1.25)),f=u(a,document.elementFromPoint((f.left+f.right)/2,(f.top+f.bottom)/2))),h=Math.min([0,25,50,90,99,100][(n?1:0)+(c?1:0)+(l?1:0)+(e?1:0)+(f?1:0)],h),f||(h=Math.min(50,h)),v|=4);n=0;b.m&&(b=C[0],n=(b=!(!b||!E[b.id]))?100:0,b||(n=Math.min(50,n)),h=n,n=1);A(h)&&(h=0,v|=8);return{timestamp:(new Date).getTime(),F:a,l:h,N:m,M:g,a:v,c:n,hidden:!!(document.webkitHidden||
document.mozHidden||document.msHidden||document.hidden),h:document.webkitHidden||document.mozHidden||document.msHidden||document.hidden?0:h}}function K(){var a=d!=top,b={D:!1,w:!a,O:!a,m:!1,V:!1};1==y.u&&(b.D=!0);var c=navigator.userAgent;/iPhone|iPad|iPod/i.test(c)?b.w=!1:/Android/i.test(c)?b.w=!1:/msie/i.test(c)||/windows.*trident/i.test(c)?b.O=!0:/firefox/i.test(c)?b.w=!0:/chrome/i.test(c)?b.m=b.D?!1:a:/webkit/i.test(c)&&(b.m=a);b.i=a&&!b.w&&!b.O&&!b.D;b.a=0;a&&(b.a|=1);return b}function Q(){var a,
b;try{a="{";for(var c=location.ancestorOrigins.length,l=0;l<c;l++)a=a+"'"+location.ancestorOrigins.item(l)+"'",1<c-l&&(a+=",");b=R(a+"}");return b=b.replace(/=+$/,"$'")}catch(e){}}function R(a){return btoa(encodeURIComponent(a).replace(/%([0-9A-F]{2})/g,function(a,c){return String.fromCharCode("0x"+c)}))}function L(a,b,c,l){function e(e){var d=0;if(w.m){if(w.V)d=3;else try{var f=C[0];if(f&&f.pa())w.i=!1;else if(d=f&&f.element?1:2,!e)return}catch(g){d=2}-1!=u&&(clearInterval(u),u=-1);-1!=x&&(clearTimeout(x),
x=-1)}if(w.i)try{B({F:a,a:w.a,i:!0,U:d,R:0,b:h},b,1)}catch(g){}else try{var k=J(a,w,c,l);k.ha=!0;k.b=h;var p=50<=k.l&&!k.hidden;q&&(q.ca=k.timestamp,q.L=k);A++;B(k,b,1);p&&(z=k.timestamp);D=p;r=setInterval(n,100);t=setTimeout(m,36E5)}catch(g){}}function n(){try{if(10<=A||F)return m(),!1;var e=J(a,w,c,l),f=50<=e.l&&!e.hidden;q&&q.add(e);var g=!1,n=!1;f&&(D&&(k=e.timestamp-z),k>=d._mpiv.oa[p]&&(0===p&&(q&&q.wa(),n=!0),e.ua=p,p++));e.R=k;e.b=h;n&&(A++,B(e,b,1));f&&!D&&(z=e.timestamp);!f&&D&&(k=0);D=
f;(g=q&&1===q.H&&q.X()&&q.s().K())&&m();return!g}catch(r){return m(),!1}}function m(){-1!=r&&(clearInterval(r),r=-1);-1!=t&&(clearTimeout(t),t=-1);for(var a=C.length;a--;){var b=C[a];b&&b.element&&b.element.remove();C[a]=null}y.u&&y.v&&y.v.disconnect()}function g(){if(!F){F=!0;var a=(new Date).getTime(),c=d._mpiv.startTime,a=c&&a>c?a-c:0;if(!(36E5<a)){var e=(c=G[v])&&c.Y();try{B({a:0,b:h,duration:a/1E3,Z:e?c.count:0,ma:e?c.total:0,na:e?c.max:0},b,4)}catch(f){}(a=(a=H[v])&&a.s())&&a.C()}}}var h=parseInt(99999*
Math.random()),v=a?a.id||"ad":"frame",f=G[v];f&&(f.b=h,setTimeout(function(){f.C(b)},3E5));var q;if(q=H[v])q.b=h,q.url=b;var k=0,p=0,r=-1,t=-1,u=-1,x=-1,D=!1,z=null,A=0;if(location.ancestorOrigins){var I=Q();try{B({a:0,b:h,ga:I},b,2)}catch(S){}}var F=!1;try{var E=/CriOS/.test(navigator.userAgent)?"unload":"beforeunload";d.addEventListener(E,g)}catch(S){}f&&(a?(a.onmouseenter=function(a){f.start(a)},a.onmouseleave=function(){f.end()}):d!=top&&(document.onmouseover=function(a){f.start(a)},document.onmouseout=
function(){f.end()}));var w=K();w.m&&(I=O(h),w.V=-1==I);w.m?(u=setInterval(function(){e(!1)},500),x=setTimeout(function(){e(!0)},6E4)):setTimeout(function(){e(!0)},100)}function M(a){Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){for(var c=b||0,d=this.length;c<d;c++)if(this[c]===a)return c;return-1});var b=a?a:"frame";if(-1!=z.indexOf(b))return!0;z.push(b);var c=a?document.getElementById(a):d.frameElement;y.u&&c?y.v.observe(c):y.u=!1;G[b]=new t(b);H[b]=new k(b);if(a=a&&a.id){if(-1!=
z.indexOf(a))return!0;z.push(a)}return!1}function T(a,b,c,d){return M(a)||"string"==typeof a&&(a=document.getElementById(a),null===a)?!1:L(a,b,c,d)}function U(a){return M(null)?!1:L(null,a)}p.prototype.J=function(a){var b=Math.max(this.t,a.t),c=Math.max(this.g,a.g);return new p(b,c,Math.max(Math.min(this.S,a.S)-b,0),Math.max(Math.min(this.r,a.r)-c,0))};p.prototype.G=function(){return this.xa*this.la};t.prototype.start=function(){this.startTime=(new Date).getTime()};t.prototype.end=function(){var a=
(new Date).getTime();0<this.startTime&&a>this.startTime&&(a-=this.startTime,a>this.max&&(this.max=a),this.total+=a);this.count++};t.prototype.Y=function(){var a=(new Date).getTime(),b=d._mpiv.startTime;return 0===this.count||this.count>(b&&a>b?a-b:0)/50||0===this.total||0===this.max||this.max>this.total||this.count>this.total/50?!1:!0};t.prototype.C=function(a){if(this.Y())try{B({b:this.b,a:0,count:this.count,duration:this.total,max:this.max},a,3)}catch(b){}};var G=[],E=[],C=[];r.prototype.ia=function(){var a=
!1;navigator.plugins&&navigator.plugins.length&&(a=!(!navigator.plugins["Shockwave Flash"]&&!navigator.plugins["Shockwave Flash 2.0"]));!a&&navigator.mimeTypes&&navigator.mimeTypes.length&&(a=navigator.mimeTypes["application/x-shockwave-flash"],a=!(!a||!a.enabledPlugin));if(!a)try{new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),a=!0}catch(b){a=!1}return a};r.prototype.ka=function(){var a="";try{for(var b=document.getElementsByTagName("script"),c=0;c<b.length;c++){var d=b[c].src;if(d.match(/mpiv\.js/i)){a=
d.replace(/\.js$/,".swf");break}}}catch(e){a=document.location.protocol+"//"+document.location.host+"/js/mpiv.swf"}this.P=a};r.prototype.va=function(a){switch(a){case 0:this.o=d.innerHeight/2;this.j=d.innerWidth/2;break;case 1:this.j=this.o=0;break;case 2:this.o=d.innerHeight-1;this.j=d.innerWidth-1;break;case 3:this.o=0;this.j=d.innerWidth-1;break;case 4:this.o=d.innerHeight-1,this.j=0}};r.prototype.ea=function(){if(!this.W||0===this.P.length)return!1;var a;try{a=document.createElement("OBJECT");
a.id=this.id;a.type="application/x-shockwave-flash";a.data=this.P;a.width="1";a.height="1";a.origwidth="1";a.quality="low";a.wmode="transparent";a.style.opacity=0;a.style.position="absolute";a.style.zIndex=-10;a.style.height="1px";a.style.width="1px";a.style.top=this.o+"px";a.style.left=this.j+"px";var b=document.createElement("PARAM");b.setAttribute("name","flashvars");b.setAttribute("value","adid="+this.id);a.appendChild(b);var c=document.createElement("PARAM");c.setAttribute("name","allowscriptaccess");
c.setAttribute("value","always");a.appendChild(c);document.body.appendChild(a)}catch(d){return!1}this.element=a;return!0};r.prototype.pa=function(){return!(!this.element||!this.element.isViewable)};x.prototype.add=function(a){A(a.h)&&(a.h=0,a.a|=8);a.a&8&&(this.T=1);a.c&&(this.c=a.c);this.f.push(a.h);this.end=a.timestamp;1==this.f.length&&(this.start=a.timestamp);this.K()&&this.C()};x.prototype.K=function(){return 150<=this.f.length};x.prototype.C=function(){if(!this.da&&0<this.f.length){var a=this.f,
b=!0;if(1<a.length)for(var c=a[0],d=1;d<a.length;d++)if(c!=a[d]){b=!1;break}a=b?""+this.f[0]:this.f.join("-");try{B({b:this.b,a:0<this.T?8:0,count:this.f.length,sa:this.ta,start:this.start,end:this.end,ra:a,c:this.c,A:this.A,qa:this.I},this.url,5),this.da=!0}catch(e){}}};var H=[];k.prototype.add=function(a){var b=this.ja(a.timestamp),c=b-this.$;if(!(0>=c||this.ba(a))){var d;d=this.L;d=30<c?{timestamp:a.timestamp,F:a.F,l:a.l,N:a.za,M:a.ya,a:a.a,c:a.Aa,hidden:a.hidden,h:0}:d&&d.h<a.h?d:a;for(var e=
1;e<=c;e++){var k=e==c?a:d;if(!this.ba(k)){var m=this.aa()?this.fa():this.s();m.add(k);1<e&&m.A++}}}this.$=b;this.L=a};k.prototype.fa=function(){var a=new x(this.B.length,this.b,this.url);a.I=this.H;this.B.push(a);return a};k.prototype.ja=function(a){return(a-this.ca)/100|0};k.prototype.s=function(){var a=this.B.length;return 0<a?this.B[a-1]:null};k.prototype.X=function(){return 4<=this.B.length};k.prototype.aa=function(){var a=this.s();return!a||a.K()};k.prototype.wa=function(){this.H=1;var a=this.s();
a&&(a.I=1)};k.prototype.ba=function(a){var b;(b=this.aa())&&!(b=this.X())&&(b=a.h,b=a.hidden||A(b)||0===b);return b};var y=new function(){function a(a){for(var c=0,d=a.length;c<d;c++){var e=a[c];y.ioStatusList[e.target.id?e.target.id:"frame"]=e}}this.v=null;this.u=!1;this.ioStatusList=[];try{this.v=new IntersectionObserver(a,{threshold:[.1,.15,.2,.25,.3,.35,.4,.45,.5,.55,.6,.65,.7,.75,.8,.85,.9,.95,.99,1]})}catch(b){}this.v&&(this.u=!0)},z=[];d._mpiv=d._mpiv||{mf:U,me:T,fl:N,oa:[1E3,5E3,1E4,3E4,6E4],
Ba:K,startTime:(new Date).getTime()}})(window);})();
